### ISSUE TITLE
How to print a string without the ending new line?

### ISSUE THREAD

**Issue by hcchengithub** [jcubic/jquery.terminal#124]
How to print a string without the ending new line?

term.echo() always prints a new line at the end.
I tried : term.echo("hello ",{flush:false}); term.echo("world!",{flush:false}); term.flush()
but it still prints,
hello\n
world\n
I tried this at : http://terminal.jcubic.pl/#demo , J/T version is 0.7.6
so am I using the right method?

**Comment by jcubic** [comment]
it was asked multiple times, from version 2.8.0 there is file that add newline option for echo. See #511
