### ISSUE TITLE
Not possible to paste serveral commands

### ISSUE THREAD

**Issue by mkschreder** [jcubic/jquery.terminal#136]
I'd like to be able to paste several lines with commands. the terminal should split pasted text at each line and execute each line as though it was a command. 

This is very useful for copy/pasting several lines of terminal commands.

**Comment by jcubic** [comment]
I've found this old issue, I think it will be good idea to add onPaste event and there you will be able to split on newline and call exec, return false will disable default paste. Will track the progress in #453
