### ISSUE TITLE
More control over echo and gets requested.

### ISSUE THREAD

**Issue by rdebath** [jcubic/jquery.terminal#140]
I've linked up this terminal to an in-browser javascript program over at <http://rdebath.github.io/LostKingdom/> and <https://github.com/rdebath/LostKingdom>.

For the most part it's working okay, and looks brilliant, but I had problems with linking them together.

My first issue was that the input and output to the 'terminal' are essentially independent streams; what I would have liked to be able to do is to turn off the prompt completely and have the last data printed by the application as the current prompt. The application would then print a string ">>> " without a newline and that string is the prompt.

To get it working I've had to fake this by buffering the line until the application sends a  newline and using 'set_prompt' with the remainder of the line. Plus some more messing about with newlines so they don't get duplicated. 

It works but it's messy.

**Comment by krainboltgreene** [comment]
An "append" like echo would allow for really easy "old school typewriter writing it out character by character" animations.

**Comment by jcubic** [comment]
@krainboltgreene you can do animations using command line insert or set_command methods. There is typewriter writing example on the site.

**Comment by krainboltgreene** [comment]
Oh man, I must have totally missed it sorry. I thought I looked at all the API documented :(

I'll check it out, thanks!

**Comment by jcubic** [comment]
I'm not planning to add echo without new line, closing.
