### ISSUE TITLE
dead keys on MacOS

### ISSUE THREAD

**Issue by patovala** [jcubic/jquery.terminal#158]
I'm having problems trying to use the terminal with us-international layout (Mac OS), specifically using " or ' and `  this chars have dead keys so, to type a quote ", you have to press the quote key followed by the SPACE key. Is this behaviour supported?

**Comment by jcubic** [comment]
Devel branch use event.key if supported by the browser here is [browser support](http://caniuse.com/#feat=keyboardevent-key) it seems that it's not supported by Safari.

**Comment by jcubic** [comment]
Finally was able to install MacOSX on virtualBox and fixed the issue

**Comment by jcubic** [comment]
the fix will be in version 1.0.7
