### ISSUE TITLE
Unable to use apostrophes for certain keyboard layouts.

### ISSUE THREAD

**Issue by Yatoom** [jcubic/jquery.terminal#179]
Keyboard layouts that require you to press an apostrophe `'` first and then another key (e.g. `', space`) for it to become visible, will not let you enter an apostrophe in the terminal. An example of a keyboard layout that does **not** work is the `US-International` layout. An example of a keyboard layout that does work is `International-AltGr` dead keys.

**Comment by jcubic** [comment]
It seems this is resolved tested US alternative multinational layout in both 0.11.23 and devel branch and I can type `'` by pressing `'` and space. I'm testing this on Xubuntu 16.04. Also devel branch (will be in next version 1.0.0) use event.key property to get the letter is browser support it so it should work with dead keys, this need to be tested.

**Comment by jcubic** [comment]
1.07 fixed #158 issue with dead keys on Mac and when I tested with US-alternative it work when I press <kbd>'</kbd> and <kbd>c</kbd> I've got `ć`.
