### ISSUE TITLE
default prompt character location

### ISSUE THREAD

**Issue by wankbank** [jcubic/jquery.terminal#180]
I'm unable to locate the default prompt character, as I'm interested in changing it:

``>``

I've looked through each `.js` file in addition to the `.css` and in every `jquery.terminal-*` file there is:

``prompt = options.prompt || '> ';``

However, changing the character seems to have no effect; I'm obviously missing something perhaps. 

In the documentation it reads:

``prompt [string|function] — default is “>” you can set it to string or function with one parameter which is callback that must be called with string for your prompt (you can use ajax call to get prompt from the server). You can use the same formatting as in echo.``

I'm totally lost on how that is done. Sorry if this is a really dumb question, but it seems I'm failing miserably in trying somehow to change a simple command prompt.

~ Thanks

**Comment by jcubic** [comment]
To change the prompt you need to use code like this:

```javascript
$('...').terminal($.noop, {
    prompt: '>>> '
});
```

**Comment by wankbank** [comment]
That works — thank you! :)

Just out of curiousity, what does the `default` prompt in `jquery.terminal-src.js` actually do?
```javascript
$.terminal.defaults = {
        prompt: '> ',</pre>
```
I thought this might be what I had overlooked originally, but changing `>` to `>>>` didn't affect it either.

**Comment by jcubic** [comment]
I need to remove this because it's the same as
```
prompt = options.prompt || '> ';
```
