### ISSUE TITLE
How to print wildcard instead of word

### ISSUE THREAD

**Issue by rahmanusta** [jcubic/jquery.terminal#185]
Hi, jquery terminal is qood product. Is there a way to print * instead of word and switch back another time? 

Thanks.

**Comment by jcubic** [comment]
You can't replace what's echo on terminal.

**Comment by rahmanusta** [comment]
That is weird. Why? How will i hide my ssh password??

**Comment by jcubic** [comment]
If you only want to hide the input then there is set_mask method.
```javascript
term.set_prompt('password: ');
term.set_mask('*');
```

**Comment by rahmanusta** [comment]
Thats great! Thanks.
