### ISSUE TITLE
Vim Support

### ISSUE THREAD

**Issue by rahmanusta** [jcubic/jquery.terminal#186]
Is it possible to use vim like editing with jquery terminal?

**Comment by jcubic** [comment]
What you mean by vim like editing?

**Comment by rahmanusta** [comment]
For example implemented a ssh client. And after connecting to remote OS, i used sudo vim abcd.php. This will open this file in terminal to edit. I wonder is there a standart way to implement in jq termimal?

**Comment by jcubic** [comment]
No but there is [jsvi](http://gpl.internetconnection.net/vi/) you can try to use it. I've move it to github [jcubic/jsvi](https://github.com/jcubic/jsvi) with plan to improve it. There is also my [micro editor](http://micro.jcubic.pl/) which is nano/pico implementation.

**Comment by rahmanusta** [comment]
Thanks. I will look them.
