### ISSUE TITLE
Responsive Terminal 

### ISSUE THREAD

**Issue by damienvaz** [jcubic/jquery.terminal#187]
So i was trying to involve your terminal for my web pages. And i saw that it wasn't responsive ( at least for me).
I don't know if it should be or not (being responsive) but in case it wasn't , i think you should add on your css file that :

`word-wrap: break-word;`

Like that all the lines from the terminal will contain to the visible area !
You can see on my webpage [DV](http://damienvaz.github.io)

**Comment by jcubic** [comment]
There is line wrapping in terminal, long lines are slit into multiple lines depend on width of the terminal. I've notice that there was a bug in that code and number of characters per line was calculated in wrong way, I've fix that in devel branch.
