### ISSUE TITLE
Star wars animation problems

### ISSUE THREAD

**Issue by damienvaz** [jcubic/jquery.terminal#188]
So, i saw your code from star wars animation and i thought it will be cool to add to my web page.
I saw that your code available [here](http://terminal.jcubic.pl/examples.php#starwars), had a problem !
The condition of that for-loop is wrong !

>for (var i=0; i>lines; i+=LINES_PER_FRAME) {
>        frames.push(star_wars.slice(i, i+LINES_PER_FRAME));
>    }

It should be lesser than and not greather than ! 

Regarding to this animation, can't we make it bigger for  a better visualization ?
My webpage : [DV](http://damienvaz.github.io)

**Comment by jcubic** [comment]
Only code that was show up was wrong, the code that was running was correct.

You can't make bigger terminal for some part of command, you will need to make animation outside of terminal.
