### ISSUE TITLE
incorrect formatting when url contains multiple parameters

### ISSUE THREAD

**Issue by pyakpyak** [jcubic/jquery.terminal#189]
when url formatting applied, resulting string doesn't contain parameters which were specified after first ampersand.

**Comment by jcubic** [comment]
It work for me if I use this url http://example.com?foo=bar&baz=quux

**Comment by y0ft88** [comment]
When I echo this url the formatting is broken (the last characters are not detected as part of the url) 
http://localhost:3000/dump/355136053206986-null/%D9%85%D9%84%D9%81%20%D8%AC%D8%AF%D9%8A%D8%AF?u=c6QqgwJzro3BhokNi&t=7vgv_K446-VYqDL7PL2AnQNgQ09uNtmLZVurTaduLbU

**Comment by jcubic** [comment]
it work for me, in devel branch without any error but on 0.8.8 I've got unclosed html entity error.

**Comment by y0ft88** [comment]
I'm using the devel version 0.9
![online tart shop](https://cloud.githubusercontent.com/assets/11421121/6598287/fef9cc4a-c7d8-11e4-926c-9bf4cd22acf5.png)

here a screenshot see last characters are not detected as part of the url

**Comment by jcubic** [comment]
It's because url is split into two lines. I don't know why in your case you have 2 lines that are blue. All parameters should be white in this case. I'll try to come up with formatting for urls so they will work even if they are split into multiple lines.

**Comment by pyakpyak** [comment]
Thank you for looking at this.

Just a little bit more context (sorry i've not provided it in the beginning):  i tested this with 0.8.8. I did echo(url, {raw: false}) of a url with parameters and it was broken.

Here is the url example:
http://test.myhost.com/requestDetails/spawn?typeFilter=t1,t2,t3,t4&nanosecondFilter=10000&data=9c51a787-ecc1-4f1a-bb4b-6b744cead65e-46262&env=test&region=us-east-1

I will try to migrate to the dev branch and see if the issue is still there.

**Comment by jcubic** [comment]
the url don't work.

**Comment by jcubic** [comment]
I've created formatting for url with exclamation mark, so your url will look like: `[[!;;]<URL>]`

I'll try to replace all urls with formatting so they always have full url.

**Comment by jcubic** [comment]
Now urls keep href even if they are split, and `[[!;;]<URL>]` is used internaly by terminal.
