### ISSUE TITLE
Selection CSS is very dark

### ISSUE THREAD

**Issue by rdejuana** [jcubic/jquery.terminal#193]
Your css for selection is very dark

![screenshot 2015-03-23 08 53 20](https://cloud.githubusercontent.com/assets/23434/6781236/2c1bedba-d13a-11e4-9148-edc4127b9667.png)
```
.terminal .terminal-output div div::selection,
.terminal .terminal-output div div a::selection,
.terminal .terminal-output div span::selection,
.cmd > span::selection,
.cmd .prompt span::selection {
    background-color: #aaa;
    color: #000;
}
```
May I suggest use white instead of black as the highlight color?

![screenshot 2015-03-23 08 54 55](https://cloud.githubusercontent.com/assets/23434/6781251/52c67d36-d13a-11e4-8d21-c226d81ac984.png)

```
.terminal .terminal-output div div::selection,
.terminal .terminal-output div div a::selection,
.terminal .terminal-output div span::selection,
.cmd > span::selection,
.cmd .prompt span::selection {
    background-color: #aaa;
    color: #fff;
}
```

**Comment by jcubic** [comment]
I prefer dark one, they are reversed default colors.

**Comment by rdejuana** [comment]
They might be reversed but they are hard to read.  

Never mind, I'll just override them locally.
