### ISSUE TITLE
[Feature Request] built in AJAX indicator

### ISSUE THREAD

**Issue by rdejuana** [jcubic/jquery.terminal#194]
I am making ajax calls to the server that might take a little time.  I have created a way to show an ajax indicator when making a call, but it would be nice to have a built in way.

What I am doing is something like this
```
$wp_cli.terminal handleCommand, ...

handleCommand = function() 
  term.echo('<i id="terminal-spinner" class="fa fa-spinner fa-spin"\>', {raw: true})
  term.pause()
 ...ajax call

handleAjaxCallResponse = function() 
   $('#terminal-spinner').closest('div + div').remove()
  term.resume()
```

I'd like something like 
```
 term.pause(indicator: true) or  term.pause('<i id="terminal-spinner" class="fa fa-spinner fa-spin"\>')
```
and have it automatically remove itself on on term.resume()

**Comment by jcubic** [comment]
In your code you should have indicator back in when you resize the browser.

**Comment by jcubic** [comment]
Spinner will not fit into terminal, real terminal or terminal emulator don't have one. I may only add blinking cursor on next line when terminal is paused.

**Comment by gpetrov** [comment]
a busy indicator will be very much appreciated. Its is very often needed and should be easily bound indeed with the term.pause and resume commands.

**Comment by jcubic** [comment]
I can add onPause and onResume events so users will be able to create indicators.

**Comment by gpetrov** [comment]
yes such events will be great :+1:

**Comment by jcubic** [comment]
I've added those events to devel branch.
