### ISSUE TITLE
unix ANSI support and problems with certain colors

### ISSUE THREAD

**Issue by kdar** [jcubic/jquery.terminal#199]
I decided to try to create a greetings banner with https://github.com/busyloop/lolcat, but it seems to convert some colors incorrectly.

Here is what it looks like:

![casperansi](https://cloud.githubusercontent.com/assets/119919/7213769/956ebfcc-e558-11e4-9e3a-5aca4b8b5b0b.png)

As you can see, some of the colors have backgrounds that shouldn't be there, and the foot is missing some color.

Here is the raw test ansi file:
http://privatepaste.com/c875396af1

Here is the ansi file but escaped so you can use `echo()`:
http://privatepaste.com/b9cc323018

**Comment by jcubic** [comment]
Fixed in devel branch, you will need jquery.terminal file and unix_formatting.js
