### ISSUE TITLE
Right-sided padding appears upon overflow scrollbar

### ISSUE THREAD

**Issue by tasl33m** [jcubic/jquery.terminal#201]
(I've also posted this on Stackoverflow ... http://stackoverflow.com/questions/29877421/right-sided-padding-appears-upon-overflow-scrollbar)

The terminal works fine until I type a few commands where the overflow kicks in and all of a sudden padding is shown on the right. It is extremely annoying and probably has a bit to do with JQuery Dialog. Despite hiding the scrollbar the padding still shows.

Anyone know how to fix this? I'm assuming it's all in the CSS. Direct link: http://chaostheorem.com/android/jquery.terminal.css

Simple site: http://www.chaostheorem.com/android/

Starting:
http://i.stack.imgur.com/YqxIe.png

So far so good:
http://i.stack.imgur.com/kBOmd.png

Overflow with right-sided padding, DAMMIT!:
http://i.stack.imgur.com/2LEZp.png

**Comment by jcubic** [comment]
I think that's not padding but line wrap, when there is scrollbar it make less characters per line. I've notice that there was bug in version 0.8.8 I've fixed that in devel branch but in your example the line wrap is ok when there is no scrollbar.

You can try to add option `outputLimit: 0` it will disable scrollbar by showing only that many lines how many there is rows.

**Comment by tasl33m** [comment]
Thanks for the quick reply. I added in outputLimit: 0 (as you can see online), and it does appear to work initially, but what happens now is you can't scroll back up (ie. you lose the history of commands you first started with).

**Comment by jcubic** [comment]
It's exactly what `outputLimit: 0` do, you don't have scroll.
