### ISSUE TITLE
IE Blocker issue with Terminal Open.Window()

### ISSUE THREAD

**Issue by tasl33m** [jcubic/jquery.terminal#203]
Problem as described over on Stack: http://stackoverflow.com/questions/29890246/ie10-blocker-window-open-issue

I have a problem only affecting IE and no other browser (what's new?)

I'm using jquery-terminal (http://terminal.jcubic.pl) here where the user can input a command into a prompt and based on their command a window will popup and take them to a specified URL.

Eg: If a user types google into the command prompt it should open a new window and take them to www.google.com
```javascript
if (command.match(/^\s*google\s*$/i)) {
   window.open('http://www.google.com', '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes');
else if ... bing, yahoo, etc.
```

Okay, so IE will open the window and load the URL the first time without any hiccup if the user types 'google'. The problem arises when the user closes that window and goes to type in 'google' again, the window loads with a blank page instead of going to the URL.

So I ask, is there a way to fix this via code, or is IE trying to protect the user in its own way (ie. Settings problem?).

Thanks in advance.

**Comment by jcubic** [comment]
It work as expected on Windows 7 / IE10 I get same url when I type google few times, but it redirect me to `google.pl`. Can you create a demo with the problem?
