### ISSUE TITLE
Consider moving to the MIT license

### ISSUE THREAD

**Issue by caniszczyk** [jcubic/jquery.terminal#204]
It would be great to use this library for documentation projects hosted at apache.org, however, they don't allow works under the LGPL: http://www.apache.org/legal/resolved.html#category-x

Would love for you folks to consider moving to the MIT license which would help resolve this issue and is the primary license used in jquery land these days.

Thanks for your consideration

**Comment by samdark** [comment]
+1. MIT is much better.

**Comment by mickeyvip** [comment]
As I was pointed out by James Ward:
  
  The Bower metadata doesn't contain a valid spdx license identifier: 
  https://github.com/jcubic/jquery.terminal/blob/master/bower.json#L10

**Comment by jcubic** [comment]
I've already added url to package.json but it need to wait for the next release

**Comment by jcubic** [comment]
New version 0.10.0 will use MIT license.

**Comment by jcubic** [comment]
New version 0.10.0 with MIT license is available.
