### ISSUE TITLE
Problem when destroy terminal

### ISSUE THREAD

**Issue by thducuit** [jcubic/jquery.terminal#205]
I debug when destroy terminal, I see you write this line code. (line 699 in file jquery.terminal-0.9.0_dev.js)
            remove: function(index) {
                data.splice(index, 0);
            },

This code I think may have problem. I think 0 should be replaced by 1).
Because current code doesn't remove old terminals. So, this will cause memory leak.

**Comment by jcubic** [comment]
Fixed, thanks for pointing that out.
