### ISSUE TITLE
saving and restoring state of terminal

### ISSUE THREAD

**Issue by genbod** [jcubic/jquery.terminal#208]
export_view and import_view are very useful for restoring the visual state of the terminal, but what about history and any nested interpreters?  I am using jquery.terminal in a durandal ( knockout.js) single page web app and even though I save a reference to the plugin in my view model, every time I compose the view for the tab, the view is rebound and a new terminal object is created.  I have used:

                    term.import_view(self.term.export_view());
In the OnInit function to transfer the visual state from the saved terminal reference to the newly bound one and it looks great.  However, the other internal state obviously is not transferred, so history doesn't work and I am no longer nested inside of interpreters.  Is there any way to save/restore state for the jquery.terminal?  I have also tried term = self.term because I thought term was being passed by reference but history and interpreter stack still doesn't seem to transfer.

**Comment by jcubic** [comment]
In devel branch it now save and restore interpreter stack.

**Comment by genbod** [comment]
Nice!  I cant wait to try it out.  Incredible plugin 😊

Sent from my Windows Phone
________________________________
