### ISSUE TITLE
Pressing SHIFT clears current line

### ISSUE THREAD

**Issue by hreinhardt** [jcubic/jquery.terminal#209]
(This bug occurs in the devel branch)

How to reproduce:
1. Press and hold the 'a'-key (or any other character key)
2. Press and release the SHIFT-key

The current line will be deleted.

I believe the following code is responsible for this bug:
```javascript
if (no_keypress) {
    // Some Androids don't fire keypress - #39
    self.set(clip.val());
}
```

**Comment by hreinhardt** [comment]
Unfortunately the commit doesn't fix the issue for me (tested in Opera, Chrome and Firefox).

**Comment by jcubic** [comment]
I'm unable to reproduce the bug anymore.

**Comment by hreinhardt** [comment]
With the commit you added the behaviour slightly changes. The line is now cleared after releasing the 'a'-key. So to reproduce:

1. Press and hold the 'a'-key
2. Press and release the SHIFT-key
3. Release the 'a'-key

**Comment by jcubic** [comment]
Now it should work.

**Comment by hreinhardt** [comment]
Great, thanks.
