### ISSUE TITLE
Display linux terminal like progress

### ISSUE THREAD

**Issue by samundrak** [jcubic/jquery.terminal#211]
Is there any api to display linux terminal like progress
like / | \ -

**Comment by jcubic** [comment]
You can use prompt for that like this:
```javascript
var anim = ['/', '|', '\\', '-'];
var i = 0;
var delay = 400;
(function animation() {
  term.set_prompt(anim[i++]);
  if (i > anim.length-1) {
    i = 0;
  }
  setTimeout(animation, delay);
})();
```

**Comment by samundrak** [comment]
Ok ! Thanks for your help :)

**Comment by jcubic** [comment]
Also if you want to have animation you will need to stop keypress and keydown events like in [user typing animation](http://terminal.jcubic.pl/examples.php#user-typing)
