### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by jloveric** [jcubic/jquery.terminal#213]
I don't see an npm package for this, seems like there should be one.  Looks like a nice program though.

**Comment by jcubic** [comment]
There is bower package that someone created.

**Comment by michaelvashchinsky** [comment]
+1 for NPM.

Yes, but with all the process of migrating to NPM, I think NPM package will be a good thing to have.

**Comment by jcubic** [comment]
You can now install jQuery Terminal from npm.

**Comment by michaelvashchinsky** [comment]
Thank you so much!
