### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by iamdriz** [jcubic/jquery.terminal#214]
Is it possible to provide options for the user to then select using the keyboard?

For example they might type `inbox` which returns a list of mail items, that they can then highlight using the arrow keys and hit return to then read this mail item. Or they might have to choose an option or go back / cancel.

Is this possible? The best example I can come up with is a screenshot from a game: http://staticdelivery.nexusmods.com/mods/130/images/46226-1-1337484046.jpg

**Comment by jcubic** [comment]
No you can't use arrows to pick the option, the only thing you can do is to add new interpreter when user type `inbox`, print the list and ask the person to type another command that will pick the right email.
