### ISSUE TITLE
How to change number of characters?

### ISSUE THREAD

**Issue by sumy7** [jcubic/jquery.terminal#215]
Hello.
I have try jquery.terminal today. It's cool. But I ran into a problem.
I resize the term to 426px width, but only got 35 characters per line. It's the half of one line.
I found that the number of characters relative to `num_rows`.

I want to fill up the whole line. Is there any way or trick to solve this problem?
*sorry for my English.*

**Comment by jcubic** [comment]
You should have about 55 characters. Do you have a demo where this is happening, where I can try things out? Maybe [jsfiddle](http://jsfiddle.net/)?

**Comment by sumy7** [comment]
I copy my code to jsfiddle. [http://jsfiddle.net/sumy/f7qdrp1y/](http://jsfiddle.net/sumy/f7qdrp1y/)

**Comment by jcubic** [comment]
You need to set the same font on .terminal because it's used for character calculation:

```css
.terminal {
  font-family: fantasquesansmono;
}
```
You will have 67 characters http://jsfiddle.net/f7qdrp1y/3/

**Comment by sumy7** [comment]
Thanks a lot. 
I add the css, and clear browser cache, then it works.

**Comment by sumy7** [comment]
Thanks for your suggestion. I try this method in my blog, but it didn't work. /(ㄒoㄒ)/~~ 

You notice that the problem is cause by `font-family`,  I want to say what I understand.
In the function `char_size()` [function](https://github.com/jcubic/jquery.terminal/blob/master/js/jquery.terminal-0.8.8.js#L2391-L2401), a fake terminal created calcualte the dimention of `&nbsp;` representing one character. the normal `<span>` width is 6, but my is 12.
font-family from [jquery.terminal.css](https://github.com/jcubic/jquery.terminal/blob/master/css/jquery.terminal.css#L90) is 
```css
.terminal, .cmd {
    font-family: FreeMono, monospace;
}
```
I don't have FreeMono and monospace in my computer. so a default font which have a big `&nbsp;` would be selected.
My solution is using a higher priority selector to make my font-family be selected.
```css
.terminal span{
    font-family: fantasquesansmono !important;
}
```

**Comment by jcubic** [comment]
monospace is meta name same as sans or sans-serif it will pick the font of that type.
