### ISSUE TITLE
Authentication token

### ISSUE THREAD

**Issue by iamdriz** [jcubic/jquery.terminal#216]
In past applications that use a JavaScript front-end that requires authentication I have used an access token that is passed to every API endpoint that checks its valid before returning the data. Does this terminal plugin automatically pass the token when stored to every command in the RPC file (except for the login command?)

**Comment by jcubic** [comment]
yes

**Comment by iamdriz** [comment]
@jcubic In the RPC demo if you type `exit` you leave the login prompt and just get the initial prompt.
If you were to create a login command (when the user types login or requests another command) could you then call the login again? As from what I am seeing it just says `[AUTH] Access denied (no token)`. So is the plugin listening for a command called 'login' to prevent that error when no token exists?

**Comment by iamdriz** [comment]
Also noticed a bug, if you enter the password `exit`, it then exists the current login prompt and then asks for a login again but uses the asterisk when typing:
![screen shot 2015-12-12 at 15 36 12](https://cloud.githubusercontent.com/assets/801252/11762670/5399b026-a0e6-11e5-98e8-6bcd9fe4d997.png)

**Comment by jcubic** [comment]
Fixed in last commit to devel.

**Comment by iamdriz** [comment]
What about this: https://github.com/jcubic/jquery.terminal/issues/216#issuecomment-164161838 is this correct that the plugin overrides the auth error if the command typed is login?

**Comment by jcubic** [comment]
It just call login as normal auth method with token as first argument, I should probably remove login from command list.

**Comment by iamdriz** [comment]
@jcubic If you have login option set to true for an interpreter is that all commands typed just return `[AUTH] Access denied (no token)` (regardless whether they exist in the RPC or not) if you are not authenticated. Shouldn't the plugin pass the command to the server regardless and let the server decide if it requires authentication rather than the authentication being set client side?

**Comment by jcubic** [comment]
If you're not authenticated you can't type commands and now when I removed exit from login and password you should never see `[AUTH] Access denied (no token)`, it should only happen if you remove token from localStorage by hand.

**Comment by iamdriz** [comment]
@jcubic Ah okies so that prevents you from seeing it. I've noticed that you have put the fix in the devel branch but not the master. And the master (at the time of writing) is 12 commits ahead and 165 commits behind, meaning things have been added to both... are you planning on merging these?

**Comment by jcubic** [comment]
I wanted to have fixed Android issue for 0.9 version, but I think I just merge and release the 0.9 version without that fix.

**Comment by jcubic** [comment]
I've merge the branches.
