### ISSUE TITLE
[AJAX] Invalid JSON

### ISSUE THREAD

**Issue by iamdriz** [jcubic/jquery.terminal#217]
When trying the RPC example I get this error (regardless of what is typed for username/password):

~~~
[AJAX] Invalid JSON - Server reponse is: 
<br />
<b>Warning</b>:  get_object_vars() expects parameter 1 to be object, string given in <b>/Users/cameron/Sites/terminal/examples/json-rpc/json-rpc.php</b> on line <b>75</b><br />
<br />
<b>Warning</b>:  get_object_vars() expects parameter 1 to be object, string given in <b>/Users/cameron/Sites/terminal/examples/json-rpc/json-rpc.php</b> on line <b>75</b><br />
<br />
<b>Warning</b>:  get_object_vars() expects parameter 1 to be object, string given in <b>/Users/cameron/Sites/terminal/examples/json-rpc/json-rpc.php</b> on line <b>75</b><br />
{"jsonrpc":"2.0","result":null,"id":"2","error":{"code":-32600,"message":"Invalid Request: no method"}}
~~~

**Comment by jcubic** [comment]
I don't get that error, do you have live demo?

**Comment by iamdriz** [comment]
@jcubic  It's just the one I've downloaded from the main website.

**Comment by iamdriz** [comment]
@jcubic If I do a var_dump at line 75 where it's used to see what the $object is that is passed to the function I get: `string(67) "{"jsonrpc":"2.0","method":"login","params":["demo","demo"],"id":3}"`

**Comment by iamdriz** [comment]
@jcubic Here's an example of it running: http://dev.driz.co.uk/terminal/examples/rpc-demo.html

**Comment by jcubic** [comment]
Did you modify `json-rpc-service-demo.php` to use local `json-rpc.php` file instead of the one from submodule? I need to remove local json-rpc.php file.

**Comment by jcubic** [comment]
Can you try again downloading the code, I've removed json-rpc submodule and use modifed json-rpc.php from the json-rpc repo.

**Comment by iamdriz** [comment]
@jcubic Yeah I was using the local version. Fixed now.
