### ISSUE TITLE
Keydown event for arrow keys does not fire when the terminal has focus

### ISSUE THREAD

**Issue by arcadiogarcia** [jcubic/jquery.terminal#218]
As the title says, the keydown event does not fire for arrow keys when the terminal has focus, but it does for other keys though. I guess this is necessary to enable some features such as history, but it would be nice to be able to add our listeners that receive all the keys that have been pressed, in order to be able to implement other features (I'm currently trying to implement Ctrl+Arrows key bindings).

**Comment by jcubic** [comment]
This work for me in latest version:
```javascript
  $('...').terminal($.noop, {
    keydown: function(e) {
      console.log(e.which);
      if (e.ctrlKey && (e.which == 38 || e.which == 40)) { // up/down arrows
        return false;
      }
    }
  });
```
Can you provide jsfiddle with the problem?

**Comment by arcadiogarcia** [comment]
I was trying with vanilla JS, listening for keydown globally: http://jsfiddle.net/4fp6onvv/7/ , shouldn't that also work?

**Comment by jcubic** [comment]
It work for me on Chromium on GNU+Linux

**Comment by arcadiogarcia** [comment]
I'm having the issue on Edge/FF/IE on W10, I'll try in Chrome

**Comment by jcubic** [comment]
You're right it don't work in Chromium too.

**Comment by jcubic** [comment]
It's because terminal `return false` in keydown, why don't you just use keydown callback?

**Comment by arcadiogarcia** [comment]
The callback does the job perfectly, thanks for your help!
