### ISSUE TITLE
echo {raw:true} not always obeyed

### ISSUE THREAD

**Issue by shayping** [jcubic/jquery.terminal#219]
My understanding of echo is that is {raw:true} is provided in the options, the raw string provided to echo will be presented. 
However if I do
  `term.echo('<div>hey [[ there ]]<div>', {raw:true, exec:false})`
process_line always strips out "[[ there ]]" which is not what I expect. 

I think process_line should just pass string directly to buffer_line() is raw:true ... ??

**Comment by jcubic** [comment]
Should work now in devel branch.
