### ISSUE TITLE
Multiline Input

### ISSUE THREAD

**Issue by ghost** [jcubic/jquery.terminal#22]
Admittedly this is a niche case, but it would be a nice configurable feature for the plugin to count the number of opening braces/parens/brackets and continue to accept input until the count is zero for each.

**Comment by Totktonada** [comment]
It was not easy to find, so I'll leave here the link: https://github.com/jcubic/jquery.terminal-www/blob/a4c593e516b738d361a745a214ce852306cda9b4/examples.php.in#L2265-L2296

**Comment by jcubic** [comment]
IMHO better multiline is Shift+Enter, I've created better parenthesis match but in single input here https://jcubic.github.io/lips/ (source: https://github.com/jcubic/lips/blob/gh-pages/index.html#L192)

**Comment by jcubic** [comment]
But there is also an option to overwrite ENTER keymap and insert newline when parenthesis are not balanced, I'll try to create example or update my parenthesis matching.

**Comment by Totktonada** [comment]
Our case is when a backend is responsible for distinguish whether a command is incomplete. But I guess I'm able to implement it just on server side and allows a client to send incomplete commands (maybe prompting will need some tweaking).

**Comment by jcubic** [comment]
Here is better solution, for your case:
```javascript
 var term;

 $(function() {
     term = $('<div/>').attr('id', 'term')
         .appendTo('body')
         .terminal(function(command) {
            this.echo('executing ' + command);
         }, {
             name: 'portfolio',
             keymap: {
                ENTER: function(e, original) {
                    this.pause();
                    $.jrpc('service.php', 'enter', [this.get_command()],
                        (response) => {
                            console.log(response);
                            if (response.result == '__ENTER__') {
                                this.insert('\n');
                            } else if (response.result == '__EXEC__') {
                                original();
                            }
                            this.resume();
                        }
                    );
                }
            },
             prompt: 'exec> '
         });
 });
```

```php
<?php

require('json-rpc.php');

if (function_exists('xdebug_disable')) {
    xdebug_disable();
}

function balance($code) {
    $pa = str_split(preg_replace("/[^()]/", "", $code));
    $i = 0;
    foreach ($pa as $p) {
        if ($p == '(') {
            $i++;
        } else if ($p == ')') {
            $i--;
        }
    }
    return $i;
}

class Service {
    function enter($code) {
        $p = balance($code);
        if ($p < 0) {
            throw new Exception("Parenthesis error");
        } else if ($p > 0) {
            return "__ENTER__";
        } else {
            return "__EXEC__";
        }
    }
}

handle_json_rpc(new Service());

?>
```

Instead of JSON-RPC you can use normal ajax call and inside interpreter function you can call ajax. The only limitation is that you will have two requests. If you want one you will to put your code instead of "__EXEC__" and return exec value if result will be __ENTER__ you insert `\n` normaly but if you have different value you just echo it and call `original()` note this in this case your interpreter can be empty (use `$.noop`) it will be only use to handle displaying of prompt.
