### ISSUE TITLE
How do you get a reference to the new terminal after calling term.push(...)?

### ISSUE THREAD

**Issue by arcadiogarcia** [jcubic/jquery.terminal#220]
I am pushing a new terminal with term.push(callback, options); and then I want to be able to pop it outside the callback function, is there a way to get a reference to the new terminal before even the callback function is executed? It would be intuitive that the push function returned it, but apparently it returns the same terminal.

**Comment by jcubic** [comment]
there is only one terminal instance per terminal. `push()` don't create new terminal.

**Comment by arcadiogarcia** [comment]
Oh, then why (after pushing once and poping once) do I get a message saying "You can't exit from the main interpreter"? The pop works but it seems to try to pop all the way to the bottom though.

**Comment by jcubic** [comment]
Can you show your code?

**Comment by arcadiogarcia** [comment]
Oops sorry, I just found the issue, I didn't know the library already implemented Ctrl+D, so I implemented my own on top... causing it to pop twice.
