### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by hervethouzard** [jcubic/jquery.terminal#221]
Hello,

Is the Ajax query using a timeout? 
Sometimes I don't reveive answer (data) from my Php script whereas there's no error in my code?

bye

**Comment by jcubic** [comment]
No it don't use timeout. Can you show your code?

**Comment by hervethouzard** [comment]
Hello,

I can's show you my Php code, it's confidential, it just reads some records from a database.
My JS code is really simple:
`
      jQuery(function($, undefined) {
          $('#term_demo').terminal("excalibur.php", {
              greetings: greetings(),
              height: 500,
              width: '80%',
              completion: true,
              prompt: 'Nestor> '
          });
      });
`

**Comment by jcubic** [comment]
Do you use `json-rpc.php` that's in example directory? do you get error in developer tools?

**Comment by hervethouzard** [comment]
Yes I'm using it.
No I d'ont have any error message.
The same Php script with a different (shorter) query will run

**Comment by jcubic** [comment]
What is server response whe this happen?

**Comment by hervethouzard** [comment]
There's no answer, as if the communication were closed.

**Comment by jcubic** [comment]
Try adding:
```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```
in php

**Comment by hervethouzard** [comment]
Hello,

There's no error, in fact I beleive that the content returned by the Php script is causing the problem.
Give me some time and I will tell you if the problem is coming from this.

**Comment by hervethouzard** [comment]
Hello,

The problem was coming from the french é character which is in my content !
I have to convert the content to UTF8

You can close this ticket, sorry for disturbing you.
