### ISSUE TITLE
Can't Paste in Firefox on Linux

### ISSUE THREAD

**Issue by xloem** [jcubic/jquery.terminal#223]
I can't paste in jquery-terminal .

I'm using Firefox 38.5.0 with NoScript 2.9.0.2 (and the page in question allowed).  I'm running Gentoo Linux.

All of right-clicking, ctrl-v, and middle-clicking do nothing.

**Comment by jcubic** [comment]
Did you try version in devel branch?

**Comment by xloem** [comment]
Oh, you're right, it's fixed in git!  Even the master branch works fine.  I was using 0.9.3 release.

**Comment by jcubic** [comment]
Are you sure master branch work? it should be the same as on the site - 0.9.3.

**Comment by xloem** [comment]
I'm on master it's working.  master branch was last committed to Thu Jan 21 2016 in 76373c2fdc, 0.9.3 was tagged Thu Dec 24 2015 in 8f7d5e0999

**Comment by jcubic** [comment]
I've only added missing css file to master branch, weird.

**Comment by xloem** [comment]
Hrm even 0.9.3 tag is working for me.  I'm testing with the tilde example.  Something must be different between the example and my actual site

**Comment by xloem** [comment]
Okay, I was confusing myself.
Ctrl-V seems to be working fine, even on my site.  I must have made a mistake finding it not working.
Pasting with the context menu does not work, even in the devel branch.

**Comment by xloem** [comment]
no, ctrl-v does not work on my site.  i was accidentally testing locally; it works from file:/// but not http://

my brain is pretty confused by now

**Comment by xloem** [comment]
no, it works fine
my clipboard just became emptied for some reason between loading the pages .
perhaps my computer has some other issue
