### ISSUE TITLE
creating an interpreter via object doesn't call completion function

### ISSUE THREAD

**Issue by XpressiveCode** [jcubic/jquery.terminal#224]
I might be setting this up wrong, but walking through the code, it hits

```
else if (type === 'object') {
                finalize({
                    interpreter: make_object_interpreter(user_intrp,
                                                        settings.checkArity),
                    completion: Object.keys(user_intrp)
                });
```

It doesn't ever attempt to use the `settings.completion`  

```
el.terminal({ 
        foo: function(){ this.echo('foo'); }
    },{
    completion: function(term, command, callback){
            console.log('nope');
        }
    });
```

Attempting to override via the option function, does in fact override it to use the function, but then in the comparison against the top.completion, it loses out and the top version is used, which is the command list of methods found in the object.

```
 if ((settings.completion &&
                     $.type(settings.completion) != 'boolean') &&
                    !top.completion) {
                    completion = settings.completion;
                }
```
Because top.completion has the original method names in an array, it trumps the updated settings.completion?

Hopefully I've just set this up incorrectly. Any help would be appreciated.

**Comment by jcubic** [comment]
Fixed in devel branch.
