### ISSUE TITLE
On small screens, terminal character width is calculated incorrectly

### ISSUE THREAD

**Issue by mrlowe** [jcubic/jquery.terminal#225]
This means long lines extend past the right edge of the terminal. Here's a codepen example that demonstrates the issue:

http://codepen.io/anon/pen/VeGEKE

I noticed this on a mobile device, but it also happens in a desktop browser when you shrink it down to about 450px. I'll submit a pull request with a fix in just a minute.

**Comment by jcubic** [comment]
Thanks for the fix.
