### ISSUE TITLE
Suppress error messages

### ISSUE THREAD

**Issue by Tomaltach** [jcubic/jquery.terminal#228]
Is there a way to suppress error messages from being outputted to the terminal. I have my own errors messages being echoed out, but I still get the exception error shown as well.

Just would like to know is there an option like the scrollbar that can be turned on and off.

Thanks.

**Comment by jcubic** [comment]
you can add this option:
```
exceptionHandler: $.noop
```

**Comment by Tomaltach** [comment]
Perfect. Thanks :D
