### ISSUE TITLE
Terminal slightly broken for safari private mode

### ISSUE THREAD

**Issue by yutongluo** [jcubic/jquery.terminal#229]
In Latest Safari Version 9.0.3 (11601.4.4), if you private browse the Terminal becomes broken. In my case the greeting did not show up and commands require pressing the enter key twice. For the examples, the tilda-demo is also broken (shows up initially without pressing tilda, press enter twice to enter command).

The javascript console error shows:
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

This is because Safari safe browsing prevents writing to localStorage completely. See 
[here](http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an).

**Comment by jcubic** [comment]
Thanks for the fix.
