### ISSUE TITLE
Completion always pushing "clear" and "exit"

### ISSUE THREAD

**Issue by onliners** [jcubic/jquery.terminal#232]
Hi,

Thanks a lot by this awesome script! 

I've setted completion as array of commands. Then, everytime I press TabTab commands "clear" and "exit" get added multilpe times. 

Because complete_helper() does command.push without checking.

I've fixed by adding condition "$.inArray('clear',commands)==-1". 

Although, that will only work if completion settings is an array.

Best regards.

**Comment by remram44** [comment]
I'm also affected by this.

**Comment by jcubic** [comment]
Fixed in devel branch. Your `$.inArray` in `complete_helper` will work for both array and function.
