### ISSUE TITLE
Can you update your up to date js and css file without version number?

### ISSUE THREAD

**Issue by dannyxx001** [jcubic/jquery.terminal#233]
Hello, I'm an intern of cdnjs. (https://github.com/cdnjs/cdnjs)

I want to send pull request to merge your lib, but the filename can't contain version number.

So, would you please update your filename?

Best regards.

**Comment by jcubic** [comment]
There is minified version don't contain version number [jquery.terminal-min.js](https://github.com/jcubic/jquery.terminal/blob/master/js/jquery.terminal-min.js)

**Comment by dannyxx001** [comment]
Sorry, I may make some mistake because I suppose the css file is not up to date by the update time.

Thanks for your response.
