### ISSUE TITLE
marking an expression with a mouse double click does not work from mac on chrome

### ISSUE THREAD

**Issue by DavidBord** [jcubic/jquery.terminal#234]

**Comment by jcubic** [comment]
In what browser? Did you check devel branch?

**Comment by DavidBord** [comment]
Chrome
Nope, v0.8.8

**Comment by jcubic** [comment]
Try latest 0.9.3 it work in chrome but not in IE

**Comment by DavidBord** [comment]
When upgrading to 0.9.3 marking an expression with a mouse double click does not work from mac on chrome

**Comment by jcubic** [comment]
By "marking an expression with a mouse double click" you mean selecting text inside terminal?

**Comment by DavidBord** [comment]
yes

**Comment by jcubic** [comment]
Should be fixed in version 0.11.2.
