### ISSUE TITLE
Is it possible to use `.min.(js|css)` instead `-min.(js|css)` in the filename?

### ISSUE THREAD

**Issue by PeterDaveHello** [jcubic/jquery.terminal#238]
Since it's more commonly used, not sure if you would agree this :smile:

**Comment by jcubic** [comment]
What's the difference? Why would you need this?

**Comment by PeterDaveHello** [comment]
Thanks for your prompt reply, the only difference is `.min.js` is more commonly used then `-min.js`, before #237, cdnjs needs to manually minify the css file, the naming follows the more commonly used `.min.css`, I wonder if it's possible to make the structure consistent, so the users of jquery.terminal on cdnjs don't need to manually change `-min` to `.min` or vise versa between versinos, but it's only a disscussion, I'll totally respect your dicision, thanks!

PS: jquery.terminal on cdnjs: https://cdnjs.com/libraries/jquery.terminal

**Comment by jcubic** [comment]
Changed in version 0.10.4.

**Comment by PeterDaveHello** [comment]
Thanks @jcubic

**Comment by jcubic** [comment]
I've added new file js/jquery.terminal.js to have both minified and unminified versions in cdn. Does it need to be updated by hand again or it will update automatically.

**Comment by PeterDaveHello** [comment]
@jcubic I'll manually commit it again, after that, the bot can handle the new versions!

**Comment by jcubic** [comment]
thanks

**Comment by PeterDaveHello** [comment]
You're welcome.
