### ISSUE TITLE
"exit" is never evaluated 

### ISSUE THREAD

**Issue by prot0man** [jcubic/jquery.terminal#239]
My desired result is to actually have exit evaluated and passed to terminal (but not cause the shell to exit--I'm handling that elsewhere). So in my settings, I set exit to false and notice that whenever I enter exit, it never makes it to the terminal. So I dug into jquery.terminal-0.10.5.js, and found the issue to be in the commands function where you match "exit" and "clear". The problem is that the interpreter never invokes the command. I made the following modification which now has the behavior I expected:
```javascript
                    if (settings.exit && command.match(/^\s*exit\s*$/i)) {
                        var level = self.level();
                        if (level == 1 && self.get_token() || level > 1) {
                            if (self.get_token(true)) {
                                self.set_token(undefined, true);
                            }
                            self.pop();
                        }
                    } else if (settings.clear && command.match(/^\s*clear\s*$/i)) {
                        self.clear();
                    } else{
                      var result = interpreter.interpreter.call(self, command, self);
                    } 
```
The change is the else case.

**Comment by jcubic** [comment]
Thanks for your report, I'll incorporate your fix.
