### ISSUE TITLE
First argument as array with function breaks terminal

### ISSUE THREAD

**Issue by nyariv** [jcubic/jquery.terminal#240]
The terminal fails to load if there is a function in the array.

This loads:
`$('#terminal').terminal([{}], {prompt: '$ ', greetings: "Test"});`

But this doesn't:
`$('#terminal').terminal([{}, function(command, term) {}], {prompt: '$ ', greetings: "Test"});`

**Comment by jcubic** [comment]
The function need to be the last element of the array because it's executed when no methods found.

**Comment by jcubic** [comment]
Fixed in 0.10.7

**Comment by nyariv** [comment]
Perfect. It is now working. But it seems there are a couple of console logs remaining in the code.

**Comment by jcubic** [comment]
I've left them by mistake, you can grab the file from repo it's removed, byt npm and cdn version have them.

**Comment by nyariv** [comment]
Thanks.
