### ISSUE TITLE
tabcompletion

### ISSUE THREAD

**Issue by hervethouzard** [jcubic/jquery.terminal#241]
Hello,

How do you use tab completion with a JSON-RPC server?

I have tried everything I could nothing runs.
My JSON-RPC server, a Php script, returns everything needed, including documentations, in my terminal declaration I have added something like this:

tabcompletion: ['who', 'cd', 'test', 'ls', 'clear', 'pwd'],
I also tried:
tabcompletion: true,
completion: true,

But nothing happend when I hit the tab key ...???

**Comment by jcubic** [comment]
If you're using json-rpc implemenation from examples then you can use:
```javascript
completion: true,
```
otherwise you need to explicitly pass array of commands:
```javascript
completion: ['who', 'cd', 'test', 'ls', 'clear', 'pwd'],
```
tabcompletion was removed in version 0.8.0

**Comment by hervethouzard** [comment]
Hello,

Thank you for your answer.
That's what I have done but typing the TAB key does not complete my commands....???

**Comment by jcubic** [comment]
Can you show your code?

**Comment by hervethouzard** [comment]
Here it is:

`  		function greetings()
  		{
  			return '** Bienvenue **';
  		}
  		jQuery(function($, undefined) {
  			$('#term_demo').terminal("http://192.168.0.8/test.php", {
  				greetings: greetings(),
  				height: 500,
  				width: '80%',
  				completion: true,
  				prompt: 'Nestor> '
  			});
  		});
`

**Comment by jcubic** [comment]
do you use json-rpc.php file from examples directory?

**Comment by hervethouzard** [comment]
Yes, problem solved by updating to the last version, I was using verion 0.9.
Sorry...
