### ISSUE TITLE
blinking problem with minified css

### ISSUE THREAD

**Issue by arkanovicz** [jcubic/jquery.terminal#242]
Using jquery.terminal-0.10.11.min.css stylesheet breaks cursor blinking.

Tested with:
- Chromium 48.0.2564.116 
- Firefox 44.0.2
on Ubuntu 15.10 (64-bit)

No special terminal option used.

The blinking is still there, but almost invisible (kinda switching between two very close shades of gray).
Reverting to the non-minified version solves the problem.

**Comment by jcubic** [comment]
It was because yuicompressor replaced 0% keyframe with 0. Fixed in 0.10.12.

**Comment by arkanovicz** [comment]
Nice reactivity!
