### ISSUE TITLE
json-rpc.php

### ISSUE THREAD

**Issue by bjmb** [jcubic/jquery.terminal#245]
Hi,

Thank you for this awsome library.
I believe the file json-rpc.php inside examples(in both the master branch and the devel branch) is not the same on as the one used in http://terminal.jcubic.pl/rpc-demo.html as the one in the respository one doesn't have for example the help function. Any chance of this file being uploaded to the repository?

Thank you.

**Comment by jcubic** [comment]
In devel branch I've implemented help in JavaScript based on results from system.describe.

**Comment by jcubic** [comment]
json-rpc.php on the site is old and it don't have system.describe

**Comment by bjmb** [comment]
Thank you very much for your answer. The help function is implemented. This version is no exactly as the on in the page, as for example the "ls" command doesn't work without arguments but it's more than enough.

Thanks again.
