### ISSUE TITLE
text format confusion

### ISSUE THREAD

**Issue by JelleRoets** [jcubic/jquery.terminal#246]
Wanted: echo the text "[foo] bar" in green to the terminal using ansi-formatting.
Tried: term.echo("\x1b[32m[foo] bar");
=> wrong result: ![image](https://cloud.githubusercontent.com/assets/4798064/16873994/f3074a6a-4a96-11e6-9132-b7a3ebbb7157.png)

**Comment by jcubic** [comment]
It's because it's replaced by `"[[;#008400;][foo] bar]"` (`]` close the formatting) to fix the issue you need to escape the ] using
`term.echo("\x1b[32m[foo\\] bar");`

**Comment by JelleRoets** [comment]
thx for the quick feedback! that solved my issue.
