### ISSUE TITLE
How to give multi-line command ?

### ISSUE THREAD

**Issue by jayendra13** [jcubic/jquery.terminal#248]
I am using this code to display `python` interpreter on html, everything is working fine except the command which requires multiple lines. The things like `for` loop or `if-else` cases requires more than one line to complete command, how to do it with terminal.js ?

```
for x in list:
    print x
```
Current implementation gives error obviously as it sends the `for x in list:`, without waiting for `print x`

**Comment by jcubic** [comment]
You can take a look at my trypython interpreter https://github.com/jcubic/try-python/blob/master/js/main.js#L167

Basicaly you check if command contain `:` at the end if so you save the command in varaible declerated outside of terminal function and in next command you append the command to the previous command, if command is empty and if saved code is not empty you eval the code.

**Comment by jayendra13** [comment]
Thanks I was searching exact the same thing!!
