### ISSUE TITLE
Pager?

### ISSUE THREAD

**Issue by seanhandley** [jcubic/jquery.terminal#251]
It would be nice to have a built in pager (like more/less) so large output can be more easily handled in the terminal.

**Comment by jcubic** [comment]
It's implented as example for use in user code http://terminal.jcubic.pl/examples.php#less. And there is better less in leash browser shell https://github.com/jcubic/leash/blob/master/leash-src.js#L1084

**Comment by jcubic** [comment]
The only time when you can't execute custom less on output is when you're using JSON-RPC but then you can use processRPCResponse to format output from RPC as you want.

**Comment by jcubic** [comment]
Closing because this can be implemented in user code using available API.

**Comment by seanhandley** [comment]
Thanks @jcubic - I'll give it a try.
