### ISSUE TITLE
flush() don't work as expected

### ISSUE THREAD

**Issue by rcracel** [jcubic/jquery.terminal#253]
This may be mostly due to my misunderstanding on how the output buffer works, but I was under the impression that I should be able to do multiple .echo( ..., { flush: false }) and all these entries would be kept in the buffer until the next flush() is invoked.

Instead, I am experiencing that only one line is being output when I invoke flush().

Reason I was using it, is I have some commands I need to support that produce a high volume of output lines and figured it would be more efficient to only flush at the end.

**Comment by jcubic** [comment]
yes it should flush the lines that had flush false, I add tests that fail and try to fix this (I don't have unit tests for flush yet).

**Comment by jcubic** [comment]
fixed in version 0.11.6

**Comment by rcracel** [comment]
Sweet, thank you so much!
