### ISSUE TITLE
Difficult to re-enable terminal with a mouse

### ISSUE THREAD

**Issue by jpatrickpark** [jcubic/jquery.terminal#255]
What I am describing here is not a bug, just inconvenience. 
Once I lose focus of the terminal (by clicking the part of the website that is not part of terminal), I can click where the cursor was (which is invisible because the blinking cursor is gone) in order to regain focus.
However, the area where you can click is really small that **it takes 10 to 20 clicks before finding the right spot** and enable the terminal.
On android there seems to be some OS or browser-level support to help press the right spot, but it is difficult to do so with a mouse.
## Platform

I experienced this on chromeOS 53.0.2785.103 (64-bit) on the terminal demo page.
## Possible Solution

I was wondering if you can make it so that the entire last line (with the prompt) will enable the terminal when clicked.

**Comment by jcubic** [comment]
It should enable terminal when you click on the terminal, unfortunetelly I don't have chromeOS so I can't test to figure out what's going on. I need to check maybe you can install chromeOS in VirtualBox,

**Comment by jcubic** [comment]
It seems that this happen on Linux/Chrome probably on all platforms.

**Comment by jcubic** [comment]
Fixed in version 0.11.10.

**Comment by RomanPerin** [comment]
I have this issue in version 1.5.0.

**Comment by jcubic** [comment]
@RomanPerin  Can you try latest 1.6.4 and devel branch? Do you have the issue with demo or comment section on homepage?

**Comment by jcubic** [comment]
Ok, I've tested and it seems that there is an issue with mousemove on MacOS the event is triggered when bind happen after the actual mouse move, it seems it's bug in Chrome MacOS. I'm investigating.

**Comment by jcubic** [comment]
Fixed in devel branch it can be testing on this pen https://codepen.io/jcubic/pen/KvJMJx

**Comment by RomanPerin** [comment]
Thx for the quick fix! I have tested https://codepen.io/jcubic/pen/KvJMJx and it works fine to me.

**Comment by jcubic** [comment]
released in version 1.7.0
