### ISSUE TITLE
The OutputLimit option

### ISSUE THREAD

**Issue by stanleyxu2005** [jcubic/jquery.terminal#256]
Dear Developer,

I use jquery.terminal as a log viewer. As log messages have quite an amount, it will sooner or later impact browser performance. I think I need only to keep only 200 most recent log messages. S I set `outputLimit` to 200, but it seems to clear the terminal and remove all log messages. 

Is it possible to keep the most N line text or do you have a plan to add this into the development plan?

**Comment by jcubic** [comment]
Do you have a demo somewhere? Maybe you can create [jsFiddle](https://jsfiddle.net/). I need to check if outputLimit is working I don't have it in unit tests.

**Comment by jcubic** [comment]
There was bug in outputLimit maybe it will work for you in version 0.11.9.

**Comment by stanleyxu2005** [comment]
Cool. Thanks for the quick response.
