### ISSUE TITLE
Dont autoscroll when terminal is updating

### ISSUE THREAD

**Issue by stanleyxu2005** [jcubic/jquery.terminal#257]
_(Continue with the previous issue.)_

I use `jquery.terminal` as a log viewer. When I checking the logs, I might scroll up to a position. And meanwhile I have a background service that might continue to put new log into the terminal. When new log is echoed to terminal, the terminal will scroll to bottom. 

This is very annoying, because I have to scroll back where I was. Is it possible to disable scroll when `echo` or `error` is called?

**Comment by jcubic** [comment]
I will add an option.

**Comment by jcubic** [comment]
Option scrollOnEcho added in version 0.11.8.
