### ISSUE TITLE
Broken on Edge

### ISSUE THREAD

**Issue by MalcolmMcLean** [jcubic/jquery.terminal#258]
Worked fine on Edge. Until the latest update to Edge. Now it is broken. JQuery does not link the terminal property in Edge (Chrome still functional).,

**Comment by jcubic** [comment]
In which version of Edge it's broken, I'm using version 25.10586 and demo on home page work fine. Which version of jQuery you're using and do you have a demo somewhere? Maybe you can create [jsFiddle](https://jsfiddle.net/)

**Comment by MalcolmMcLean** [comment]
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
Here's the program that fails. I'm trying to write a game with a console window and a map. Open it in Chrome and it runs, open it in Edge and it generates a "can't attach terminal" message. 

    On Friday, 30 September 2016, 15:03, Jakub Jankiewicz <notifications@github.com> wrote:
 

 In which version of Edge it's broken, I'm using version 25.10586 and demo on home page work fine. Which version of jQuery you're using and do you have a demo somewhere? Maybe you can create jsFiddle—

**Comment by jcubic** [comment]
I've installed latest update and I still have Edge 25 and EdgeHTML 13. How did you get that version, I'm not very familiar with windows.

**Comment by MalcolmMcLean** [comment]
My Windows installation has the default settings, which allow Microsoft to update at will. There was massive update which took about an hour to execute, rebooting the machine several times and making me late for work. Then afterwards the program was broken on Edge, but not on Chrome. Previously it had run on Edge correctly. 

    On Monday, 3 October 2016, 17:39, Jakub Jankiewicz <notifications@github.com> wrote:
 

 I've installed latest update and I still have Edge 25 and EdgeHTML 13. How did you get that version, I'm not very familiar with windows.—

**Comment by jcubic** [comment]
Ok I get the update, and demo on home page is working in latest Edge. Can you send your code again because I didn't get it if you sent it. You can send it to [mailto:jcubic@onet.pl](mailto:jcubic@onet.pl)

**Comment by jcubic** [comment]
It seems that the terminal is working in both IE and Edge on Windows 10 and because there are no response from OP, I'm closing the issue as cannot reproduce.
