### ISSUE TITLE
Disable one or more shortcuts programmatically

### ISSUE THREAD

**Issue by stanleyxu2005** [jcubic/jquery.terminal#259]
I'm using the jquery.terminal as a read-only log view. The default shortcuts are similar to a regular bash shell. When I presss <kbd>CTRL</kbd>+<kbd>R</kbd>, I mean to reload the page. But jquery.terminal will enter reverse search mode. 

It will be great, if we can disable particular shortcuts when initialize the terminal instead of hooking up `keypress` event or something else.

Expected solution will be
```
   var shortcuts = terminal.getShortcuts() // return a dictionary
   delete shortcuts.ctrlR;
   terminal.setShortcuts(shortcuts);
```

**Comment by jcubic** [comment]
CTRL+R is handled by keydown event in cmd plugin to overwrite it you can use keydown option:

```javascript
$('...').terminal(interpreter, {
    keydown: function(e, term) {
        if (e.which == 82 && e.ctrlKey) {
            return true;
        }
   }
});
```
if you return true the default action will be executed (in case of CTRL+R refresh) and if you return false it will not.

**Comment by jcubic** [comment]
to see what which to use you can use demo at the bottom of http://api.jquery.com/keydown/ and http://api.jquery.com/keypress/

**Comment by jcubic** [comment]
Sorry didn't notice that you don't want to use keypress

**Comment by stanleyxu2005** [comment]
Yes. I can use `keypress` as workaround. But I'd be appreciated, if you agree to change that from jquery.terminal side.

**Comment by jcubic** [comment]
It will be hard to change shortcuts to object with current architecture.

**Comment by stanleyxu2005** [comment]
Okay. Never mind.

**Comment by jcubic** [comment]
In devel branch I've added keymap to cmd terminal and interpreter to delete shortcut you can use this code:
```javascript
        onInit: function() {
            var cmd = this.cmd();
            var keymap = cmd.keymap();
            delete keymap['CTRL+R'];
        }
```

**Comment by jcubic** [comment]
But this will make CTRL+R refresh the page because default action will not be prevented.

**Comment by stanleyxu2005** [comment]
Can you allow `cmd.keymap()` passed into the constructor, so that exact those specified keys will response?

**Comment by jcubic** [comment]
yes, there is option keymap for terminal and cmd and push, so you can use:
```javascript
$('...').terminal{}, {
  keymap: {
    "CTRL+R": function() { return false; }
  }
});
```
the same with cmd plugin and push.
