### ISSUE TITLE
Propose to remove versioned files

### ISSUE THREAD

**Issue by stanleyxu2005** [jcubic/jquery.terminal#260]
I notice there is two copies of latest version in dist directory. One without version number and the other has. I think this is not a good practice, as other popular projects do not follow this pattern. 

I will usually 
- create a vendor directory and then 
- run `npm install foo` manually (out of the vendor directory) and then
- create a new sub directory with its version number and then
- copy the minified version (or maybe also the unzipped version) there
- in HTML code, I will manually upgrade the version number.

Hope this can change your mind to remove the extra copy from dist directory.

**Comment by jcubic** [comment]
in version 0.11.16 there will be no versioned files in npm

**Comment by jcubic** [comment]
0.11.16 had versioned file as main file fixed in 0.11.17.
