### ISSUE TITLE
The terminal got focus by double-click while is frozen !

### ISSUE THREAD

**Issue by sebastienwarin** [jcubic/jquery.terminal#262]
Hello,

I found an issue by upgrading this library in my solution. This issue is coming with the version 0.10.0 : even if you freeze the terminal you can get a focus (and intercep all keys from the keybord) by double-click on the prompt.

To reproduce the bug, add this option in "multiply-interpreters-demo.html" from your examples :
`onInit: function (term) {
   term.freeze(true);
}`

With the version 0.9.3, the terminal is disable (read-only mode) so even if you double-click on the prompt, you can't have the focus !
But the same example in the version 0.10 of this library, don't work : I get the focus while the terminal is frozen !

Best,

**Comment by sebastienwarin** [comment]
Hi,

In fact, it's not a regression in 0.10.x or greater, I don't read the comment on the freeze method : "Disable/Enable terminal that can be enabled by click" !
But before the 0.10 (0.9.3 for example), if you freeze the terminal you can't re-enable it !

In my case, I would like to have this behavior, a "read only" terminal to show log message in real-time. So I have add a "readOnly" option to do this.

I send you a pull request if you want to integrate or update my code to support this feature.

Thank you for your work, this is a great plugin!

**Comment by jcubic** [comment]
when terminal is frozen it should be no enabled on click it. Thwere should be "can't" in docs because when you disable terminal you can enable it on click that's why I added freeze. if it don't work it's probably because I added mousedown/mouseup instead of click.

**Comment by sebastienwarin** [comment]
Ok I don't understand this by reading the comment of the freeze method ! I think that you can re-enable the terminal on click even if it's frozen !
So I will update my PR to remove the readOnly option and use the frozen variable instead !
