### ISSUE TITLE
term.echo add newline to message. Can I disable it?

### ISSUE THREAD

**Issue by goflatworld** [jcubic/jquery.terminal#265]
I want to use this plugin in my project. During test I notice one issue in my situation --- term.echo add newline (or enter/CRLF) to each message displayed on the terminal. It messed up my display.

My application get messages from server. The message is ONE character at a time.  e.g. If the message is "test". My first message is t and secondary message is e...  

When I use term.echo, I expected it to display my message as "test". but it actually display it as 
t
e
s
t
My understanding is the term.echo automatically add CRLF to each message. If this is the case, can I tell term.echo do not add CRLF?

**Comment by jcubic** [comment]
No it's not possible, term.echo always add new line at the end and it would be hard or even impossible to make it not to add new line with current architecture.
But you can try to use term.update(-1, string) to update last line, I can make it accept function as second argument so you will be able to use:
```javascript
term.update(-1, function(string) {
   return string + message;
});
```
in the current version you will need to save the previous message in variable:
```javascript
var line = '';
...
line += message
term.update(-1, line);
```

**Comment by goflatworld** [comment]
Thanks for the reply, I have below function now. It still has a new line after every char. Can you please let me know what am I doing wrong?
............................................................

 function onMessage(evt)
    {
        var message = evt.data;
        if (message.startsWith("B"))
        {
            message = message.slice("B".length);
            log.innerHTML =  log.innerHTML+ message;
	    var line ='';
            line +=message;
	    term.update(-1, line);
	    term.echo(line);
        }
}

.............................................

**Comment by jcubic** [comment]
you shoulld call echo on first message and update on next messsages, try something like this 
```javascript
var line = '';
function onMessage(evt) {
    var message = evt.data;
    if (message.startsWith("B")) {
        message = message.slice("B".length);
        log.innerHTML = log.innerHTML+ message;
        line += message;
       line = line.replace(/\n$/, ''); // don't echo new line at the end
        if (line === message) {
            term.echo(line);
        } else {
           term.update(-1, line);
        }
        if (message.match(/\n$/)) {
            line = '';
        }
    }
}
```

**Comment by goflatworld** [comment]
Great thanks. that worked!

I want to use the plugin as pure VT100 emulator. Do you have a doc on how to use this lib? The examples are jason, mysql related. I didn't  find out VT100 examples.

I'm also looking into terminal.js to see if I can use it as a simple simulator.

**Comment by goflatworld** [comment]
Actually, what I hope to do is like a telnet client. Basically it will:

1. Connect to the server --- I have done it
2. Send character to the server  (disable local echo since the server will echo back everything I typed). I used onkeyup event to do it via input box, can I do it with your lib?
3. Display the return. --- You have helped me on this one.
4. Put the cursor right after the return, no its own prompt. ---- Can I do it via this lib?

**Comment by jcubic** [comment]
If you want real telnet client you can take a look at [xterm.js](https://github.com/sourcelair/xterm.js)

**Comment by goflatworld** [comment]
Thanks a lot.

**Comment by jcubic** [comment]
it was asked multiple times, from version 2.8.0 there is file that add newline option for echo. See #511
