### ISSUE TITLE
Dismiss warning if response content type is text/json

### ISSUE THREAD

**Issue by stanleyxu2005** [jcubic/jquery.terminal#267]
I saw an warning 'Response Content-Type is not application/json'. One of my server application will return "text/json" instead of "application/text". I don't know whether it will be invalid if the terminal accepts both content types?

**Comment by jcubic** [comment]
It's just the warning, I can remove it. It doesn't chnge anything.

**Comment by stanleyxu2005** [comment]
Thanks
```
if(!a.match(/(application|text)\/json/)){
var s="Response Content-Type is neither \"application/json\" nor \"text/json\"";
```

**Comment by jcubic** [comment]
Added text/json will be in version 0.11.16 that will be released soon.
