### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by git-wizard** [jcubic/jquery.terminal#269]
Hi, i do not know if i can put this here however i am having trouble understanding how to use this.

I have tried everything, it works but i cannot type anything when i have it on my website. Could someone please tell me EXACTLY how to use this plugin, i find it to be incredible i really like it however cannot get it to work.

Any help will be greatly appreciated.

**Comment by jcubic** [comment]
Can you share your code, maybe create [jsfiddle](https://jsfiddle.net/)

**Comment by git-wizard** [comment]
Keep in mind that i am rather new to web design however i find it really enjoyable.

The javascript i just copied as i had no idea about what to do. I know very basic js. 

https://jsfiddle.net/3ghx7o6s/

I understand how it works roughly.

**Comment by jcubic** [comment]
You try to execute 2 examples (two $(..).terminal() and two documen ready $(function(){...})) on single body element and you missed jquery. 

Look at this : 
https://jsfiddle.net/3ghx7o6s/1/

**Comment by pot-wizard** [comment]
I still do not understand, im sorry. This is very confusing for me.

**Comment by pot-wizard** [comment]
This is another account i have by the way.

**Comment by jcubic** [comment]
* You need to include jquery you added jquery as local file which is no there on jsfiddle, I've included the one from jquery cdn if you have that file locally include it before jQuery Terminal (in your html).
* don't use this html 
```html
<div id="terminal" class="terminal">
    <div class="header">Terminal Emulator: </div>
    <div class="terminal-output"></div>
</div>

<div id="command-line" class="cmd" style="width: 100%;">
    <span class="prompt">&gt;</span>
    <span></span>
    <span class="cursor blink">&nbsp;</span>
    <span></span>
    <textarea class="clipboard"></textarea>
</div>
```
that html is added dynamicaly by the terminal
* aslo you have this code:
```javascript
jQuery(function($) {
    $('#terminal').terminal("rpc_demo.php", {
        login: true,
        greetings: "You are authenticated"});


    jQuery(function($) {
        function progress(percent, width) {
        $('body').terminal(function(command, term) {
        }, {...});
    });
});
```
two `jQuery(function($) {` one inside other one. that code is executed when DOM is ready you don't need to use two of them. Also you're executing two times terminal plugin the second execution will be ignored.

PS: why you have two github accounts?

**Comment by jcubic** [comment]
You want to add terminal to `<div id="terminal">` just use:
```html
<div id="terminal"></div>
```

**Comment by pot-wizard** [comment]
Thank you so much :D
