### ISSUE TITLE
Using both JSON-RPC auth and interpreter commands

### ISSUE THREAD

**Issue by sjmh** [jcubic/jquery.terminal#270]
I've gotten the JSON-RPC auth working and I can create json rpc methods which I can call and that all works.

What I'd like to do though, is require the user to login via the JSON-RPC auth, but I'd also like to have some commands to be handled by jquery.terminal after they've logged in, rather than passing them to the JSON-RPC api.

Is there a way to do that?

**Comment by jcubic** [comment]
You can use array as first argument like this:
```
    $('...').terminal(["json-rpc-service-demo.php", function(command, term) {
			if (command == 'test') {
				term.echo('testing');
			}
		}], {
            login: true
      });
```
but I think it will not work if the JSON-RPC service will not have system.describe, the json-rpc.php implementation that's in examples have it.

**Comment by jcubic** [comment]
But this will execute commands from json rpc and methods from other interpreters if you only want to use login then you need to implement login as a function like this:

```javascript
$('...').terminal(function(command, term) {
}, {
    login: function(user, pass, callback) {
        $.jrpc('json-rpc-service-demo.php', 'login', [user, pass], function(data) {
            callback(data.result);
        }, function() {
            callback(null);
        })
    }
});
```
