### ISSUE TITLE
[Feature Request] Only scroll on echo when at the bottom

### ISSUE THREAD

**Issue by schrej** [jcubic/jquery.terminal#271]
We are using this plugin for a game server management panel to display the console of the service that is running. It's working nice so far.

One thing we are missing is the ability to disable automatic scrolling on echo when the terminal is not scrolled all the way (or very close) to the bottom. This would make it possible to scroll up and read older portions of the output without jumping down whenever there is new output (which happens rather often on an active server).
Additionally, a callback on new output when the terminal does not scroll would be nice to show a notice to the user that there is new output available.

We would also be happy with a workaround if there is one, I hadn't time to look in the code and one who knows it is probably able to answer that quite quickly.

**Comment by jcubic** [comment]
There is an option to disable scroll on echo - scrollOnEcho{

As for notification can you just do the notification yourself when you echo something? You can for instance add class .notify and remove it in setTimeout:
```javascript
$('.terminal').addClass('notify');
```
and add css:
```css
.terminal {
  transition: all 1s linear;
  border: 1px solid transparent;
}
.terminal.notify {
  border-color: red;
}
```
or use jquery animation.

**Comment by schrej** [comment]
Sorry, i can't test right now..

If I set scrollOnEcho to falls and am scrolled all the way down, will new output be visible or would I have to scroll down to see it? Because that's what I want: As long as I am scrolled all the way down I want to stay scrolled down so new output after entering a command is visible.

Also for the notifications it would be necessary to  detect if the console is scrolled down so it's only shown if there is new output that is not currently visible.

**Comment by jcubic** [comment]
if scrollOnEcho is set to false it don't scroll at all, when echo is executed, maybe I can add a check to call scroll to bottom also when page is at the bottom even when scrollOnEcho is set to false.

As for notifications you can check if page is at the bottom using this answer from SO: [How can I determine if a div is scrolled to the bottom?](http://stackoverflow.com/questions/876115/how-can-i-determine-if-a-div-is-scrolled-to-the-bottom) but if you're adding terminal to body element you will need to use this [Check if a user has scrolled to the bottom](http://stackoverflow.com/questions/3898130/check-if-a-user-has-scrolled-to-the-bottom)

Maybe I can came up with an API to test that you're at the bottom, maybe `term.bottom();` or `term.is_bottom();`

**Comment by jcubic** [comment]
the `term.bottom()` can scroll to the bottom. so you will be able to use this code:
```javascript
var bottom = term.is_bottom();
term.echo('something');
if (bottom) {
    term.bottom();
}
```
that way I will not need to add extra check for cases when page is at the bottom. Need to think about it.

**Comment by jcubic** [comment]
In version 0.11.22 when you set scrollOnEcho to false it will scroll when at the bottom of the page before echo. And also there are two methods `is_bottom()` and `scroll_to_bottom()` so you can create code like this:
```javascript
term.echo('Something');
if (!term.is_bottom()) {
    // notify the user for instance
    term.addClass('notify');
}
```

**Comment by schrej** [comment]
Thank you so much, this is working great!

**Comment by schrej** [comment]
During some further testing, the scroll at the bottom didn't always work, I don't know what exactly the issue is.

My idea would be to just add a few pixels to the is_bottom() detection to avoid rounding and beeing only 99.9% at the bottom issues.

**Comment by jcubic** [comment]
I've added an option scrollBottomOffset with default set to 20. Can you test file from the repo?

**Comment by schrej** [comment]
Now it's working perfectly, thank you!
