### ISSUE TITLE
Jquery terminal advanced usage

### ISSUE THREAD

**Issue by AZm1n** [jcubic/jquery.terminal#275]
Hello and a happy new year everyone.

I've been playing around with 'Jquery Terminal' for couple of weeks and i'm really impressed with it's functionality compared to similar tool. Thank you for sharing that!

Now i want to take this another step further and start putting it in production and have some users to test.

My usage scenario is currently a Json RPC interpreter, I enter a command and then send it to an ASP.NET API for processing the command and returning the results, everything works perfectly fine but i have the some questions and appreciate a helping hand here.

1- Is it possible to have an interactive terminal through the jsonRPC library?
For example a user enter 'Create Disk', The Command go to the API to process and then the API wiIl require more inputs from the user, say 'name', 'location' and 'size', how do I capture these inputs in an such an interactive way? i'm fine with wither client/server side idea.

I know that i can pass all argument with the post data, tested it and worked fine, but some commands will require interactivity to make the experience more pleasant, how to achieve this in an elegant way?

2- How to customize color returned if the result returned is a json object?
For example, i can return a string from the API and i can append the desired color on any part of the string from the API and the terminal render it correctly.
Now if I return an object or array of object, how to do do color or other formatting properly?

3-For the Tab auto completion feature, is this feature only applicable to the PHP code shared on the page or can be used somehow with a .Net API?
My thinking was to download the commands via an RPC call and handle the Tab key manually, any other elegant suggestion is welcome.

I'm a very good .Net developer but still navigating my way through the realm of Java script,  things going good but it's totally different realm than .Net, I really do appreciate examples and js code samples if possible demonstrating any idea.

Thanks.

**Comment by jcubic** [comment]
To customize colors for objects or array you can use costom processRPCResponse callback where you can echo the response.

To have completion with JSON-RPC you can add method system.describe that will return list of methods and number of parameters or you can use code like this:
```javascript:
$.jrpc('service-url', 'get_methods', [], function(data) {
    $('body').terminal("service-url", {
        completion: data.result
    });
});
```

as for first question with interactive command you can turn of arity with `checkArity: false` and in command if there are no arguments you return extended command (a way to execute different command from the server) `term.echo('[[ interactive command Name Description Age ]]');` and then you implement the interactive command (you put interactive command in object as first element of the array and your rpc string as second argument)

here is [demo that use function instead of rpc](http://codepen.io/jcubic/pen/WRNPxj?editors=0010)

**Comment by AZm1n** [comment]
Thank you!
let me do some testing today and post back.
Thanks again.

**Comment by AZm1n** [comment]
OK, this bring me very close to what i need, let me recap what i understand and ask a followup question
***term.echo('[[ interactive foo Name Name2 Description Description2 ]]');
In this example you are passing the label interactive to the term.echo, interactive is a label for the loop function that accept the string 'name', you then slice the arguments to strip out the command and push a new terminal with everyone.

then you pass the object created to the 'foo' function which basically can be the rpc interpreter. 
very neat!!! (y)

I really like in this approach that this loop act as an anonymous function where i can call it with different parameters and it will just do the job.

How do i make this scale though? what is the best pattern to use.

I want one function call to both this anonymous loop function and the processrpcresponse so that i be able to call it from any terminal, i'm trying to make the code resuable as much as i can.

Thanks.

**Comment by jcubic** [comment]
I don't know if I understand what you mean. In rpc service in .NET you create two functions (using function overloading) one function process arguments and function without arguments just `return "[[ interactive name <LIST OF ARGS> ]]";` then you can add this in JS:

```
$('...').terminal([{
    interactive: function(name) {
        var term = this;
        var args = [].slice.call(arguments, 1);
        var result = [];
        var index = 0;
        (function loop() {
            if (args[index]) {
                term.push(function(command) {
                    result.push(command);
                    index++;
                    term.pop();
                    loop();
                }, {
                    prompt: args[index] + ': '
                });
            } else {
                // you can also use result.join(' '); so you get arguments in rpc method
                // or if strings can have spaces result.map(function(string) { return JSON.strinigify(string); }).join(' ');
                term.exec(name + ' ' + JSON.stringify(result), true);
            }
        })();
    }
}, "rpc-server"], {
  checkArity: false,
  processRPCResponse: function(data, term) {
    if (typeof data == 'string') {
       // this will also echo `[[ interactive ]]` exec command because it will be normal string
       this.echo(data);
    } else if (data instanceof Array) {
      // process array
    } else if (typeof data == 'object' && data) {
      // process objects
    }
  }
});
```

if user type `command Name Description` it will execute method with arguments (if you have class as rpc service) and if user type `command` it will execute method without arguments that will return '[[ interactive command <ARGS> ]]` that will in turn execute interactive command that will then execute method with arguments `command Name Description` the same as if user type it.

**Comment by jcubic** [comment]
I've notice one thing extended commands was showing up when you resize the page or terminal (when resize method is called). I've fixed that in devel branch.

**Comment by AZm1n** [comment]
Interesting approach
Thank you i'll give that a try today and post my test results.

**Comment by AZm1n** [comment]
This is exactly, exactly what I want to achieve.
I want to be able to dynamically construct sub commands based on the response and post them back to the API when user hit enter.

When the page refreshes, I can see it hit my API with the 'system.describe' method and this is the right behavior on startup with rpc interpreter I believe.

When I type any command it didn't go to the API though and the terminal displays 'Command xxxxx Not Found', I want every command to be sent to the API and construct back either a new command or display result, the code you share is the right one, but how to direct every command to the API though?

Here is code i'm using, it's pretty much the same like what you shared + the API test server, This code is wrapped into a spinner function to start/stop animation.

Thank you!

        $('#term').terminal([{
            interactive: function (name) {
                var term = this;
                var args = [].slice.call(arguments, 1);
                var result = [];
                var index = 0;
                (function loop() {
                    if (args[index]) {
                        term.push(function (command) {
                            result.push(command);
                            index++;
                            term.pop();
                            loop();
                        }, {
                            prompt: args[index] + ': '
                        });
                    } else {
                        term.exec(name + ' ' + result.map(function (string) {
                            return JSON.stringify(string);
                        }).join(' '), true);
                    }
                })();
            }
        }, "https://localhost:44330/api/Migrate/PostCommand"], {
            checkArity: false,
            greetings: 'Hello! type [[b;#fff;]help] to get started.',
            prompt: "> ",
            processRPCResponse: function (data, term) {
                if (typeof data == 'string') {
                    // this will also echo `[[ interactive ]]` exec command because it will be normal string
                    this.echo(data);
                } else if (data instanceof Array) {
                    // handle only 1 dim arrays
                    term.echo(data.join(' '));
                } else if (typeof data === 'object') {
                    var string = '';
                    for (var f in data) {
                        if (data.hasOwnProperty(f)) {
                            string += f + ': ' + data[f] + '\n';
                        }
                    }
                    term.echo(string);
                }
            }
        });

**Comment by jcubic** [comment]
It's a bug if system.describe return error it don't work the same as if you use option `ignoreSystemDescribe: true` if you use that option it will not call system.describe and it will work.

**Comment by jcubic** [comment]
fixed the issue in devel branch.

**Comment by AZm1n** [comment]
Thank you, that made it works, all commands are now passed to the server but the 'processRPCResponse' is not capturing the returned data, I tried returning a json object or a string but the 'data' is showing as undefined in the call back when I check the developer tool in chrome.

Thanks.

**Comment by jcubic** [comment]
Are you sure you're returning string, Array or Object and not number? Because your `processRPCResponse` callback don't check for numbers. How your response callback look like do you modify the `response.result` data? Do you have a demo when I can test your code?

**Comment by AZm1n** [comment]
I don't do any modification to the code above, I checked the Network Tab in Chrome and saw the response body contains either a json object or a string depending on what i return from the API, so i'm pretty sure the response is sent from the server and not a number.

from the API i'm returning this

return Ok("This is my string");
//Or
return Ok(MyJsonObject);

https://msdn.microsoft.com/en-us/library/dn314591(v=vs.118).aspx

**Comment by AZm1n** [comment]
This is also used to work fine with my previous test when i was using "$jrpc" before.

**Comment by jcubic** [comment]
Are you sure the response from server is JSON-RPC like:
```json
{"jsonrpc":"2.0","result":"foo","id":3,"error":null}
```
You can see it working [here](http://terminal.jcubic.pl/test.php) the server side code look like this (in php):
```php
    require('json-rpc.php');
    define('CSRF_HEADER', 'X-CSRF');
    class Test {
        function add($a=null, $b=null) {
            if (!$a && !$b) {
                return "[[interactive add A B]]";
            } else {
                return $a + $b;
            }
        }
        function show($name=null, $description=null) {
            if (!$name && !$description) {
                return "[[interactive show NAME DESCRIPTION]]";
            } else {
                return "NAME: $name, DESCRIPTION: $description";
            }
        }
    }

    handle_json_rpc(new Test(), CSRF_HEADER);
```

**Comment by AZm1n** [comment]
No, actually i'm not wrapping the results into the expected json-rpc format result.
I used the same pattern i used for the $jrpc, which was able to handle the results without wrapping them into the Json-RPC object. the call backs to process the results was running fine.

What i will do then is i'm going to introduce a new class with the expected json-rpc return object.
I will then add my returned string/ object into the jsonrpcobject.result and return the whole json-rpc object back to the terminal.

I hope this is the right way of doing it :)

**Comment by AZm1n** [comment]
I created two classes for the request and response on the API as per json-rpc2 specification and parsing automagically worked on the client side.

Thank you Jacub for your patience and help. I think I have everything i need right now and many actions on my side to complete the parsing logic at the API.

Thanks 🥇
