### ISSUE TITLE
add support for CSRF protection

### ISSUE THREAD

**Issue by AZm1n** [jcubic/jquery.terminal#276]
Since all the request sent using the json-rpc library, is it possible to add support for CSRF protection?
Typically, the terminal should expose a default variable where one can specify the name and the cookie string.

this post should have some details
http://stackoverflow.com/questions/22063612/adding-csrftoken-to-ajax-request

adding support for csrf protection is essential IMHO to run securely in production.

Thanks.

**Comment by AZm1n** [comment]
I also have a .Net code ready that can handle CSRF tokens coming from ajax requests, i'll be more than happy to test it after implanting it.

**Comment by jcubic** [comment]
In devel branch I create two callbacks request and response that can modify request and response, I've tested with [JSON-RPC in php](https://github.com/jcubic/json-rpc/commits/master)

```javascript
         var csrfToken;
         $('<div/>').appendTo('body').terminal("test.php", {
             request: function(jxhr, term, request) {
                 if (csrfToken) {
                     request.params.unshift(csrfToken);
                 }
             },
             response: function(jxhr, term, response) {
                 if (!response.error) {
                     csrfToken = response.csrf ? response.csrf : response.result.shift();
                 }
             }
         });
```
basicly system.describe return CSRF token in csrf fileld and all other requests return array with first item be token and the second be result from method.

if you want to have http header based CSRF you can do something like this:

```javascript
         var csrfToken;
         $('<div/>').appendTo('body').terminal("test.php", {
             request: function(jxhr, term, request) {
                 if (csrfToken) {
                     request.params.unshift(csrfToken);
                 }
             },
             response: function(jxhr, term, response) {
                 if (!response.error) {
                     csrfToken = response.csrf ? response.csrf : response.result.shift();
                 }
             }
         });
```

if you prefer HTTP header based CSRF you can use code like this:

```javascript
         var header = 'X-CSRF';
         var csrfToken;
         $('<div/>').appendTo('body').terminal("test.php", {
             request: function(jxhr, term, request) {
                 if (csrfToken) {
                     jxhr.setRequestHeader(header, csrfToken);
                 }
             },
             response: function(jxhr, term, response) {
                 if (!response.error) {
                     csrfToken = jxhr.getResponseHeader(header);
                 }
             },
             width: 600,
             height: 480
         });
```

**Comment by AZm1n** [comment]
Tested it and working like a charm.
Thank you.

**Comment by jcubic** [comment]
I've changed the order of arguments now it's:
```
function(jxhr, request, term)
```
and
```
function(jxhr, response, term)
```

because I'm adding `this` to all callbacks and removing term as argument from documentation (all callbacks will work the same except those two).
