### ISSUE TITLE
Terminal pause behavior on json-rpc ajax requests.

### ISSUE THREAD

**Issue by AZm1n** [jcubic/jquery.terminal#277]
On issue 276, it introduced  new request,response callbacks for the json-rpc interpreter which is great to do any actions pre/post the request..

Now when I try to start the animation on the request callback, the animation is not getting started because the jsonrpc interpreter disables the prompt when pausing the terminal.
.
Ln:2781
```javascript
        // ---------------------------------------------------------------------
        // :: Create interpreter function from url string
        // ---------------------------------------------------------------------
        function make_basic_json_rpc(url, auth) {
            var interpreter = function (method, params) {
                self.pause();
```
I understand it is expected to pause the terminal on Ajax request, but can you also expose a flag to set the prompt to enabled if one to use animation?
or do you think there is a better approach to start/stop animation on ajax requests with the current behavior?

Thanks.

**Comment by jcubic** [comment]
I've added option softPause (in devel branch) if you set to true it will not hide the prompt, the code now look like this:
```javascript
        // ---------------------------------------------------------------------
        // :: Create interpreter function from url string
        // ---------------------------------------------------------------------
        function make_basic_json_rpc(url, auth) {
            var interpreter = function (method, params) {
                self.pause(settings.softPause);
```

**Comment by AZm1n** [comment]
Thank you.
Tested it and working as expected.
