### ISSUE TITLE
displaying images inside the terminal

### ISSUE THREAD

**Issue by AZm1n** [jcubic/jquery.terminal#278]
is it possible for the terminal to display picture?
I noticed that the terminal works by appending new Span to the Div, is it possible for the 'echo' command to parse and display an image link?

alternatively, if the terminal exposes an append function, and then we define the parsing logic in post processing.

The image container will definitely need to be formatted to fit the terminal

to be fair, this is definitely not a must have, but at the same time will be a very cool to have, You can definitely asses the feature/dev cost efforts and decide accordingly :)

Thanks.

**Comment by jcubic** [comment]
You can add image or any other html using raw option:
```javascript
this.echo('<img src="http://lorempixel.com/output/cats-q-c-987-650-8.jpg"/>', {raw: true});
```
and put this css rule:
```
.terminal img {
    max-width: 100%;
}
```
then the image will not be larger then the terminal.

**Comment by AZm1n** [comment]
Worked like a charm Thanks,
one more related questions, what is the best practices if I'm returning the a list of strings and image links?
For example if i'm returning ObjectA that has two attributes, one is a name and second is an image link.

I'm able to parse my object and then send the 'Name' to term.echo in one call and then display it's picture in another call to 'term.echo()', it's working very well but  I just want to make sure that this is right approach.

in contrast for displaying pure texts from the objects,  I build and format one string in the parsing logic and use just one call  to term.echo() to display my result , and the terminal displays it properly.

so Can I mix both 'text' and 'HTML attributes' in one call to term.echo() or parsing and sending them to the echo one by one is the right approach in this case.

Thanks.

**Comment by jcubic** [comment]
The only caveat is that when you echo raw html you don't get proper wrapping using JavaScript (you will need to relay on css based long line wrapping and you will need to put `<br/>` instead of `\n` or wrap your text in `<p>`) if you don't care you can use one echo with raw option if you notice that there are issues with long line wrapping you can switch to two echo, one with text and one with picture.

**Comment by AZm1n** [comment]
Perfect, Thank you!
