### ISSUE TITLE
can't use the mouse to select text in IE11

### ISSUE THREAD

**Issue by ftaffelt** [jcubic/jquery.terminal#281]
In the current version i can't use the mouse to select text in the terminal. This only occurs in IE. Other browser working fine.

**Comment by jcubic** [comment]
can you test version in devel branch, I think it's fixed there.

**Comment by ftaffelt** [comment]
devel looks good. thanks.

**Comment by jcubic** [comment]
The problem again was in JS that prevent selection to work, it's fixed in master branch will be in version 1.0.2. Can you test if it work for you?

**Comment by ftaffelt** [comment]
master branch works for me. thanks.
