### ISSUE TITLE
Firefox Can't copy paste inside the same terminal

### ISSUE THREAD

**Issue by ftaffelt** [jcubic/jquery.terminal#283]
### Actual behavior
Copy pasting content inside the same terminal seems to be broken.

### Steps to reproduce
In Firefox. Type something into a terminal. Select some text with mouse and press Ctrl+C to copy text into clipboard. Press Ctrl+V to insert content from clipboard into terminal. No text is inserted.

**Comment by jcubic** [comment]
Can you test the file from master branch, to confirm that's fixed for you?

**Comment by ftaffelt** [comment]
it's working now in firefox. 

#281 seems to be back - sorry to say that.

Noticed also on IE11:  pressing the spacebar key echos the term "Spacebar" in the terminal. Should i fill a separate issue for this?

**Comment by jcubic** [comment]
you can create another issue.

**Comment by NoahCardoza** [comment]
This might still be an issue in Chrome. https://github.com/nickola/web-console/issues/46

**Comment by jcubic** [comment]
@NoahCardoza if you look at the jquery terminal submodule it's version is 0.11.12. and current is 1.19.1 and now I'm working on 1.20.0.

Can you clone the repo with --recursive open terminal submodule directory in src/vendor and run git pull, after this copy/paste should work. for this to be permament the owner need to run pull nad commit the updated submodule in original repo.

**Comment by jcubic** [comment]
It was fixed in [version 1.0.2](https://github.com/jcubic/jquery.terminal/blob/master/CHANGELOG.md#102)
