### ISSUE TITLE
altgr+key on keyboards without

### ISSUE THREAD

**Issue by jarv** [jcubic/jquery.terminal#288]
After upgrading to version 1.0.5 on cmdchallenge.com multiple people are reporting that altgr+key is not working on non-us layouts. Can you think of any changes in this version that would cause this issue?

**Comment by jcubic** [comment]
fixed in 1.0.6

**Comment by Lilja** [comment]
I am here from the cmdchallenge and I don't think this fix fixes it, at least for my pok3r RGB with nordic layout.

[You posted a codepen in jarv/cmdchallenge#118](https://github.com/jarv/cmdchallenge/issues/118) and [i modified it](https://codepen.io/anon/pen/xLWEKv). 

I can't press <alt+gr>+<+> which produces a \ . 

```
Keydown Keycode 17 AltKey false CtrlKey true key Control
Keydown Keycode 18 AltKey true CtrlKey true key AltGraph
Keydown Keycode 187 AltKey true CtrlKey true key \
Keypress Keycode 92 AltKey true CtrlKey true key \
```

**Comment by jcubic** [comment]
@Lilja what browser OS you see this? Also what exactly is your  keyboard setup? so I can recreate it?

**Comment by Lilja** [comment]
Win 7/chrome 60.0. 3112.90

Swedish keyboard layout

**Comment by jcubic** [comment]
Ok it now work, you can test. This regresion was for all layouts that use alt to enter keys with altGr.

**Comment by jarv** [comment]
@jcubic wow that was fast, I will update the site soon with this new version. thanks!

**Comment by Lilja** [comment]
Works!
