### ISSUE TITLE
current maybe is null.That cause abnormal.

### ISSUE THREAD

**Issue by zixi0007** [jcubic/jquery.terminal#292]
### Expected behavior
There is risk of array bounds,current maybe is null.That cause abnormal.
src code line 1522
if (pos === current.length) {
                                    pos = 0;
                                    current = array[++line_index];
                                }
 draw_cursor_line(current, pos);
### Actual behavior

if (pos === current.length) {
                                        pos = 0;
                                        current = array[++line_index];
					**if(!current){current="";}**
                                    }
 draw_cursor_line(current, pos);
### Steps to reproduce

You can create demo by forking this codepen http://codepen.io/jcubic/pen/MbVMwO

**Comment by jcubic** [comment]
Do you know the case when this out of bound will happen? What do I need to do as a user to have current equal to undefined?

**Comment by jcubic** [comment]
I can add:
```
if (!current) {
     throw new Error('Internal error, wrong position in cmd redraw');
}
```

so if this happen (and I don't think it will) users will report the exception.

I don't think it will happen because that case `current = array[++line_index];` is only executed when current line is in the middle of the lines so there will always be next line.

**Comment by jcubic** [comment]
Added exeption in version 1.0.9
