### ISSUE TITLE
Issue with typing

### ISSUE THREAD

**Issue by kokokokokokoko** [jcubic/jquery.terminal#293]
Navigating to the center of some text only types first letter then cursor moves to end of text.

### Steps to reproduce
(1) Type: alert('')
(2) Use back arrow key to type "hello" between the ''.

* Tested in the latest firefox/chrome on OSX

**Comment by sharkdp** [comment]
I can confirm this. Chrome 56.0.2924.87/Linux

**Comment by jcubic** [comment]
The problem was with dead keys logic, the terminal was thinking that special keys like arrows (that don't trigger keypress) are dead keys. Can you test this [codepen](http://codepen.io/jcubic/pen/MbVMwO) if it work for you too?

**Comment by sharkdp** [comment]
Yes, it works again. Thanks!!

**Comment by jcubic** [comment]
Released in 1.0.9 version.
