### ISSUE TITLE
terminal doesn't keep cursor position if "delete" key is pressed

### ISSUE THREAD

**Issue by rht1369** [jcubic/jquery.terminal#294]
### Expected behavior

Deleting a character using delete key should not move the cursor to the end of the line.

### Actual behavior

If you delete a character using delete key, and start typing again, the cursor will jump to the end of the line

I believe it's related to #293

**Comment by jcubic** [comment]
Fixed in 1.0.11, it was similar to #293, the input event code was executed for non-character keys.
