### ISSUE TITLE
Input not working in version 1.0.11 on Chrome/Android

### ISSUE THREAD

**Issue by sharkdp** [jcubic/jquery.terminal#295]
Version 1.0.10 works on Android, but the newest version 1.0.11 does not. Nothing get's displayed in the terminal when I type.

BTW: Thanks for this amazing piece of software!

**Comment by jcubic** [comment]
It seems that on chrome android the key property is supported but it's  `unidentified` (not to confuse with undefined) for single characters keys.

Fixed in master branch.

If you're testing can you take a look at issue #235 if you can delete first character in chrome and if arrows work, it seems to work for me (didn't test the arrows)

**Comment by sharkdp** [comment]
Thanks for the quick response!

I have tested the current master on Chrome/Android:
- Input: works
- Arrow keys: work
- Backspace (starting at the end of the input): works
- Backspace (deleting the first character): works
- Backspace (somewhere in the middle of the input): works, but cursor jumps back to end of input
- #235 seems to be fixed, I can not reproduce it.

I have also tested on Chrome/Linux where everything seems to work just fine.

**Comment by jcubic** [comment]
I have default keyboard and chrome 56 and I don't have arrows, what keyboard do you use?

**Comment by sharkdp** [comment]
[SwiftKey](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey) has an option to enable arrow keys.

**Comment by jcubic** [comment]
Ok, I've installed hacker keyboard and make it work with entering text int the middle (the issue was not only with backspace but any key).

Can you retest?

**Comment by sharkdp** [comment]
Inserting text in the middle seems to work, however backspace does not work as expected. It deletes the right character, but jumps the cursor to the right by 2-3 characters (not necessarily to the end of the input).

**Comment by jcubic** [comment]
I'm not able to reproduce this one on Android/Chrome also tested on Linux/Chrome with disabled keypress (android/chrome don't trigger keypress).

I've added `return false` instead of `return is_touch` in backspace maybe that will fix your issue, sorry not able to test.

**Comment by sharkdp** [comment]
Unfortunately, it did not help, no. Maybe it is also specific to my environment (other JS scripts around)? Hopefully not. Do you have a test environment online?

The backspace issue is not pressing for me, and the original issue is solved. If you want, I can open a new bug report.

In any case, thank you very much!

**Comment by jcubic** [comment]
I have this for testing http://terminal.jcubic.pl/android.php it's just jquery.terminal-src.js file I upload with full screen terminal.

You can open another issue.
