### ISSUE TITLE
Backspace does not work as expected on Chrome/Android

### ISSUE THREAD

**Issue by sharkdp** [jcubic/jquery.terminal#296]
### Expected behavior

Backspace deletes previous character and cursor stays at same position.

### Actual behavior

Backspace deletes previous character but the cursor jumps to the right by 2 characters.

### Steps to reproduce

SwiftKey/Chrome/Android:

* Go to http://terminal.jcubic.pl/android.php
* Type `123456789`
* Use left arrow to move the cursor on top of the `5`
* Press backspace -> `4` is removed, cursor is on top of the `7` (instead of `5`)

**Comment by jcubic** [comment]
It seems that SwiftKey is generating keyCode 229 for every key including backspace, but I was able to fix the issue by checking the length of the text before and after input event.

Can you retest?

**Comment by sharkdp** [comment]
Perfect, now it works. Thank you very much (for digging so deep)!

**Comment by jcubic** [comment]
I also fixed cursor position when click on completion on a keyboard.
