### ISSUE TITLE
Event.key not available in Safari and (slightly) older versions of Chrome

### ISSUE THREAD

**Issue by sharkdp** [jcubic/jquery.terminal#297]
Unfortunately, the newest bugfix has introduced an error in Safari (I believe, could not really test it myself) and older versions of Chrome where `Event.key` is not available:
```
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
```
This means that Enter, Backspace etc. do not work in these browsers.

I saw that there is a check if `event.key` exists in some other parts of the code.

**Comment by jcubic** [comment]
You need to use key [event property polyfill](https://github.com/cvan/keyboardevent-key-polyfill/) (it's in the readme) I can check why you get that exception and not the one that say that you need to use the polyfill

**Comment by sharkdp** [comment]
Oh dear, I totally missed that when going through the installation process. Thank you very much!

**Comment by jcubic** [comment]
In 1.0.14 the exception is thrown when creating terminal or cmd and there is no exception when pressing keys.

**Comment by sharkdp** [comment]
Thank you very much!
