### ISSUE TITLE
Cannot read property 'ansi_colors' of undefined

### ISSUE THREAD

**Issue by noikiy** [jcubic/jquery.terminal#298]
The page load the jQuery lib first.
I got the error when i hover the terminal tab.

![image](https://cloud.githubusercontent.com/assets/977243/24073275/f571291e-0c2f-11e7-84f1-79b18a981fea.png)

**Comment by jcubic** [comment]
Do you load two versions of jQuery and unix_formatting.js ?

**Comment by jcubic** [comment]
Do you have that page somewhere online, if not then maybe you can create codepen or jsfiddle demo that show that error?

**Comment by jcubic** [comment]
I found that [laravel-tracy library](https://cdn.rawgit.com/recca0120/laravel-tracy/master/docs/tracy-exception.html) it seems it work without error.

**Comment by noikiy** [comment]
@jcubic yes, i loaded two jquery with same version.

**Comment by noikiy** [comment]
my project is laravel and the package is laravel-tracy.
i found that the terminal will showthe  error if the page already load jquery

**Comment by jcubic** [comment]
I saved $.terminal that is used in terminal variable in unix_formatting.js maybe that will fix your issue, I've tired to reproduce your error by adding another jQuery library after initialization of the terminal and unix formatting is working (I've loaded old version), don't know why it should throw exception.

Can you test new version of unix_formatting.js?

**Comment by jcubic** [comment]
Ah, I know the reason, because both unix_formatting and jQuery terminal use local copy of jQuery that was used when you included the files,

If you use code like this:
```
<script src="js/jquery-1.8.0.js"></script>
<script src="../repo/js/jquery.terminal-src.js"></script>
<script src="../repo/js/unix_formatting.js"></script>
<script>
$('<div/>').appendTo('body').terminal(function(command, term) {
});
</script>
<script src="js/jquery-1.8.0.js"></script>
```
everything will work as expected. Do you have different order of scripts?

**Comment by jcubic** [comment]
Can you create demo page with just the front-end files? Maybe on jsfiddle or codepen.

**Comment by jcubic** [comment]
Closing because of no response from OP after two weeks.
