### ISSUE TITLE
completion happens above instead of below

### ISSUE THREAD

**Issue by philip-ulrich** [jcubic/jquery.terminal#299]
### Expected behavior
~ > [tab]
exit    clear    resume    cd    ls    echo    help
~ > []

I should be able to tab complete and the options show below my [tab]'d line

Gif:
![example](http://i.exec.tech/t0UX/3YI5dG9E.gif)
(oddly enough.. even in this.... it does duplicates if you do it multiple times

### Actual behavior
exit    clear    exit    clear    resume    cd    ls    echo    help
exit    clear    exit    clear    resume    cd    ls    echo    help
exit    clear    exit    clear    resume    cd    ls    echo    help
~ > [tab][tab][tab][]
The auto complete is actually showing above the same line I tab completed on. 

Gif:
![example](http://i.exec.tech/mxm6/5YgNpuFw.gif)

### Steps to reproduce
See this codepen
http://codepen.io/anon/pen/JWMLwP

This seems to be "broken" as of 1.0.0

**Comment by jcubic** [comment]
I've didn't copy echo_command function when I was writing complete function in version 1.0.

Fixed in master branch it will be in next version.

**Comment by philip-ulrich** [comment]
That would make sense. I can confirm that it is fixed in the master. Thank you!
