### ISSUE TITLE
Copy/Paste to terminal dosen't work in MacOSX

### ISSUE THREAD

**Issue by kevzettler** [jcubic/jquery.terminal#3]
Have Tested in Chrome, Safari, FF3

MacOSX uses the apple/option meta keys + c / v for copy paste the jQuery terminal code is not acknowledging these key combos

**Comment by michaelvashchinsky** [comment]
Is being handled?

We need it too.

Thank you

**Comment by alex-downtown** [comment]
Is there any work being done on this?

**Comment by jcubic** [comment]
I don't have a mac and I can't work on this :(

**Comment by alex-downtown** [comment]
Well... I need this, so I'll work on this myself. Expect pull request next days.

**Comment by jcubic** [comment]
Closed by Mistaken by commit after merge with devel.

**Comment by jcubic** [comment]
@alex-downtown any progress, maybe you can create working demo of pasting in test page and I will be able to take that and incorporate into my code.

**Comment by jcubic** [comment]
Anybody can test if this work on Safari http://stackoverflow.com/a/6035265/387194

**Comment by jcubic** [comment]
https://jsfiddle.net/7rb8ecv5/

**Comment by jcubic** [comment]
Can anybody test devel branch for the issue?

**Comment by automotua** [comment]
Hi, I wanna help do the test. I don't see any copy/paste problems in Safari (9.0.2 (11601.3.9)), Firefox (43.0.4), Chrome(48.0.2564.103, 64-bit) on my OSX 10.11.2. I simply copied / pasted using the demo site http://terminal.jcubic.pl for the testing. That site should be using the 0.9.3 version of temrinal.js, as I checked from the page source.

Hopefully it's of some help.

**Comment by jcubic** [comment]
@automotua thanks for the test, can you also test devel version, you can find it here http://terminal.jcubic.pl/latest.html it use jquery.terminal-src.js file from devel branch.

**Comment by automotua** [comment]
@jcubic Well, the devel branch works in only Chrome, not Firefox or Safari. All are still the same versions indicated above, on same machine.

**Comment by jcubic** [comment]
That's weird because demo with 0.9.3 don't work in Firefox on GNU/Linux.

**Comment by jcubic** [comment]
Can you test this [fiddle](https://jsfiddle.net/7rb8ecv5/2/)?

**Comment by automotua** [comment]
@jcubic 
`} else if (e.clipboardData && e.clipboardData.getData) {`
`   pastedText = e.clipboardData.getData('text/plain');`
`  } else {`
This `else if` will fire in all three browsers, with the alert box showing up with pasted text correctly. No text shows up in the textarea though. But I think it's fine because there's this line: `return false; // Prevent the default handler from running.` .

**Comment by romanman** [comment]
@jcubic what is the chance to get this fix 
any soon ? 
the copy paste from the terminal is pretty 
important ?

**Comment by jcubic** [comment]
@romanman I don't have access to Mac so I can't work on this issue. I've try to install OSX on virtual box but was not able to.

**Comment by romanman** [comment]
@jcubic : actually I have it on Windows 10 Chrome , 
maybe it's a different but when I copy some text
on the terminal the copy mark is removed by 
refresh

**Comment by jcubic** [comment]
I'll try to install windows 10 on virtual box.

**Comment by romanman** [comment]
@jcubic , thanks is it that big difference , 
between chrome on win / linux / mac ???

**Comment by jcubic** [comment]
People report issues with Copy/Paste on Windows and Mac and I don't see any on linux so there must be differences.

**Comment by jcubic** [comment]
It seems that codalab fixed the issue can you take a look at https://github.com/codalab/codalab-worksheets/blob/develop/codalab/apps/web/static/js/custom/jquery.terminal-0.8.8_custom.js if it works? It's old 0.8.8 but copy paste should work, I'll take that code and incorporate it in devel branch.

**Comment by jcubic** [comment]
Anyone? Can you test that file in previous comment?

**Comment by cupuyc** [comment]
@jcubic First I tested on Mac. Mentioned file fixed copy/paste in one browser and broke in another. I looked which changes this file brings, comparing to original 0.8.8 version. I had luck to find out that few lines were removed. So I restored them and it became working on both Win/Mac FF/Chrome.

https://gist.github.com/cupuyc/7281eef0a19b3f4daf459f5dc1f291df

**Comment by jcubic** [comment]
Can you change without that content editable, is it needed?

**Comment by jcubic** [comment]
What about Safarii? Can you test if this return true or false in Safarii and Firefox on a Mac?
https://jsfiddle.net/8L73jfL4/

**Comment by jcubic** [comment]
Can somebody test devel branch version on a Mac Chrome/Firefox/Safari?

**Comment by Tyratox** [comment]
Devel branch works on my mac in Chrome 51.0.2704.84, Firefox 48.0.2 and Safari 9.1.3 (11601.7.8) 👍 :)

**Comment by jcubic** [comment]
Awesome, thanks.

**Comment by jcubic** [comment]
Can somebody test this version in MacOSX chrome/firefox/safari? https://gist.github.com/jcubic/ce02aab838b9bdbb72761e20223f9b63 I've commented out content editable code that was created by codalab, it look like it's not needed, but I want to be sure.

**Comment by Tyratox** [comment]
Works 👍 , tested in the same browsers as stated above.

**Comment by jcubic** [comment]
Great thanks again.

**Comment by stereobooster** [comment]
Still a problem for Mac OS X + firefox

**Comment by jcubic** [comment]
Will be fixed in 1.0.7

**Comment by jcubic** [comment]
Can anybody test devel version? Here is codepen with devel version http://codepen.io/jcubic/pen/LxgJQG

**Comment by jcubic** [comment]
Tested on VirtualBox it work.
