### ISSUE TITLE
Paste in Google Chrome on OSX clears terminal and double-pastes text

### ISSUE THREAD

**Issue by jleibund** [jcubic/jquery.terminal#301]
### Expected behavior
Cmd+V text into jquery terminal command line (with default jquery terminal mappings) should behave as it does in other browsers -- pastes the text.

### Actual behavior
Paste causes terminal command line to clear the existing command text and replaces it double paste.  E.g.

> set  <Cmd+V pasting in the text 'hello'>

produces 

> hellohello

### Steps to reproduce

I am on latest Chrome (OSX) version Version 57.0.2987.110 (64-bit).  I'm using jquery terminal version 1.0.14 and I have also seen this happen on many of the online examples.  It can be reproduced in the Quake demo, the Commodore 64 demo, etc.

You can create demo by forking this codepen http://codepen.io/jcubic/pen/MbVMwO

**Comment by jcubic** [comment]
Unfortunately I can't test because MacOSX in VirtualBox don't work in my old laptop. I've added META+V to be ignored by input event just like CTRL+V on chrome/Windows maybe that will fix you issue.

Can you test the file from master branch?

**Comment by jleibund** [comment]
Thank for the fast response. I'll give it a try tonight or Monday morning
and let you know.

**Comment by jleibund** [comment]
The change worked!
