### ISSUE TITLE
Terminal connection timeout

### ISSUE THREAD

**Issue by xinzealot** [jcubic/jquery.terminal#304]
### Expected behavior
How to keep the terminal connection alive for one hour or two
### Actual behavior
The connection to the terminal timeout every few minutes, but it can be re-connected 
### Steps to reproduce
open a terminal, waiting for a few minutes, the it shows error:timeout

PLease see attached screenshot. Do you know there is any config variable or param when initializing terminal that we can control the duration of the alive connection without timeout? 
![terminaltimeout](https://cloud.githubusercontent.com/assets/25123021/24492168/66c1820a-14f8-11e7-8e53-b397e4da8f91.jpeg)

**Comment by jcubic** [comment]
This is not related to the terminal, your connection timeout (do you use websockets?) not the terminal. You need to catch your error somehow (depend on what is timing out) and reconnect.

**Comment by jcubic** [comment]
Can you share your code? Without looking at the code I can't do much.

**Comment by jcubic** [comment]
Closing. The error came form OP defined code and it seems it's related to Server Side Events that get reconnected and not jQuery Terminal.
