### ISSUE TITLE
How to increase the font size in the terminal?

### ISSUE THREAD

**Issue by fracz** [jcubic/jquery.terminal#305]
I did not manage to increase the font size. My custom CSS is ignored and I could not find any option that configures it. I suppose there is some magic behind this... So asking.

**Comment by jcubic** [comment]
If you don't care about IE and Edge then you can use css variables:
```css
.terminal {
  --size: 2;
}
```
or if you need to support IE and Edge you need to set the size in pixels (em don't work):

```
.terminal, .cmd, .terminal .terminal-output div div, .cmd .prompt {
    font-size: 20px;
    line-height: 24px;
}
```

there is info abot it in [style section of the api reference](http://terminal.jcubic.pl/api_reference.php#style)

**Comment by fracz** [comment]
Tank you!
