### ISSUE TITLE
jquery.terminal doesn't work with cordova app

### ISSUE THREAD

**Issue by ibrarhussainansari** [jcubic/jquery.terminal#309]
If I tap on terminal it launches android keypad, but when type nothing write on terminal.

**Comment by jcubic** [comment]
Do you have a working demo that I can use to recreate the issue? I don't know much about cordova and will be hard for me to test.

**Comment by ibrarhussainansari** [comment]
Right now I just used it on my cordova (hybrid) app. But does't work.
Cordova app doesn't use any mobile browser like chrome etc, it uses webview (A View that displays web pages).
Yes I have blinking cursor. While tapping on any key, it doesn't enter or type anything on terminal.
What is "key property polyfill" ?

**Comment by ibrarhussainansari** [comment]
I will get you working demo very soon.

**Comment by jcubic** [comment]
keyboard events have key property that's not supported by old browsers and if you want to use jQuery Terminal with browser that don't support that property you need to use [polyfill (replacement)](https://github.com/cvan/keyboardevent-key-polyfill/) just include js file and call:

```
keyboardeventKeyPolyfill.polyfill();
```

don't know if that will resolve the issue, it's just shot in the dark.

**Comment by ibrarhussainansari** [comment]
I tried polyfill but still doesn't work.

**Comment by ibrarhussainansari** [comment]
When I hit enter button cursor moves down
For example: 
>
>
> --- cursor blinking here ---

**Comment by jcubic** [comment]
Will test when your provide demo.

**Comment by jcubic** [comment]
Ok, after some struggle I've installed cordova app on my new phone and it's working, the issue (a typo) was fixed in #317

**Comment by jcubic** [comment]
released in version 1.4.3
