### ISSUE TITLE
[QUESTION] - posting JSON-RPC named arguments

### ISSUE THREAD

**Issue by akg518** [jcubic/jquery.terminal#313]
Hi All,

Not sure if this is the best place to post this - Do you know if there is any way for posting JSON-RPC named arguments? currently the 'params' attribute always sends a list instead of a dictionary.

For example:
`command --param1=foo --param2=bar `
produces this RPC call:
`{u'params': [u'--param1=foo', u'--param2=bar'], u'jsonrpc': u'2.0', u'method': u'command', u'id': 3}`
...whereas I'd be expecting this:
`{u'params': {u'param1': u'foo', u'param2': u'bar'}, u'jsonrpc': u'2.0', u'method': u'command', u'id': 3}`

Thanks in advance!

Adrian

**Comment by jcubic** [comment]
Right now only lists (arrays) are supported, but I can add option for objects (dictionaries) when using long options (maybe RPCObjectParams).

But what about a case like this:
```
command --param1=foo bar
```
what should be the output? or maybe it should show error "You can't mix options and normal arguments when using RPCObjectParams option"?

**Comment by akg518** [comment]
Hej Kuba,

Thanks for getting back!

I had a quick look at how this could be done - so far the best way I've found would be via a get-opt like interface. That is - given the short options and long options schema (two strings) it would produce an object with an options object and an argument list, similar to what has been given in examples on https://docs.python.org/2/library/getopt.html.

so your command line would be converted from this:

`command --param1=foo bar`

...to this:

`{'params': {'opts':{'param1': 'foo'}, 'args': ['bar']}, 'jsonrpc': '2.0', 'method': 'command', 'id': 3}`

I'll be developing this functionality on the server side, but I'd imagine many people would be interested in such a functionality.

Btw I did find an implementation of get-opt in js that you might be interested in looking:
https://www.npmjs.com/package/getopt

Thanks again,
Adrian

**Comment by jcubic** [comment]
I just look at JSON-RPC spec and there are no named arguments so sorry, but I want to be compliant with a spec.

You can modify server side to parse array (list) and extract the named arguments (create dictionary), this should't be to difficult the oter option is to use function as interpreter parse comman and send json you want.

**Comment by jcubic** [comment]
BTW getopt in javascript is for parsing arguments based on spec so it's no use here.

**Comment by akg518** [comment]
Sure, no problem I've already implemented on the server side - just wanted to check if I'm not duplicating work.

Thanks again
Adrian
