### ISSUE TITLE
Firefox : capslock on - ctrl+c  - outputs c

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#314]
### Expected behavior
selected text is copied to clipboard
### Actual behavior
outputs char "c" nothing copied
### Steps to reproduce
capslock is on , select text in terminal press ctrl+c

**Comment by jcubic** [comment]
It was happening for all CTRL+key when caps-lock was on, I've disabled keypress when CTRL or Mac Command key is pressed. Will be in next version.

**Comment by jcubic** [comment]
released in version 1.4.3
