### ISSUE TITLE
slow performance : char_size is called several times per plugin's operation ( i guess like 4 times )

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#315]
### Expected behavior
store char size after each plugin operation, to eleminate need to append temporary cursor 4 times.
### Actual behavior
char_size is called 4 times per one plugin's operation (ex: resize, command output.. etc) on screen resulting in appending temp span cursor (4x per plugin on screen)  to body ( which slows performance, say you have many terminals on screen) 

also when numChar/numRows manually defined would be great to not call native methods ( get_num_chars / get_num_rows ) at all

**Comment by jcubic** [comment]
the function is executed only on resize and calculation in resize are not executed when the options `numChar/numRows` are set.

The improvement will be in next version

**Comment by jcubic** [comment]
In version 1.5.0
