### ISSUE TITLE
inputs trigger terminal keypress event which terminal assignes to document

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#316]
### Expected behavior
do not call key press event handler on other inputs presented on page with terminal
### Actual behavior
if there are other inputs on page beside terminal, assigned key press ( keypress	:  function() {} ) event from terminal will be also triggered on input key press

**Comment by jcubic** [comment]
Thanks for reporting the issue, the fix will be in next version.

**Comment by jcubic** [comment]
released in version 1.4.3

**Comment by jcubic** [comment]
Forget about keydown it had the same issue, will be in next version.
