### ISSUE TITLE
Chrome : next key press after CTRL+V will output text from clipboard second time

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#318]
### Expected behavior
after ctrl-v next key press dont paste second time from clipboard
### Actual behavior
after CTRL+V and pressing random key, terminal will output paste second time from clipboard
### Steps to reproduce
copy something -> CTRL+V -> press any key

**Comment by jcubic** [comment]
Fixed in devel branch.

**Comment by jcubic** [comment]
In version 1.5.0
