### ISSUE TITLE
Weird syntax highlighting issues with formatter in 1.5.2

### ISSUE THREAD

**Issue by ovk** [jcubic/jquery.terminal#325]
### Expected behavior
Syntax highlighting is independant from the cursor position.

### Actual behavior
If cursor put in the middle of formatted keyword, pressing spacebar leads to `&nbsp` appearing in the user input. 

### Steps to reproduce
https://jsfiddle.net/txgg52fa/2/
Just type something like `xtestx`, the `test` part will be blue. Point your cursor in between `s` and `t` letters and press spacebar. Then press backspace.

### Browser and OS
Chrome  60.0.3112.78 on Ubuntu 16.04

This is followup to my question on SO: https://stackoverflow.com/questions/45406312/whole-line-formatting-in-jquery-terminal

**Comment by ovk** [comment]
Update: 

It looks like the issue not related formatter. Even without formatter registered, moving cursor over space leads to `&nbsp;` appear in place of space. For example, with input string `a b` moving cursor left/right will reproduce the problem.

**Comment by jcubic** [comment]
Thanks for the report, fixed that in devel branch, you can test if it work for you one [this codepen](https://codepen.io/jcubic/pen/LxgJQG)

**Comment by ovk** [comment]
It looks like it is fixed. Formatter seems to be working properly as well. Thanks.

**Comment by ovk** [comment]
Apparently the issue wasn't fixed completely. Strangely enough, it still can be reproduced using specific RegExp in a formatter.

Please take a look at this example: https://jsfiddle.net/txgg52fa/3/
Type any number and press spacebar to see the issue.

**Comment by jcubic** [comment]
There are two issues here one is that formatters are applied to formatting (you have [[;blue;] in greetings for url) the second if the regex text that you enter is first encoded (spaces are replaced by &nbsp; and then formatters are applied) the solution is to use this formatter:
```javascript
$.terminal.defaults.formatters.push(function(string) {
             return string.replace(/&[^;]+;|([A-Za-z])/g, function(_, match) {
                 return match ? "[[b;blue;]" + match + ']' : _;
             });
         });
```

**Comment by jcubic** [comment]
The first issue is resolved in devel branch will be in next version 1.6.0.

**Comment by jcubic** [comment]
version 1.6.0 is out.
