### ISSUE TITLE
Usage with Angular 2

### ISSUE THREAD

**Issue by MaximeAnsquer** [jcubic/jquery.terminal#328]
Hello,

Is this terminal usable withing an Angular 2 app?
If yes, could you briefly explain how to integrate it?

Thank you very much!

**Comment by jcubic** [comment]
Sorry don't know Angular 2, maybe you can check [AngularJS wrapper](https://github.com/primalfear/angular-terminal) and extract something out of it. it use events to comunicate with terminal instance.
