### ISSUE TITLE
when pasting from buffer (ctrl-v), then returning false on keypress, strange behavor on next key press

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#331]
### Actual behavior
pressing ctrl-v, then pressing some key which is forbidden (keypress return false), pressing next char (which is ok) terminal will insert strange text
### Browser and OS
chrome. ffox.

**Comment by jcubic** [comment]
there was an issue with pasting, can you test devel version in this pen https://codepen.io/jcubic/pen/LxgJQG

**Comment by artursOs** [comment]
just have tested and it's working now. thanks

**Comment by jcubic** [comment]
released in version 1.7.0
