### ISSUE TITLE
onTerminalChange || onFocus 

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#339]
### Expected behavior
trigger onTerminalChange event
### Actual behavior
when trying to switch between terminals on a page, onTerminalChange doesn't evoke
### Steps to reproduce
switch between terminals on a page
### Browser and OS
chrome||ffox.

**Comment by jcubic** [comment]
The issue was because of focus handler on textarea I wanted to have foucs when user press tab while on a page, I've removed that code because it was causing problems and also onTerminalChange is called for all terminals.

**Comment by jcubic** [comment]
Released in version 1.8.0
