### ISSUE TITLE
Problem with copy and paste

### ISSUE THREAD

**Issue by raviteja2200** [jcubic/jquery.terminal#340]
## Expected behavior
New text typed after a string, which is pasted should be appended
## Actual behavior
The copied text disappears and new char typed is being printed twice
## Steps to reproduce
- Copy a long string (cmd +c)
- Paste it on terminal (cmd +v)
- Type a single letter 'a'
- Notice that the copied string is gone and 'aa' on terminal

## Browser and OS
Browser:Version 60.0.3112.113 (Official Build) (64-bit)
OS: macOS Sierra
version 10.12.6

**Comment by jcubic** [comment]
Fixed in devel branch.

**Comment by raviteja2200** [comment]
Thanks for the quick fix, will this be available in next release?

**Comment by jcubic** [comment]
yes, next version 1.9.0

**Comment by raviteja2200** [comment]
Thanks, I have tested the fix using devel branch.
