### ISSUE TITLE
Disallow images to be pasted as commands on the terminal

### ISSUE THREAD

**Issue by ssv1000** [jcubic/jquery.terminal#342]
### Open jquery terminal.
        Copy an image to the clipboard
       Go to terminal and do Ctrl+V  -- then image will be pasted on to the terminal

**Comment by jcubic** [comment]
This is a features added on purpose, when you have images in clipboard they can be echo when paste.

Do you think it's a bad idea?

I can make an option to disable that feature.

**Comment by ssv1000** [comment]
I think am option would be good. We just need the text to be copied and
everything else should be blocked.

thanks


On Thu, Sep 28, 2017 at 11:39 AM, Jakub Jankiewicz <notifications@github.com

**Comment by ssv1000** [comment]
Can you please let me know if you are fixing this bug by providing an
option to use "just text copy".
And also please let me know in which release the fix will be available, and
when the release will be available for us to use.

Appreciate your help on this.


thanks

**Comment by jcubic** [comment]
Added in devel branch option `pasteImage`, it will be in next version 1.9.0.

You can grab devel version if you need it now, all build files have VER as version so you will know it's devel version.

**Comment by raviteja2200** [comment]
tested this change on devel branch, works as desired.

**Comment by ssv1000** [comment]
tested
