### ISSUE TITLE
ctrl+c is not doing anything

### ISSUE THREAD

**Issue by abhiks19** [jcubic/jquery.terminal#343]
### Expected behavior
ctrl+c should ignore the entered string and provide a new prompt

### Actual behavior
ctrl+c is not doing anything

### Steps to reproduce
1. Enter a random string 
2. Press "CTRL+C"

### Browser and OS
Chrome, IE, Edge - Windows 10

**Comment by jcubic** [comment]
this is by design because CTRL+C copy text to clipboard in any browser so I left it so you can select text inside terminal and copy.

I can do what you want if selection is empty, but then there will be two functions for the same key, I don't know if that's good idea.

**Comment by zhangyitao421** [comment]
On windows command prompt, CTRL+C without selecting any text will cancel the current command. CTRL+C with some text selected will copy the text.
I think jquery terminal should have the similar behavior.

**Comment by abhiks19** [comment]
I would agree with zhangyitao421 here.

**Comment by jcubic** [comment]
Added in devel branch the same as it look in bash on GNU/Linux it echo `command + "^C"` and clear the current command.

**Comment by abhiks19** [comment]
Thank you!. Works as expected.
