### ISSUE TITLE
Opening angle bracket causes text to disappear when moving cursor

### ISSUE THREAD

**Issue by itsZN** [jcubic/jquery.terminal#345]
### Expected behavior
Moving the cursor would not cause text to disappear to the right of it.

### Actual behavior
If the cursor any further than one character before the first `<` character, all characters after the cursor are invisible.

### Steps to reproduce
* Type `AAAAAAAAAAAAAB<BBBBBBBBBBBB` into a console
* Move your cursor over any of the Bs
* The Bs to the left of the cursor should disappear

### Browser and OS
Chrome 61 Win 8.1/ Win 10

It think it is related to the `<` not being escaped.

**Comment by jcubic** [comment]
fixed in devel branch

**Comment by jcubic** [comment]
Released in 1.9.0
