### ISSUE TITLE
Erasing of pasted string cause its duplication

### ISSUE THREAD

**Issue by RinaVladimyrovna** [jcubic/jquery.terminal#346]
### Expected behavior

- The last N characters of the string are erased

### Actual behavior

- The string is duplicated if two last characters are erased

### Steps to reproduce

- Paste any string containing more then three character
- Start erasing its last characters using backspace

### Browser and OS

- Chrome 61.0.3163.100
- Opera 48.0.2685.35
- Edge 40.15063.0.0
- EdgeHTML 15.15063
- Win 10

**Comment by jcubic** [comment]
Which version you're using, I'm not able to reproduce and I've just released version 1.9.0 can you test it in that version?

**Comment by RinaVladimyrovna** [comment]
I used 1.8.0.
And yes, there is no such a thing in 1.9.0.
Thank you very much.
