### ISSUE TITLE
The first typed letter is doubled if a string was pasted previously

### ISSUE THREAD

**Issue by RinaVladimyrovna** [jcubic/jquery.terminal#347]
### Expected behavior

- Letters are typed without duplication

### Actual behavior

- The first letter to type is duplicated

### Steps to reproduce

- Paste any string
- Type any letter

### Browser and OS

- Edge 40.15063.0.0
- EdgeHTML 15.15063
- FireFox 55.0.3 
- Chrome 61.0.3163.100
- Opera 48.0.2685.35
- Win 10

**Comment by jcubic** [comment]
Fixed in 1.9.0
