### ISSUE TITLE
All printed text is highlighted grey in Edge

### ISSUE THREAD

**Issue by RinaVladimyrovna** [jcubic/jquery.terminal#348]
### Expected behavior

- The text is not highlighted grey as it is in other browsers

### Actual behavior

- The text is highlighted grey

### Steps to reproduce

- Look at Demo section of http://terminal.jcubic.pl/ in the Edge browser

### Browser and OS

- Edge 40.15063.0.0
- EdgeHTML 15.15063
- Win 10

**Comment by jcubic** [comment]
This issue was fixed in 1.9.0 just now.

**Comment by RinaVladimyrovna** [comment]
Thank you.
