### ISSUE TITLE
An additional cursor appears in Safari and Edge

### ISSUE THREAD

**Issue by RinaVladimyrovna** [jcubic/jquery.terminal#349]
### Expected behavior

- There is only one cursor in the Terminal

### Actual behavior

- There is additional cursor to the left of the active line

### Steps to reproduce

- Type any letter in the Terminal
- Look at the very left end of the line

### Browser and OS

- Safari 10/602.1
- iOS 10.3.1
- Edge 40.15063.0.0
- EdgeHTML 15.15063
- Win 10

**Comment by jcubic** [comment]
In Edge/IE it was reported and fixed in #344

**Comment by RinaVladimyrovna** [comment]
I apologize for repeating.
Thank you.

But now the same issue exists in 
**IE 11.608.15063.0
Win 10**
