### ISSUE TITLE
CTRL+V when overwritten throws an error

### ISSUE THREAD

**Issue by raviteja2200** [jcubic/jquery.terminal#351]
### Expected behavior
Shouldn't throw an error, should execute original.
### Actual behavior
Throws an error, original is not a function
### Steps to reproduce
When you overwrite 
param keymap: {
```javascript
'CTRL+V' : function(e, original){
   return original(e);
  }
}
```

### Browser and OS
Chrome, MAC high Sierra

**Comment by jcubic** [comment]
Thanks for the report, fixed in devel branch and also fixed `this` context.

**Comment by raviteja2200** [comment]
Thanks for the quick fix, tested this fix on devel branch
