### ISSUE TITLE
Input of some characters result in HTML code instead

### ISSUE THREAD

**Issue by lepe** [jcubic/jquery.terminal#352]
### Expected behavior
For example, entering `<  > [  ]` should print those characters

### Actual behavior
It is printing: `"&#60;&#61;&#93;&#91;" `
(it doesn't happen if its the very first character)

### Steps to reproduce
Type those characters

### Browser and OS
Ubuntu 16.04 64bits
Chrome 61.0.3163.102
Firefox 56.0

**Comment by lepe** [comment]
The reason seems to be in line 1689:
```javascript
function draw_cursor_line(string, position) {
                var len = $.terminal.length(string);
                if (position === len) {
                    before.html(string);   //<-------- replaced: format(string) for string
                    cursor.html('&nbsp;');
                    after.html('');
                } else if (position === 0) {


```
Now seems to be working fine. I'm not sure it it could have side effects.

**Comment by jcubic** [comment]
This is already fixed in devel branch, can you test https://codepen.io/jcubic/pen/LxgJQG
