### ISSUE TITLE
changing numChars manually with settings()

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#353]
### Steps to reproduce
when changing numChars manually with settings(). and then perform resize().  terminal doesn't recalculate max new num chars for command prompt value.

**Comment by jcubic** [comment]
The setting numChars was just a hack to make test from jasmine node work becuase there are no css there to make width of the terminal so I've created that option to set number of chars. I didn't know it even work outside of tests.

Maybe I should not put it in docs.

**Comment by jcubic** [comment]
In devel branch, I've made a change to get inline style from terminal instance for fake `.terminal` div, but you still need to call resize() manually becuase changing font don't trigger resizer, (the width&height is not changed).

**Comment by artursOs** [comment]
there are two problems. first it doesn't correctly return actual num chars per line. (maybe because of custom css) 
and second :
 problem is that when i have many terminals on screen , executing this code : 
var temp = $('<div class="terminal temp"><div class="cmd"><span cla' +
			'ss="prompt">&nbsp;</span></div></div>').appendTo('body');
cost 30 ms in my chorme brower per terminal . so image if i have 16 terminals on screen. not too good for User expirience.
so i tried to calculate num chars manually only 1 time before resizing all terminals. (for ex. when user changing font size, or change width of his browser window. Or even on terminal init) 
so i just return {} and rely on setting.num_chars

**Comment by jcubic** [comment]
I've put character size check in font resizer so it will fire only when you change font.

**Comment by jcubic** [comment]
And fixed the requested bug with command line resize on settings.numChars + terminal.resize, didn't get what you wanted first time I've read the issue.

**Comment by jcubic** [comment]
The change is in version 1.11.0
