### ISSUE TITLE
changing font size of terminal

### ISSUE THREAD

**Issue by artursOs** [jcubic/jquery.terminal#354]
changing font size of terminal, doesn't change new numChars cmd promt can handle

**Comment by jcubic** [comment]
Font size change need to be done on .terminal class, ideally by changing `--size` css variable, because that's the easiest way.

To calculate the char size new div with terminal class is added to body, so terminal will to work when created and then appended to DOM.

```
$('<div/>').terminal().appendTo('body');
```

**Comment by jcubic** [comment]
In devel branch, I've made a change to get inline style from terminal instance for fake `.terminal` div, but you still need to call resize() manually becuase changing font don't trigger resizer, (the width&height is not changed).

**Comment by jcubic** [comment]
Added resizer for font-size, you can now change font-size or --size without the need to call resize method.

The fix is in devel branch, will be in version 1.10.0
