### ISSUE TITLE
Scroll jumps to the bottom

### ISSUE THREAD

**Issue by RomanPerin** [jcubic/jquery.terminal#355]
### Expected behavior
If you scroll with a mouse, scroll should stay in a place where you stopped scrolling.

### Actual behavior
If you scroll with a mouse, scroll jumps to the bottom.

### Steps to reproduce
1. type a lot of commands to be able to see a scroll;

2. click on terminal output;
3. try to scroll with a mouse by bragging thumb of scrollbar;
4. after stop dragging (mouse up), scroll jumps to the bottom;

#### Important:
It seems like it is regression issue caused by fix of [problems with a focus](https://github.com/jcubic/jquery.terminal/issues/255);

Also, it is reproduce-able in pair with jquery-ui.draggable (jquery-ui version: 1.12.1, jquery.terminal version: 1.9.0). 

### Browser and OS
OS: Mac Sierra 10.12.6

browsers:
1. Chrome 61.0.3163.100 (Official Build) (64-bit)
2. FireFox 56.0.2

**Comment by jcubic** [comment]
Fixed in devel branch.

**Comment by RomanPerin** [comment]
Cool! thx! It works fine for me)

**Comment by jcubic** [comment]
Released in version 1.10.1
