### ISSUE TITLE
Term.echo a line ending with closing bracket not shown

### ISSUE THREAD

**Issue by arucil** [jcubic/jquery.terminal#358]
### Expected behavior

Echoing multiline strings with a line ending with a closing bracket should work correctly.

### Actual behavior

When I printed a multiline string with the first line ending with a closing square bracket, the first line didn't show, while the other lines did.

### Steps to reproduce

`term` is an instance of the terminal.
```
term.echo(`haha [
123`);
```
Then only the second line `123` showed.

### Browser and OS

Browser: Chrome 62.0.3202.94
OS: Linux Mint 18.2

**Comment by jcubic** [comment]
Sorry, forget about this bug in version 1.11.0 will fix soon and it will be in version 1.11.1

**Comment by jcubic** [comment]
The fix is in devel branch.

**Comment by jcubic** [comment]
in version 1.11.1
