### ISSUE TITLE
Terminal does not work in iPad

### ISSUE THREAD

**Issue by billyzkid** [jcubic/jquery.terminal#36]
Focus on the terminal does not bring up the iPad keyboard so there is no way to provide input.

**Comment by hervethouzard** [comment]
It's running on my iPad mini with iOS 9.2

**Comment by jcubic** [comment]
Does it work or doesn't?

**Comment by hervethouzard** [comment]
Yes, it works

**Comment by jcubic** [comment]
Great thanks for testing.
