### ISSUE TITLE
Way to disable prompt completely except on event trigger

### ISSUE THREAD

**Issue by ericMLindgren** [jcubic/jquery.terminal#360]
So I'm using jquery terminal as a front end for a go back end with websockets as our protocol. I would like the go back end to provide the prompt entirely, (i.e JQT should display no prompt except on receiving async 'message' events on the socket). I wonder if there's a simple way to do this? I've explored the project pretty thoroughly and didn't see anything obvious...

I have the remote events updating the prompt object but the problem is that the prompt gets written again immediately before the remote even has time to change the local prompt object. So it's often out of sync

The ideal would be a prompt() command, like the echo command, so that I could disable prompt completely and drive it remotely...

**Comment by jcubic** [comment]
I don't know if I understand correctly but if you just want to set prompt using code you can use `terminal.set_prompt("prompt>>>> ")`. you can also set it to empty string.

There is also a feature that allow to execute commands from echo so if you have json-rpc (you don't use it but), they look like this `[[command args....]]` you just echo this and it's get removed from output but the command get executed, you can create one command that will set prompt:
```javascript
$(node).terminal({
   prompt: function(value) {
      this.set_prompt(value);
  }
});
```

and then if you echo the stuff from the server the server can decided when to change the promp by sending `'[[prompt "new prompt"]]'` over a socket.


you can even create method that will invoke terminal methods like this:
```javascript
// if you can use ES6 otherwise you will need to use arguments array and slice
method: function(method, ...args) {
   this[method].apply(this, args);
}
```

and send `[[method set_prompt "new prompt"]]` or `[[method clear]]` it was made just for RPC when you can write your whole logic in server side.

**Comment by ericMLindgren** [comment]
Okay, I have to run for a couple hours but I'll try these solutions out when I get back... Will let you know! Thanks for all the hard work. You've made something great :)

**Comment by ericMLindgren** [comment]
hmmm yeah, I can do all of those things. I would send you a link but my server is down... 

What happens is something like this...
#user sends message to server
(player_74)[python]>team red

#server sends message back (along with a state update that triggers set_prompt()
success: You're on the red team

#JQT prints the next prompt before the promptState message has arrived and been processed
(player_74)[python]>

#JQT does not check the status of the prompt (although set_prompt() has already been called)
(player_74)[python]>l

#now that a command has been entered JQT checks the prompt variable and updates appropriately
error: Unknown command 'l'
(player_74):red:[python]>

the problem is that red should have been inserted in the prompt after the first command before redrawing the prompt. Also tried to delay drawing the prompt by 100ms but that seemed tricky to achieve... is this clearer?

My ideal behavior would be:
<- receive promptState message from server
drawServerGeneratedPrompt> Enter Command
--- wait
<- receive message message from server and print
error: Unknown command 'Enter Command'
<- receive promptState message from server 
drawServerGeneratedPrompt>

**Comment by jcubic** [comment]
If you have async commands I've created two methods `pause()` and `resume()` just for that. You call `pause()` before you do async code (that's response to user command) and when you're done you call resume, it will show/hide the terminal and it also needed if you do exec with async commands and want your commands to be executed one after another.

you can try to call pause when user enter command and resume in your socket response.

**Comment by ericMLindgren** [comment]
Ah ok. Perfect, that works for me :) I didn't understand how pause resume were meant to operate.

Thanks for taking the time!
