### ISSUE TITLE
Invalid completion suggestions given

### ISSUE THREAD

**Issue by ovk** [jcubic/jquery.terminal#361]
### Expected behavior

Autocompletion only suggests commands from the completion list.

### Actual behavior

Commands not present in completion list are suggested.

### Steps to reproduce

See: https://jsfiddle.net/a8po3ran/1/
Type `base` and press TAB. It will be completed to `base64code` which is not in the list.

### Browser and OS
Ubuntu 16.04, both Firefox and Chrome.

**Comment by ovk** [comment]
Btw this was working fine in 1.5.2. Not sure though at what version exactly it was broken.

**Comment by jcubic** [comment]
the afected version was 1.8.0 that fixed one issue with mixed case and case insensitive completion.

The fix will be in 1.11.1
