### ISSUE TITLE
Numpad operations (+, -, /, *) and decimal dot are not handled correctly in Internet Explorer

### ISSUE THREAD

**Issue by ovk** [jcubic/jquery.terminal#362]
### Expected behavior

Pressing numpad keys such as `+`, `-`, `*`, `/`, `.` append corresponding character to current command line.

### Actual behavior

A word representing the key is appended instead. For example, `2+2` becomes `2Add2` and `2-2` becomes `2Subtract2`. Numlock status doesn't matter.

### Steps to reproduce

Open https://jsfiddle.net/4sggc4cy/1/ and try typing `2+2` using numpad plus.

### Browser and OS
Windows 7, IE10 and IE11. Not sure it this is broken for other versions of IE or Edge as I don't have access to them.

**Comment by jcubic** [comment]
Thanks for the report, it's just another inconsistency in how IE set key property

**Comment by jcubic** [comment]
the fix is in devel branch will be in 1.11.1
