### ISSUE TITLE
System.describe manual refresh

### ISSUE THREAD

**Issue by kodemonk** [jcubic/jquery.terminal#364]
Hi,

I am using jquery.terminal as a console to interact with my backend. I can see that every time that I refresh the page there is a system.describe call to the backend. Problem is one of the commands I implemented is a load <entity>. And every different entity supports a different command set.

Is there any easy way I can manually launch a system.describe after every load so that the system refreshes the list of available commands?

Thanks a lot in advance!

**Comment by jcubic** [comment]
You mean that `system.describe` return different results after you call `load` or that `load` act like `system.describe` that return new set of commands?

Can you provide the code and the list of commands that you execute? it and be simplified do demonstrate the flow.

**Comment by kodemonk** [comment]
Thanks for coming back to me so quickly. 

What I mean is simple. Every time a user logs in through RPC a session is created in the backend linked with a token. This session stores the state from one command to the next one.  For example: This would be a typical user interaction:

1) After loading Jquery.terminal a system.describe call is automatically made to the backend. Which replies with 3 possible commands [exit, load, whoami]. Autocomplete works fine until this point.

2) Now user wants to work with one company and for thats uses, the command load ("load <company_id>"). I.e: load 4581657

3) Now the backend knows that there is a company loaded and even the terminal prompt is changed to CORP>. Also and most importantly a new set of commands is available [exit, load, unload, describe, whoami, set, delete]

4) Once a company is loaded the user can for instance describe it (a command which didn't make any sense at point 1). For that he simply types describe. An the info appears on the terminal screen. I can do that in the backend because I know what company is loaded, so once I receive a describe command I return the appropriate info.

The problem I have is that as you can see the list of available commands changes with every load. At point 1 there were 3 commands [exit, load, whoami] but after loading the company there are 7 [exit, load, unload, describe, whoami, set, delete].

The system.describe call is made automatically only once at the script startup (as long as completion property is set to true) but I would like to be able to invoke it manually after every load command because I want jquery.terminal to know at every point of time which commands are available to autocomplete

Hope this clarifies

Thanks again!

**Comment by jcubic** [comment]
You can do something like this:

```javascript
$.terminal(['rpc-service', {
   refresh: function(prompt) {
       this.push('rpc-service', {prompt: prompt});
   }
});
```

and then the load command can return string `"[[ push 'company number']]"`. this will call system.describe again to get new commands and set the prompt. Although this will allow to exit the new interpreter using CTRL+D and exit command if you don't want that you can try can try using:

```javascript
this.set_prompt(prompt).set_interpreter('rpc-service');
```

**Comment by kodemonk** [comment]
Great idea! That will do. I will try it right away ;) Thanks and keep up with the great work!!

**Comment by jcubic** [comment]
One more thing if you don't want the push command in your completion you can use function as second value in array:

```javascript
$.terminal(['rpc-service', function(command) {
   var cmd = $.terminal.parse_command(command);
   if (cmd.name == "push") {
       this.push('rpc-service', {prompt: cmd.args[0]});
   }
}]);
```
