### ISSUE TITLE
--char-width undefined warning

### ISSUE THREAD

**Issue by SplicePHP** [jcubic/jquery.terminal#371]
When including the css file via webpack I get the following warning:

jquery.terminal.css:443:9: variable '--char-width' is undefined and used without a fallback

My webpack loader looks something like this:
```
                    {
                        test: /\.css$/,
                        use: [
                            "style-loader",
                            "css-loader",
                            'postcss-loader'
                        ]
                    },
```

**Comment by jcubic** [comment]
I've used `var(--char-width)` because there are no sensible value for default width character and the value is always set.

I can add 1 as default value just to remove the warning if you want. Or maybe I put the value that is generated in Chrome for default font which is about `7`.

**Comment by jcubic** [comment]
The fix is in devel branch will be in next version which will be 1.12.0.
