### ISSUE TITLE
autoscroll not working

### ISSUE THREAD

**Issue by N1kop0l** [jcubic/jquery.terminal#388]
### Expected behavior
autoscroll is working with large results like 'dir c:/'
### Actual behavior
autoscroll is not working
### Steps to reproduce
I have modified the code, can  get some help please?  also I need to talk with you guys about a adding your code into my project, thanks!
### Browser and OS
chrome, ie, firefox

**Comment by jcubic** [comment]
Can you created a Demo? this one works for me https://codepen.io/jcubic/pen/aGmdoW press enter to echo few lines and counter.

**Comment by jcubic** [comment]
autoscroll works this way if before scrollbar is at the bottom it autoscroll if not then it don't scroll.

**Comment by jcubic** [comment]
Also there is [chat on website](https://terminal.jcubic.pl/#chat) and [old one from gitter](https://gitter.im/jcubic/jquery.terminal), I can help you there.

**Comment by N1kop0l** [comment]
I have modified the code but it's still not scrolling, I tried also clearing the cache but no luck

**Comment by N1kop0l** [comment]
The last code did the trick for chrome, but now scrolling is not working with firefox

**Comment by N1kop0l** [comment]
When I only use : 
scroll_object = $('body,html');
it works  for chrome & firefox, do you think that this can cause other problems?

**Comment by jcubic** [comment]
The fix from last snipped is added in version 1.15.0
