### ISSUE TITLE
echo not printing the closing square bracket for JSON stringify-ied output

### ISSUE THREAD

**Issue by ArsalanKhairani** [jcubic/jquery.terminal#390]
### Expected behavior
```
[
  {
    "error": "bug"
  }
]
```

### Actual behavior
Note the closing square bracket.
```
[
  {
    "error": "bug"
  }

```

### Steps to reproduce
```javascript
term.echo(JSON.stringify([{"error": "bug"}], null, 2));
```

### Browser and OS
Google Chrome Version 65.0.3325.181 (Official Build) (64-bit) | Linux.
https://codepen.io/anon/pen/VxKbYO

**Comment by jcubic** [comment]
Fixed in devel branch, I've needed to remove one line that was removing blank formatting from the end (the formatting was optional and it was removing single closing bracket), I hope it doesn't break anything, tests are fine.

**Comment by ArsalanKhairani** [comment]
@jcubic: Thanks. When will u be making a release?

**Comment by jcubic** [comment]
maybe in the end of next week

**Comment by jcubic** [comment]
in version 1.15.0
