### ISSUE TITLE
On Android web clients, first character entered into terminal gets appended by single whitespace

### ISSUE THREAD

**Issue by aborovac** [jcubic/jquery.terminal#391]
### Expected behavior
Don't append anything
### Actual behavior
Appends whitespace to first character entered into terminal
### Steps to reproduce
1. Open terminal demo template at http://codepen.io/jcubic/pen/MbVMwO
2. enter whatever into terminal
### Browser and OS
Dolphin, Chrome on Android

**Comment by jcubic** [comment]
Yes, I also notice that but it's added by browser autocomplete feature and I can't do nothing about this. There are attributes that suppose to disable autocomplete but they seems to not work. I can try take a look again maybe I can think something about it.

**Comment by jcubic** [comment]
it seems that this happen only to the first character afer you focus on the terminal

**Comment by jcubic** [comment]
Fixed in devel branch, the problem was the hack that insert space at the beginning for select all context menu. I didn't put space correction code in insert event that is used on android.

**Comment by jcubic** [comment]
in version 1.15.0
