### ISSUE TITLE
import_view() - getting VE.Top is not defined error

### ISSUE THREAD

**Issue by mesurinna** [jcubic/jquery.terminal#393]
### Expected behavior
On window.beforeUnload i save all data in the SessionStorage with export_view(). If i import then on page reload all data is shown correctly with the import_view() method. But when i want to use the terminal i am getting an JS Error VE.Top is not defined?

what did i missed? 

This is my Code where i initialize the terminal:

`
 
       $('.terminal_demo').terminal(
	
            function(command) {
                if (command !== '') {
    				$(".cmdInput").val(command);
    				$(".cmdInput").change();
    				this.pause();    				
                }
            }, {
                greetings: 'Terminal Emulator Demo',
                import_history: true,
                name: 'js_demo',	        
                prompt: '> '
    	    }
        );

        if (sessionStorage.getItem(rootFormName + " ." + str_class[0]) != null) {
	    var restoreData = JSON.parse(sessionStorage.getItem(rootFormName + " ." + str_class[0]));
	    $('.terminal_demo').terminal().import_view(restoreData);
	}   
`

**Comment by jcubic** [comment]
The problem is that export_view data is not suitable to JSON.stringify because it have interpreter Stack Structure with functions, so if you export view with nested interpreter you will get the same interpreter.

I can make it ignore interpreters if it's not Stack object.

**Comment by jcubic** [comment]
Also lines have finalize functions but they will just be ignored by JSON.stringify

**Comment by mesurinna** [comment]
Saving data without JSON.stingify in sessionStorage and wihtout JSON.parse to read is resulting in another JS Error Ae.Push is not a function. 

How can i save these data and reload them on a page refresh?

**Comment by mesurinna** [comment]
can i just echo out the data exported by export_view()? Just want to reload just all stuff happened before.
