### ISSUE TITLE
Wrong bracket when echo formatting in brackets

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#396]
### Expected behavior
formatting in brackets:

```javascript
term.echo('[[[b;#fff;]hello]]')
```

should display `[hello]` with text as white.

### Actual behavior
it shows: `[hello][` (in prompt it's fine, so it's only for echo).

**Comment by vitalyo7** [comment]
Having similar issue with unix formatting + color formatting:

term.echo("�[0m[�[36m�[33m0x109de1d4�[0m]�[36m�[0m�[0m�[31m")
The final result of which get interpreted as 

[[[;#0AA;]][[;#A50;]0x109de1d4]][[;#0AA;]][[;#A00;]]

Looks like when you have a mix of color codes and plain [ character color gets messed up.

**Comment by jcubic** [comment]
With unix formatting you can use this long option unixFormattingEscapeBrackets added by @ml1nk in #372 it seems that I've forget to add it to documentation. It fix the problem, the same when I use:
```javascript
term.echo('&#91;[[b;#fff;]hello]&#93;')
```

**Comment by jcubic** [comment]
There was two problems one in nested formatting function and the second was in extended commands, your example was invoking commands. And the problem was regex `\[\[(?:[^\]])*` which was matching `[[[` where is should skip first brackets, adding regex `[^\][]` solved the issue.
