### ISSUE TITLE
Typescript d.ts

### ISSUE THREAD

**Issue by 0xF6** [jcubic/jquery.terminal#406]
Where to find?

**Comment by jcubic** [comment]
There are no such file right now but I wanted to add one for jQuery Terminal.

**Comment by jcubic** [comment]
If you know typescript you can help create one.

**Comment by 0xF6** [comment]
Okay, I'll do it in a few days.

**Comment by 0xF6** [comment]
It's harder than I thought. Too difficult.

**Comment by jcubic** [comment]
I've started working on this, there is lots of types to add, I hope to have it for the next version.

**Comment by jcubic** [comment]
Types are ready, right now you can use them by copy paste.They will be in npm in next version probably in a week.

**Comment by 0xF6** [comment]
Thanks!

**Comment by jcubic** [comment]
Found bug in typescript definition strings in options should be optional the same like other fields

**Comment by jcubic** [comment]
released in version 1.19.0
