### ISSUE TITLE
React component for dterm.js 

### ISSUE THREAD

**Issue by amarendrar** [jcubic/jquery.terminal#435]
dterm.js is a very good Dialog Terminal with Resize options. We planned to use this plugin for jquery-terminal dialog.
Could you please provide the react component for dterm.js with a placeholder(as a wrapper dialog) to put the terminal/div, since we already using the jquery-terminal as a react component.

**Comment by jcubic** [comment]
which react component you're using? if you use mine from Codpen then you just need to swap `.terminal(` with `.dterm(` and it should just work if some options or methods don't work I will need to update `dterm`. it was created just as an example.

One thing about dterm is that it require jQuery UI, if you just want dialog maybe you can use some ReactJS based dialog, so you will only have non-React jQuery and jQuery Terminal, but it will require additional work. dterm is very small and you can recreate the same functionality with any dialog library. I can came up with the code.

**Comment by amarendrar** [comment]
Thanks for the Dterm React component. I use the terminal in another react component  ex: dialog. This dialog is a combination of multiple react components like checkbox, input field, and jquery-terminal. I thought that I can use the dterm to replace my react dialog component.  As per the codepen demo, the dterm is tightly coupled with jquery-terminal. I will check dterm react component can be enhanced to use for multiple components.

**Comment by jcubic** [comment]
The dterm is integrated with jquery UI dialog, if you check the source code for dterm in summary it's just the same as:
```
$('<div><div></div></div>').find('div').terminal().parent().dialog();
```

not other code. besides hooking resize of the dialog with resize of the terminal.

So if you have react dialog just use it as is and put terminal component inside, but add `onResize` event.

**Comment by amarendrar** [comment]
Thanks for your example. I created a react component wrapper for Jquery-UI Dialog and passed the terminal component props from Dialog. So all the terminal related options are in terminal component only.

Hope this example can also be used to create a wrapper react components.
[TerminalDialog.tsx.txt](https://github.com/jcubic/jquery.terminal/files/2369725/TerminalDialog.tsx.txt)

**Comment by jcubic** [comment]
So you have working code? with what else can I help you with?

**Comment by amarendrar** [comment]
Thanks. I will close this issue.
