### ISSUE TITLE
Vi editor in jquery terminal

### ISSUE THREAD

**Issue by divyareddy12** [jcubic/jquery.terminal#437]
Is it possible to support vi editor like feature in jquery terminal.
Also can ANSI Escape codes be handled in the editor.

**Comment by jcubic** [comment]
jQuery Terminal is limited to only what's implemented in JavaScript, there my for for [jsvi](https://github.com/jcubic/jsvi) but it's very limited, also it don't handle ANSI escape codes.

But good news is that there is project that allow to run whatever can work with real TTY so you can run screen or tmux and even real emacs. The project is called  [xterm.js](https://xtermjs.org/)

**Comment by jcubic** [comment]
I've use jsvi in my [GIT Web Terminal](https://jcubic.github.io/git/) but it seems that it's broken right now, it shows "Maximum call stack size exceeded" when you try to open a file.

**Comment by jcubic** [comment]
You don't need to use websockets you can use ajax with pull in interval, I did something like this at work. We had two ajax calls one to send data and one to fetch new data from tty, but I don't know how it was created on a backend, but It will require to run a process with tty for each user.

**Comment by jcubic** [comment]
The only way to have vi in jQuery Terminal is using jsvi you can look how this works in my [GIT Web Terminal](https://jcubic.github.io/git/).
