### ISSUE TITLE
wrong link on website for min.css

### ISSUE THREAD

**Issue by solsticedhiver** [jcubic/jquery.terminal#438]
the link to jquery.terminal-1.23.2.min.css on **Download** page is wrong

It is https://raw.githubusercontent.com/jcubic/jquery.terminal/11.23.2/css/jquery.terminal-1.23.2.min.css

instead of https://raw.githubusercontent.com/jcubic/jquery.terminal/1.23.2/css/jquery.terminal-1.23.2.min.css

Note there is a **11** instead of **1** in the directory leading to the file

**Comment by jcubic** [comment]
Thanks, fixed.
