### ISSUE TITLE
Cursor up jump to top if terminal has verticall scroll bar.

### ISSUE THREAD

**Issue by sobimibos** [jcubic/jquery.terminal#446]
### Expected behavior

Cursor up key recalls last command, like it does if the terminal has no vertical scroll bar.

### Actual vertical behavior

If the terminal has a vertical scroll bar, cursor up does no recall last command, but window is scrolled to the top.

### Steps to reproduce

Can be reproduced with the demo https://terminal.jcubic.pl/#demo. Enter some command until the scoll bar appears. Then press cursor up.

### Browser and OS

Firefox 62.0 and Chrome 70.0.3538.102 on MacOS High Sierra.

**Comment by jcubic** [comment]
Thanks for the report, it seems that this is fixed in devel branch (got report on website chat and fixed) will release new version soon.

**Comment by sobimibos** [comment]
Thank you for the quick fix. I really appreciate the terminal.

**Comment by jcubic** [comment]
In version 2.0.1 released yesterday.
