### ISSUE TITLE
Virtual Keyboard event binding problem

### ISSUE THREAD

**Issue by kuzmanzs** [jcubic/jquery.terminal#448]
Hi I would like to use https://terminal.jcubic.pl/virtualKeyboard.html but if I press ENTER or TAB it does not do anything. According code, event should be send back to terminal, but it looks like somewhere it got broken.
Could you check it?

**Comment by jcubic** [comment]
The virtual keyboard demo was created because the library was not working on mobile, and I've did't tested very much. but I'll check why tab is not working.

**Comment by jcubic** [comment]
I've updated this old demo, new API require to invoke 3 events keydown keypress and keyup.

**Comment by kuzmanzs** [comment]
Thanks for the fix.
