### ISSUE TITLE
Calling echo with zero arguments prints undefined

### ISSUE THREAD

**Issue by BenHormann-Intergen** [jcubic/jquery.terminal#467]
### Expected behavior
`term.echo();` should result in output of one blank line.
### Actual behavior
`term.echo();` outputs a line with 'undefined'.
### Steps to reproduce
https://jsfiddle.net/pjn54s6f/1/embedded/js,result
### Browser and OS
Any. (Open the jsfiddle result in IE to highlight my issue with using `term.echo('');`).

**Comment by jcubic** [comment]
I think that it should just do nothing or just throw exception, you're echo nothing, it's definitely users error that should be ignored or user should be notified. I don't think that `echo()` and `echo('')` should act the same.

**Comment by jcubic** [comment]
I've decided that this is correct behavior, now if you echo undefined or empty string you will have single blank like. But if empty string left after extended command got removed and executed it will be ignored.

**Comment by BenHormann-Intergen** [comment]
I forgot to say `echo(undefined)` should still print `undefined`. Probably?
You'd have to check the length of arguments to differentiate the two.

**Comment by jcubic** [comment]
Updated the code it now prints `undefined` when using `echo(undefined)` as suggested I've used `arguments.length`

**Comment by BenHormann-Intergen** [comment]
Good job (and so quick!), thanks. Cool project, keep it up.

**Comment by jcubic** [comment]
In version 2.2.0
