### ISSUE TITLE
Browser hangs up when escaped brackets are echoed

### ISSUE THREAD

**Issue by paulsmirnov** [jcubic/jquery.terminal#470]
### Expected behavior

I expect to be able to output any text to the terminal. I understand that I might need to escape some special characters used for formatting, e.g. square brackets (is any helper method available?). In case I escape them, everything should work fine.

### Actual behavior

When I echo a text containing escaped brackets (e.g. `'a\\[i\\]=42'`), browser hangs up. Note that I have to escape them at least inside color formatting syntax (`[[b;white;red]text]`).

### Steps to reproduce

See this code pen: https://codepen.io/paulsmirnov/pen/ZPYavo
Uncomment the tagged line to experience the issue.

P.S. Note that you don't need to use formatting syntax to hang up, simple echo is enough: `term.echo(msg);`. I've just decided to show you a motivation behind escaping.

### Browser and OS

- Windows 10
- Google Chrome 72.0.3626.119 (Official Build) (64-bit)

**Comment by jcubic** [comment]
Thanks for the report. This is very bad event this don't work:

```javascript
term.echo('Display [[b;white;red]' + $.terminal.escape_brackets('a[i]=42') + '] and hang up!');
```

It don't hang locally when I tested but the output is totally broken also nested formatting give weird output and make this event worse.

**Comment by jcubic** [comment]
The problem was that unix formatter (from_ansi) was meta formatter (it had `__meta__ == true` marker) so it processed whole command not only between formatting like normal formatter.

This is changing how unix formatting works but I think it's fine. I don't think that it will break someones code and if it do he can add back `__meta__` marker.
