### ISSUE TITLE
terminal output wrapped unattractively when half width of the terminal window

### ISSUE THREAD

**Issue by liyingzh** [jcubic/jquery.terminal#471]
### I have question related to jQuery Terminal

Why terminal output wrapped unattractively when half width of the terminal window? 

![default](https://user-images.githubusercontent.com/9691351/53636777-4394e500-3c5c-11e9-8c8b-61e4575ad07f.PNG)

**Comment by jcubic** [comment]
It's because font is not monospace, did you've seen this when you visited the website? O did you modify the code somehow? On what Browser/OS did you seen this?

**Comment by liyingzh** [comment]
Yes, I see it when visit https://terminal.jcubic.pl/#demo and execute ```dir(term)```

**Comment by liyingzh** [comment]
Thanks to https://github.com/jcubic/jquery.terminal/pull/381

change to font-family: Consolas , soluted.

**Comment by jcubic** [comment]
I've tested Windows 7 and Chrome and it works, maybe you have some browser extension that change style. Or maybe your system or Chrome is broken. It work when I've tested.

You can check dev tools maybe font-family is strikethrough in css panel.

**Comment by liyingzh** [comment]
![image](https://user-images.githubusercontent.com/9691351/53705452-8a066180-3e5f-11e9-8bd0-640c7b1b0f08.png)

I checked dev tool,  ```font-family: "Droid Sans Mono", "Courier New", monospace;``` is strikethrough.
and I don't know why = =

An other error in console:
![image](https://user-images.githubusercontent.com/9691351/53705466-a30f1280-3e5f-11e9-9c5e-f882fea604d7.png)

**Comment by jcubic** [comment]
This should be ok, `"Droid Sans Mono"` style came from page layout that is overwritten by terminal css. Do you have extensions? Try incognito mode and guess account (first in 3 dots menu and second on user icon menu next to 3 dots).

**Comment by liyingzh** [comment]
There's one extension (Allow-Control-Allow-Origin: *) in my Chrome, and the incognito mode not work :(
![image](https://user-images.githubusercontent.com/9691351/53732366-b26e7a00-3eb8-11e9-9baf-34b0525dd7ad.PNG)

In addition, Firefox 63 font issue same as Chrome 72, but IE 11 is OK, all 3 browsers in my windows 7.

**Comment by jcubic** [comment]
That's very weird, can you do one more thing? Can you open developer tools change tab to network check disable cache and then refresh the page?

**Comment by liyingzh** [comment]
No, it's no use. :(

![image](https://user-images.githubusercontent.com/9691351/53773730-85f14700-3f26-11e9-8e17-e282f0d03940.PNG)

**Comment by liyingzh** [comment]
You are right, it's my system font problem, and https://www.cssfontstack.com/monospace shows bellow

![image](https://user-images.githubusercontent.com/9691351/53794105-3d5b7d00-3f6a-11e9-9ab1-86b52c3abd7e.png)

Thank you for the discussion!
