### ISSUE TITLE
promise.isResolved is not a function

### ISSUE THREAD

**Issue by jamesdesouza** [jcubic/jquery.terminal#481]
When I type a defined or undefined command, I get the error below:

> jquery.terminal.js:1384 Uncaught TypeError: promise.isResolved is not a function
>     at Object.ENTER (jquery.terminal.js:1384)
>     at HTMLHtmlElement.keydown_event (jquery.terminal.js:2817)
>     at HTMLHtmlElement.dispatch (jquery-3.3.1.min.js:2)
>     at HTMLHtmlElement.y.handle (jquery-3.3.1.min.js:2)

This is the reproduced error
https://codepen.io/anon/pen/jRMbjB?editors=0010#0

**Comment by jamesdesouza** [comment]
Hmm, I used latest-cdn version. Apparently that cause the problem!
I tried downgrade to version 2.2.0 and it works perfectly normal...

**Comment by jcubic** [comment]
It suppose to be fix to #474 that was working only with old jQuery, that function was removed.

**Comment by jcubic** [comment]
Direct error is fixed, but issue #474 that introduced this error still need more work.
