### ISSUE TITLE
Allow custom "word" splits

### ISSUE THREAD

**Issue by drosenbauer** [jcubic/jquery.terminal#489]
Completion currently takes a "word" boolean indicating whether the whole string or just the current word should be completed. The current code always assume that words are divided by spaces. However, in my case, I am completing small snippets of code, so the current "word" may not be separated from the remainder of the code by a space.

I've been handling this by modifying the word split to use the regex `/[^A-Za-z0-9_\"\'\$]/` instead, which allows space-oriented words but also allows words divided by other non-text characters.

Allowing a custom autocompleteWordRegex as a configuration setting might be useful here.

**Comment by drosenbauer** [comment]
Alternatively, allowing me to specify what position in the string I want the replacement done would also solve my problem.

**Comment by jcubic** [comment]
I had the same in my LIPS project (lisp in javascript), just use whole string and split it and append to the beginning of the string of each word you're completing. Check how I've done something like this:

```javascript
        completionEscape: false,
        wordAutocomplete: false, // this will complete whole string
        doubleTab: function(string, maches, echo_command) {
            echo_command();
            // this will echo only function names
            this.echo(maches.map(command => {
                return lips.tokenize(command).pop();
            }));
        },
        completion: function(string) {
            // parse whole string before cursor
            let tokens = lips.tokenize(this.before_cursor(), true);
            tokens = tokens.map(token => token.token);
            const last = tokens.pop();
            if (last.trim().length) {
                const globals = Object.getOwnPropertyNames(window);
                // whole code before word - in your case it would be your before split
                const prefix = tokens.join('');
                const re = new RegExp('^' + $.terminal.escape_regex(last));
                // get list of function names to complete
                var commands = env.get('env')(env).toArray().concat(globals).filter(name => {
                    return re.test(name);
                }).map(name => prefix + name); // append prefix to names
                // it don't return instanceof Array that is check by jQuery Terminal when using
                // iframes before version 2.4.2
                return Array.from(commands);
            }
        },
```

whole terminal code is here: https://github.com/jcubic/lips/blob/master/examples/terminal.js and you can see it here https://jcubic.github.io/lips/

**Comment by jcubic** [comment]
The word complete is just convenient default and more advanced is whole string, so you need to parse it and handle on your own. It's the same like with interpreter. Convenient is object or string where parsing is done for you and more advanced is whole string where you need to do the parsing.

**Comment by drosenbauer** [comment]
Ah I understand. I had missed the existence of `doubleTab` previously! 

So to clarify what's going on here to make sure I understand:

1. The completion handler is invoked when the user presses tab. It returns a set of candidates for the entire string up to the cursor. 
2. If the user presses double-tab instead, the results of the completion are passed to doubleTab for filtering. In your case, you extract the final token.

Is `doubleTab` still invoked properly if `completion` is done via ajax / callback?

What does the `echo_command()` do in your doubleTab?

**Comment by jcubic** [comment]
> Is doubleTab still invoked properly if completion is done via ajax / callback?
never tested it should, let me check

> What does the echo_command() do in your doubleTab?
echo_command function just echo your last command before the tab (just look how linux command line do that, if you have just in case you may don't want that got echo.For instance right now I'm not sure if I want to duplicate whole code I'm timing again and maybe I only want final token (the list of function names). Maybe there would be better to just have option switch to turn off `echo_command`.
```
kuba@jcubic:~/projects/jcubic/www/blog/repo/img$ le
lecs         lein         less         lesskey      let          lex
lefty        les          lessecho     lesspipe.sh  letsencrypt  lexgrog
kuba@jcubic:~/projects/jcubic/www/blog/repo/img$ le
```
I've typed le then press tab twice original le is before all words, jQuery Terminal will do the same if you call `echo_command()` single function you don't need to care about arguments. As I'm now thinking this should be an option. Maybe I add and it will call echo by default.

**Comment by jcubic** [comment]
Sorry, I've forgot to check the `doubleTab`. if you didn't test it yourself. it work with async completion. You can return promise that resolve to array or call callback function but in new code it's better to use promises it will also use with native Promise object (because they are easier also if you use use ajax you can return call to fetch).

**Comment by jcubic** [comment]
I've also added option `doubleTabEchoCommand` which is set to false so it's not breaking change. There is already `echoCommand` option (it's for all commands) need more testing how those two options will work together.
