### ISSUE TITLE
Hitting any keys after pasting the content will clear the content

### ISSUE THREAD

**Issue by phuc** [jcubic/jquery.terminal#493]
### Expected behavior
Pasted content needs to be retained
### Actual behavior
It clears all the content
### Steps to reproduce
1. Copy some text
2. Go to the demo at https://terminal.jcubic.pl/#demo
3. Paste the text
4. Hit spacebar
5. All content is clear
### Browser and OS
1. Browse: Chrome version 74.0.3729.157 (Official Build) (64-bit)
2. OS: MacOS version 10.12.6

**Comment by jcubic** [comment]
It works on Linux Chromium. Will check on Browserstack in fe days. Can you reproduce on other OS/Browser?

**Comment by phuc** [comment]
I tried with Chrome on Windows 10 and Ubuntu 16. Both are working fine. It seems like it's only broken in Chrome on Mac.

**Comment by jcubic** [comment]
The fix got released in [version 2.5.2](https://github.com/jcubic/jquery.terminal/releases/tag/2.5.2)
