### ISSUE TITLE
Commands exporting

### ISSUE THREAD

**Issue by Sravs66** [jcubic/jquery.terminal#498]
Hi there,
is there any way to export all the executed commands..?
I need only executed commands to be exported to some file, not the state.

**Comment by jcubic** [comment]
You can use code like this:
```javascript
var commands = [];
$('body').terminal(function() {}, {
    onAfterCommand: function(command) {
        commands.push(command);
    }
});
```

the same will work in `onBeforeCommand` but with this you can prevent evaluation of the command and probably you will also get command that throw exception.

**Comment by Sravs66** [comment]
But in this, we can get only commands right,,,!
I want the responses of those commands also. Sorry, I missed that point in the previous question.

**Comment by jcubic** [comment]
In this case use:

```javascript
term.get_output();
```

it's list of lines that get echoed into terminal (each echo command will include prompt like on terminal).

the only issue you may have is when user use clear, you will lost the output so for this you need:
```javascript
var safe_output = [];

$('....').terminal({
   clear: function() {
      safe_output = safe_output.concat(this.get_output());
      this.clear();
   }
}, {
  clear: false
});
```
 
and to get real output without worry about clear you can use:

```javascript
safe_output.concat(term.get_output());
```
