### ISSUE TITLE
Setting output lines limit

### ISSUE THREAD

**Issue by Sravs66** [jcubic/jquery.terminal#500]
### I have question related to jQuery Terminal

Hello there,
 I have a scenario where there will be one rest call calling and it will continuously gives some response which will be echoed on the terminal. I have to limit the number of lines after i receive the response from that rest call...i checked with outputLimit. but i observed its applicable when user manually enters some commands. And the thing is i have to roll over on the messages. 
like suppose if terminal reached the 200 lines,and my next rest calls gives 20 lines more response then i should delete 1 to 20 lines from the above 200 lines and append latest 20 lines.

So just curious to know is there any possibility for this now in jQuery plugin, and any setOutputLimit method available...?

**Comment by jcubic** [comment]
Not sure if I've understand.

You have 2 cases:
1. 100 lines
2. 200 lines

and you want to set the limit before calling rest call with 100 or 200 so if rest return 20 you will get 100 - 20 or 200 - 20 lines on original output?

Or just want always 200 as limit?

You should be av\ble to use both but for first case you will need to use some jQuery to get number of lines (because terminal return only all lines that was ever produced, from last clear call).

to set the limit you should be able to use

```javascript
term.option('outputLimit', 200);
// or:
term.settings().outputLimit = 200;
```

to find numer of lines you should be able to use:
```javascript
var count = term.find('.terminal-output [data-index] div').length;
```

**Comment by Sravs66** [comment]
Hi jCubic,
let me be more clear...

1. First, one rest call will be called and i got 50 lines of data/response. And i printed those lines on terminal.(1 to 50)
2. Second rest call got called and received, lets say 30 lines of data/response(51 to 80)
3. And like that so many calls will be there where response is keep on including in the console.

My requirement is i have to limit the terminal to display only latest 60 lines( always it should be latest 60 lines ) of data [ 21 to 80 ]
From the above 2 points, 50 + 30 = 80 total lines. But i want to display (50-20(1 to 20 lines))+30.

**Comment by jcubic** [comment]
You you were saying that `outputLimit: 60` option don't work? You don't have last 60 lines?

**Comment by Sravs66** [comment]
It will work if i manually executing the commands. But my problem is i will get the response from backend mean to say from the rest call.....But now u have suggested me right...by using that i'm able to set the limit.
term.option('outputLimit', 200);
// or:
term.settings().outputLimit = 200;

**Comment by jcubic** [comment]
I should not matter from where outpu came from, the limit is on echo function and on lines not on commands you type.

so if you use: 
```javascript
$('body').terminal({}, {outputLimit: 60});
```

then what ever you do to generate output you should only have 60 lines max.

**Comment by Sravs66** [comment]
Hi jCubic, these outputLimit considers latest commands is that true..?
I mean to ask,
if i set outputLimit to 6.,
Steps:
1. test1 command which returned 7 lines of response
2. test2 command with 8 lines of response

so now totally 15 lines on console. But outputLimit is 7 so its should display the response from test2 command.

Is this correct with outputLimit ...?

**Comment by jcubic** [comment]
Limit is for output so if test2 command show 8 lines and limit is 7 it will not show whole command test2 and you will see only text from last 7 lines of test2.

**Comment by Sravs66** [comment]
Got it...thank you
