### ISSUE TITLE
underscore not displayed correctly

### ISSUE THREAD

**Issue by solsticedhiver** [jcubic/jquery.terminal#501]
I found out that underscore in not displayed at all in my jquery terminal

But that is in a very rare situation. One have to use `--size: 1.2`. Even the logo, is messed up.

You could try that jsfiddle: https://jsfiddle.net/jLyvkmta/1/

- type `echo test_test`, and you will not get underscore in the response
- type `test_underscore`, and the command echoed back will not have underscore either.

for --size 1.4 this happens once you have displayed a certain number of underscore, then it fails

**Comment by jcubic** [comment]
I was having the same problem and I just didn't use certain sizes at all, just wanted to write that this is bug in browsers but I think I fixed this. Adding `1px` to `line-height` solved the issue.

https://jsfiddle.net/pwq4s9f8/

**Comment by solsticedhiver** [comment]
Ok. thanks
