### ISSUE TITLE
echo string with double bracket `[[  ]]` trigger execute another command

### ISSUE THREAD

**Issue by jdxin0** [jcubic/jquery.terminal#508]
### Expected behavior
echo string with special characters
```
let result = '[[ ls ]]';
term.echo(result);
```
display result

### Actual behavior
execute another command `ls`

**Comment by jcubic** [comment]
This is not a bug but a feature, it's called extended commands and it's used to execute different commands from server. You can also fully control the terminal without any JS code.

To disable this feature you only need to escape the brackets, best is to use html entities.

**Comment by jcubic** [comment]
It's documented here https://terminal.jcubic.pl/api_reference.php#echo added in version `0.9.0`.
