### ISSUE TITLE
 after paste in terminal and then input any world will be double

### ISSUE THREAD

**Issue by MiniShen** [jcubic/jquery.terminal#509]
1 .copy content:hello
2.input one wold A
error result: hello AA
example:
command> hello AA

**Comment by MiniShen** [comment]
1 .copy content:hello
2.paste content
3.input one word: A
error result: hello AA
example:
command> hello AA

**Comment by jcubic** [comment]
@MiniShen what version of jQuery Terminal you're using and on what OS browser you see the issue.

**Comment by MiniShen** [comment]
Terminal version: 1.6.2      OS: windows       browser:google

**Comment by MiniShen** [comment]
the latest version is perferct! thanks!
