### ISSUE TITLE
Can a formatter be applied only to input and not output?

### ISSUE THREAD

**Issue by drosenbauer** [jcubic/jquery.terminal#518]
### I have question related to jQuery Terminal

I am trying out your PrismJS demo extension and it's working beautifully. However, it's also applying the PrismJS formatting to the terminal output, which is not what I want. I see that your `trypython` version does the same, such as highlighting the word "not in" when they appear in an error message.

Is there a straightforward way I can apply a formatter only to input lines and not output lines? How does the formatter decide which lines to format?

**Comment by jcubic** [comment]
You can disable applying of formatting when using echo:
```javascript
$.terminal.active().echo('for i in range(10):\n   print(i)', {formatters: false})
```
you can try this in console of trypython.
