### ISSUE TITLE
Login as root

### ISSUE THREAD

**Issue by o-ayoub** [jcubic/jquery.terminal#520]
### I have question related to jQuery Terminal

1) is there any way to log in as a root user ?
2) is it possible to run some commands without enter sudo ?

**Comment by jcubic** [comment]
You decide if someone login as root, jQuery Terminal only send user/password and get token, then you can verify that token when you send data to server. There is no something like sudo or root, you have this on server, jQuery Terminal is front-end library it know nothing about any of this.

**Comment by o-ayoub** [comment]
@jcubic thank you for clarification, i want to make an auto authentication, when the page is loaded send username and password to server and get login.
Thank you

**Comment by jcubic** [comment]
You need to check on the server if user is root. If you create token that will verify that the user is root, you will have root user.

Can you share your code and show what exactly you want to do?

**Comment by o-ayoub** [comment]
Thank you so much for reply
My idea: I want to make direct login without prompt user to enter login & password;

**Comment by jcubic** [comment]
Then why you need login? Don't use it then. Login function in jQuery terminal is so for typing user and password, you don't want users to type password don't use login.
