### ISSUE TITLE
Execute Shell Script.

### ISSUE THREAD

**Issue by o-ayoub** [jcubic/jquery.terminal#521]
### I have question related to jQuery Terminal
Hello, 
I have a shell script, it s about a menu like this:
1- List Student
2- List Teacher 
3- Exit
So user can enter a number 1 or 2 or 3. 

Actually when I do sh script.sh it does not give any thing. So please how can I make connection between webconsole and shell script results?

Thanks

**Comment by jcubic** [comment]
You can't run shell script with menu from jQuery Terminal. It's not tty. It need to have actual response. With jQuery Terminal you would need to write menu in JavaScript and ask for input in JS. Try [xterm.js](https://xtermjs.org/) that is real tty.

**Comment by o-ayoub** [comment]
Thank you very much. I really appreciate that. :)
