### ISSUE TITLE
i use require.js to include the needed file jquery jquery.terminal-2.8.0.min.js jquery.mousewheel-min.js to some page but when i view the page it tell me need wcwidth.js  

### ISSUE THREAD

**Issue by Destiny-1** [jcubic/jquery.terminal#542]

**Comment by Destiny-1** [comment]
when i serach wcwidth i found that in  jquery.terminal-2.8.0.min.js  whether the jquery.terminal-2.8.0.min.js grammar conflict with the require.js

**Comment by Destiny-1** [comment]
![image](https://user-images.githubusercontent.com/37127850/69298296-60d56d80-0c48-11ea-8029-5a3491a2f6c7.png)

**Comment by Destiny-1** [comment]
![image](https://user-images.githubusercontent.com/37127850/69298347-8498b380-0c48-11ea-98f8-65b532352790.png)

**Comment by jcubic** [comment]
If you use requirejs you need to have wcwidth because its dependency. I should document it.

**Comment by jcubic** [comment]
Do you have actual, real code I can test? If you copied the files you need to get wcwidth as well, jQuery.Terminal don't have jQuery as well. Both jQuery and wcwidth are dependencies you need to download them if you don't use npm but directory with files and you've downloaded.

**Comment by Destiny-1** [comment]
> I should document it

ok, thank you i will try

**Comment by Destiny-1** [comment]
> Do you have actual, real code I can test? If you copied the files you need to get wcwidth as well, jQuery.Terminal don't have jQuery as well. Both jQuery and wcwidth are dependencies you need to download them if you don't use npm but directory with files and you've downloaded.

i am sorry i can not give you real code ,by the way thank you so much to answer my question i will  download wcwidth to try
