### ISSUE TITLE
Updating a line with nested formatting ignores inner format

### ISSUE THREAD

**Issue by taikuukaits** [jcubic/jquery.terminal#543]
### Expected behavior

Updating a line with nested formatting should respect and display the nested format.

### Actual behavior

The inner format text is shown on the terminal. The inner format does not work.

### Steps to reproduce

I've reproduced in the forked codepen, all you have to do is this:

{code}
var nestedFormat = "[[b;;] bold [[;green;] green]]";
term.echo("works: " + nestedFormat);
term.echo("broke: " + nestedFormat);
term.update(-1, "broke: " + nestedFormat);
{code}

The works line is what I expect, but you can see the behavior in the broke line. 

https://codepen.io/taikuukaits/pen/QWWPEWQ

### Browser and OS

Chrome and Windows

I didn't see any similar issues and not sure if I am doing something wrong. Any help would be appreciated. Thanks!

**Comment by jcubic** [comment]
Issue fixed in devel branch, it will be in next version. Thanks for the report good finding.

**Comment by jcubic** [comment]
Forget to add the fix is in 2.9.0 and your codepen is working now.
