### ISSUE TITLE
Implement different ANSI charsets modes

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#558]
### I have idea for a new feature for jQuery Terminal

Continuation of #553 

It would be nice to have ESC ( 0 to enable graphic mode.

**Comment by jcubic** [comment]
@jerch moving discussion here;

Check this https://github.com/microsoft/terminal/issues/169

it seems that xterm.js have wrong charset for "0", it have \n and \t instead of characters that show what this control character do.

**Comment by jerch** [comment]
Eww, thx for testing and finding bugs :+1: Created an issue --> https://github.com/xtermjs/xterm.js/issues/2678
