### ISSUE TITLE
Fake memory filesystem (cd/ls commands)

### ISSUE THREAD

**Issue by matronator** [jcubic/jquery.terminal#559]
Hi, not sure if this is the right place, but it is related to this plugin and specifically [one of the examples.](https://codepen.io/jcubic/pen/WZvYGj) I'm trying to create a fake filesystem/directory structure to emulate a filesystem with cd/ls/cat commands available. At first I had this really convoluted JSON structure, but then I noticed that the [Unix/MacOS Resizable Terminal](https://codepen.io/jcubic/pen/WZvYGj) example uses a much simpler and better way to structure the data.

However, I'm having some trouble making it work with deeper layered folders. The example works great, but only with 2 "depth" levels: root folder and projects folder.

```javascript
var fs = {
    children: {
        'projects': {
            children: {
                'baz.txt': {
                    path: './projects/baz.txt',
                    content: 'Hello this is file baz.txt'
                },
                'quux.txt': {
                    path: './projects/quux.txt',
                    content: "Lorem Ispum (quux.txt)"
                }
            }
        },
        'foo.txt': {
            path: './foo.txt',
            content: "Hello, World!"
        },
        'bar.txt': {
            path: './bar.txt',
            content: "Wellcome to the bar"
        }
    }
};
```

When I use the same functions on a deeper layered structure like this:

<details>
<summary>Expand</summary>

```javascript
var fs = {
  children: {
    'projects': {
      children: {
        'music': {
          children: {
            'IDKLOL.mp3': {
              path: './projects/music/IDKLOL.mp3',
              content: 'Hello this is file baz.txt',
	      type: 'audio'
            },
            'matecak.m4a': {
              path: './projects/music/matecak.m4a',
              content: 'Lorem Ispum (quux.txt)',
	      type: 'audio'
            }
          }
        },
        'visual': {
          children: {
            'bigart.jpg': {
              path: './projects/visual/bigart.jpg',
              content: 'Hello this is file baz.txt',
	      type: 'image'
            },
            'design.jpg': {
              path: './projects/visual/design.jpg',
              content: 'Hello this is another file baz.txt',
              type: 'image'
            }
          }
        },
        'tech': {
          children: {
            'bitcoingo.io.md': {
              path: './projects/tech/bitcoingo.io.md',
              content: '...',
	      type: 'markdown'
            }
          }
        }
      }
    },
    'about.txt': {
      path: './about.txt',
      content: 'Hello, World!',
      type: 'text'
    },
    'contact.txt': {
      path: './contact.txt',
      content: 'Wellcome to the bar',
      type: 'text'
    }
  }
};
```

</details>

It starts throwing errors when traversing up the tree from the deepest folder (with `cd ..`):

```
[USER]: undefined is not an object (evaluating 'fs[dir_name].children')
```

And I'm not sure if there's a problem with how the data is structured (I tried adding path to the folders as well, but that causes it to mistake it for file) or if the problem is in the cd function itself. Looking at the function, there's some slicing of the path which, I think, happens only once?

Is there some easy way to modify the function to work with multiple levels of data? Or do I just have the data structured badly?

<details>
<summary>Relevant parts of the function</summary>

```javascript
var path = [];
var cwd = fs;
function restore_cwd(fs, path) {
  path = path.slice();
  while (path.length) {
    var dir_name = path.shift();
    if (!fs[dir_name].children) {
      throw new Error('Internal Error Invalid directory ' +
        $.terminal.escape_brackets(dir_name));
    }
    fs = fs[dir_name];
  }
  return fs;
}

[...]

cd: function (dir) {
  if (dir === '/') {
    path = [];
    cwd = restore_cwd(fs, path);
  } else if (dir === '..') {
    if (path.length) {
      path.pop(); // remove from end
      cwd = restore_cwd(fs, path);
    }
  } else if (!is_dir(cwd.children[dir])) {
    this.error($.terminal.escape_brackets(dir) + ' is not a directory');
  } else {
    cwd = cwd.children[dir];
    path.push(dir);
  }
}, [...]

[...] else if (cmd.name === 'cd') {
    var dirs = Object.keys(cwd.children).filter(function (key) {
      return is_dir(cwd.children[key]);
    });
    callback(dirs);
[...]
```

</details>

**Comment by jcubic** [comment]
I've update the codepen demo, simplified the fs now it's just plain object directory is object and file is string. Also update completion you can cd complete path `cd pro <TAB> ter <TAB> f <TAB>` and completing will complete `project/terminal/foo`.

PS: I've send an email while a ago maybe it went into spam folder.

**Comment by matronator** [comment]
Awesome! Thank you very much! :)
