### ISSUE TITLE
tab focus going to previous commands hyperlinks

### ISSUE THREAD

**Issue by Sravs66** [jcubic/jquery.terminal#566]
### I have question related to jQuery Terminal

Hi @jcubic ,
I have implemented tab completion in my code. But sometimes when i have hyperlinks in executed command response, and trying to press tab (just empty tab), focus is going back to the hyperlinks of previously executed command and then calling the rest call with empty command.
Here my problem is when i execute the empty tab it should call only the given rest call, but focus should not highlight. 
can you suggest your ideas please...?

**Comment by jcubic** [comment]
Can you show example, maybe codepen demo or something online with exact steps.

Here is I have basic terminal with latest version https://codepen.io/pen?template=MbVMwO
press enter add link and when I press tab it never add focus to link.

**Comment by Sravs66** [comment]
HI Jakub,
https://codepen.io/sravs66/pen/GRpRrWQ,

if you observe at the above code pen,  after executing tab for like 7 to 8 times, i'm clicking on the terminal and trying to give tab , then you can see that scrollbar is going up but focus is not highlighting.
For me in my code , its going up and highlighting the link also.

**Comment by jcubic** [comment]
I think you break the TAB key when you return true, why you want to do that if you return true it's probably just returned true in terminal and it call default action by the browser. In Terminal if browser all all keys are prevented they default accounts like tab to change links.

If you want completion don't use TAB key there is built in functionality, just use `completion` options that can be array or function that return array or promise of array or call callback (I think it still work).

**Comment by jcubic** [comment]
Better solution if you want to overite default TAB is to use keymap (it's simpler):

https://codepen.io/jcubic/pen/bGVGgNK

or if you really want keydown, return false so it prevent default browser action.

**Comment by Sravs66** [comment]
return false  helped.
Thank you.
