### ISSUE TITLE
terminal widget is still using v1.7.2

### ISSUE THREAD

**Issue by belm0** [jcubic/jquery.terminal#568]
https://github.com/jcubic/jquery.terminal/blob/19fb6bc99c021f09b74d83b82e2aea823c94ad8b/js/terminal.widget.js#L30

**Comment by jcubic** [comment]
Thanks for the note, I don't actually use it. Will update, maybe add to my build system.

Do you use this widget?

**Comment by belm0** [comment]
> Do you use this widget?

I used it for just early steps after finding it in the examples, but then switched to direct importing of jquery.

**Comment by jcubic** [comment]
The version is updated, I forget to build the file when version change in Makefile.
