### ISSUE TITLE
Page with multiple terminals scrolls to focused terminal - how to remain at the top?

### ISSUE THREAD

**Issue by stupid-genius** [jcubic/jquery.terminal#571]
### I have question related to jQuery Terminal

I have a page with multiple terminals and upon loading, it scrolls to the terminal with focus.  None of the terminals are at the top of the page which results in the page beginning not at the top.  What is a simple way to avoid this and have the page positioned at the top when first loaded?

I thought of various approaches such as disabling all terminals, and then requiring a click or something to enable them, but that is a very clunky design.  Is there perhaps a way to disable scrolling to the focused terminal?

**Comment by jcubic** [comment]
You need to disable the terminals, by default they are enabled and focus/jump to terminal.
Option:
```
enabled: false,
```
This is how multiple terminals are used on the website.

**Comment by stupid-genius** [comment]
Thanks.  Do you have a suggestion for an easy way to re-enable them onclick?  I could wire each up individually, of course.  Does jquery terminal have a mechanism to manage this?
