### ISSUE TITLE
Focusing on mobile can cause terminal to jump to top

### ISSUE THREAD

**Issue by craig-feldman** [jcubic/jquery.terminal#572]
### Issue summary
When focusing on the terminal using a mobile device, the terminal often jumps to the top and the prompt is thus no longer visible.
### Expected behavior
Focusing should make the terminal scroll to the bottom or alternatively maintain the position.
### Actual behavior
Focusing causes the terminal to jump to top.
### Steps to reproduce

1. Go to https://terminal.jcubic.pl/#demo on a mobile, or using chrome dev tools and mobile mode.
2. Enter some new lines in the demo terminal, such that scroll is required (i.e. the greeting is no longer visible).
3. Tap on the terminal to focus (on mobile this should bring up the keyboard).
4. Notice that the terminal has scrolled to the top (the initial greeting is present).

NOTE: I suspect this may have something to do with caching. I have encountered odd behaviour where on first load, the terminal does indeed scroll to the bottom. However, when I refresh the page and follow the above steps again, it now jumps to the top on focus.

### Browser and OS
Mac OsX chrome in mobile mode and Android using Chrome and Samsung Internet.

v 2.16.0

**Comment by jcubic** [comment]
Thanks for the report, I've recently fixed jumping issue on desktop, but didn't check how it work on mobile. Will investigate. Mobile version have different way of handling paste that also make virtual keyboard works (desktop use textarea and mobile use content editable element).

**Comment by jcubic** [comment]
Ok this is different issue then jumping on desktop because it's inside terminal. On desktop it was scrolling whole page.

**Comment by jcubic** [comment]
Issue is fixed on devel it will be released in next version. Probably 2.17.3
