### ISSUE TITLE
CTRL + L jumps to url bar in chrome and firefox

### ISSUE THREAD

**Issue by septatrix** [jcubic/jquery.terminal#587]
### Issue summary
When pressing <kbd>CTRL</kbd>+<kbd>L</kbd> to clear the terminal the cursor jumps to the url bar do to a missing `preventDefault` in the event listener (probably)

### Expected behavior
The terminal gets cleared and the cursor stays put

### Actual behavior
The terminal gets cleared but the cursor jumps to the url bar

### Steps to reproduce
Press <kbd>CTRL</kbd>+<kbd>L</kbd> in a terminal on e.g. the demo page

### Browser and OS
* Chromium 83.0.4103.97
* Firefox 77.0.1
* Ubuntu 20.04

**Comment by jcubic** [comment]
Issue fixed on devel branch it will be released in next bug fix version 2.17.3.
