### ISSUE TITLE
False "Recursive loop..." error

### ISSUE THREAD

**Issue by PhoenixVioleus** [jcubic/jquery.terminal#593]
### Issue summary

When printing (echo/less) via server-side invocation, output that mirrors that of the previous command throws an error:
Recursive loop in echo detected, skip

### Expected behavior
Output should print error-free after both submissions

### Actual behavior
The second submission prints only  an error message

### Steps to reproduce
Client-side:
```
$(function() {
    $('body').terminal(function(command) {
        return $.post('script.php', {command: command});
    }, {
        invokeMethods: true
    });
});
```
Server-side (script.php):
```
<?php
echo '[[ terminal::less("Testing...") ]]';
```

**Comment by jcubic** [comment]
Those recursive guard is pretty [flaky](https://tinyurl.com/ybenb28r), maye I should remove it, and if create recursive loop it will be user problem. Will check if I can fix this without removing this check and if not I will just remove it.

Thanks for the report.

**Comment by PhoenixVioleus** [comment]
No problem and thanks for the terminal!

**Comment by jcubic** [comment]
The issue is fixed, it should never give false positives when detecting recursive calls.
