### ISSUE TITLE
Completion doesn't honor results returned from the completion callback

### ISSUE THREAD

**Issue by ovk** [jcubic/jquery.terminal#595]
### Issue summary
As per documentation, terminal provides a completion option:

```
completion [function (string, callback)|array|boolean] — function with a callback that need to be executed with list of commands for tab completion 
```

I tried that option in a form of function that receives a string and callback, to work around terminal's completion limitation of not supporting commands delimited by parenthesis.

For example, consider two commands available: `foo` and `bar`. If the user types `foo(ba` and presses tab, I expect `ba` token to be completed to `bar` (you can imagine the resulting expression to be a function call like `foo(bar)`). Unfortunately, this doesn't work if completion is an array of `[ 'foo', 'bar' ]` as it looks like the terminal only completes space delimited arguments. So I implemented completion as a function instead, where I tokenize the string myself and return all options relevant to the current input. So, for example, if the user typed `foo(ba` the callback will receive an array `[ 'bar' ]` as this is the only valid completion option.

### Expected behavior
I expected that the terminal would take the completion array passed to the callback and suggest it to the user.

### Actual behavior
Nothing happens, seems like there is some additional processing that prevents terminal from showing provided completion suggestions.

**Comment by jcubic** [comment]
This is not a bug, to have completion like this you need two things first disable escaping (it need documentation) and then you need to process whole command for completion, I have function/variable name completion in LIPS project (it's lips language and it have lot of parenthesis), you can check how it's created.

You can see how it works here https://jcubic.github.io/lips/
and the code (latest one is in devel branch) https://github.com/jcubic/lips/blob/devel/examples/terminal.js

I need lot of updates to documentation, including line completion where you can complete part of the word.

**Comment by jcubic** [comment]
To see that whole line completion works fine you can type `(let ((x 10)) (be` and press tab it will complete word `begin`.

**Comment by ovk** [comment]
Thank you for the explanation, the example you referenced seems like exactly what I need.

*Leaving the issue open in case you want to use it to track the documentation update. Feel free to close it otherwise.*

**Comment by jcubic** [comment]
I've updated Wiki page https://github.com/jcubic/jquery.terminal/wiki/Tab-completion
