### ISSUE TITLE
support recursive autocomplete

### ISSUE THREAD

**Issue by talrubin** [jcubic/jquery.terminal#599]
### I have idea for a new feature for jQuery Terminal

When user press TAB for autocomplete for this current directory, after pressing '/' we will run function to calculate the next folder sub-directories / files and TAB will present the new data for this folder.
If the user removes the '/' from the command-line, reverse the auto-compete to the previous array of the current folder data.

**Comment by jcubic** [comment]
It will be hard to do on top of the terminal, you will never know if user typed whole command by hand or using completion, deleting "/" and removing everything to previous slash may be confusing.

But of course you can implement your own tab completion that will work just like you want. There are two API functions `.complete()` and `.before_cursor()` that you can use and change TAB keymap to implement your own completion. You will also need to add keydown and implement backspace.

**Comment by talrubin** [comment]
I added keybinding to `/`, and when the user press `/` I calculate the next folder content and add it to the `completion` array concatenated with the current path(for example: if I am in `/var` and I have all it content, and I chose to auto-complete the folder `foo`, then the user press `/`, I calculate all `/var/foo/` content and add it like: `/var/foo/NEW_CONTENT` to the `completion` array, now it contain all `/var` and `/var/foo` content). You can add another array that responsible only for the next auto-complete, and when the user press `/` it call to function to calculate it and change it value.

**Comment by jcubic** [comment]
This is something very non standard, do you have any example application that work like this? If you want to modify the the next completion you can just add something like this:
```
var completion = [];
keymap: {
  '/': function() {
       // modify completion array
  }
},
completion: function() {
   return completion;
}
```

you don't need any extra code in the library to modify next completion after you press `/`.

**Comment by D3Ve1inE** [comment]
Yes this is a great idea!

I implemented this just as @jcubic suggested, but the problem is that the autocomplete now expects files in sub-directories to start with the directory name.
For example, if i have a file named "exFile" in a folder named "exDir" I'd have to add it to the autocomplete array as "exDir/exFile" instead of just "exFile".

Basically I'm trying to simulate how auto completion in a real terminal would work and this is obviously one of the things any terminal would do.

**Comment by talrubin** [comment]
Yes, this is exactly what I did, but if you start writing the first folder (for example: `foo`) and press `/` and your function modified the `completion` array, the TAB doesn't auto-complete the next folder content because the new `completion` not start with `foo/`...

**Comment by jcubic** [comment]
When I have time I will create example, you just need to modify the completion so the array have foo in front, not just push the value to the array.

**Comment by jcubic** [comment]
The other solution is to write everything in completion function and parse what user typed, see how this works in my GIT Web Terminal. where cd complete the whole directory structure.

https://github.com/jcubic/git/blob/gh-pages/js/main.js#L1381

**Comment by jcubic** [comment]
You can test completion in GIT Web Terminal at https://jcubic.github.io/git/

type:
```
git clone https://github.com/jcubic/jquery.terminal.git
```
and try cd "jqu" TAB ".g" TAB
