### ISSUE TITLE
Clearing old lines to avoid overloading of browser

### ISSUE THREAD

**Issue by ultramoo** [jcubic/jquery.terminal#625]
### I have question related to jQuery Terminal

Sometimes the output into jQuery Terminal may contain a lot of log data. After a while this overwhelms the browser and freezes it.
I was wondering if there was a way to clear old lines (eg 500 inputs old) to avoid this?

**Comment by jcubic** [comment]
You can limit the output lines with [outputLimit option](https://terminal.jcubic.pl/api_reference.php#outputlimit).
