### ISSUE TITLE
CTRL+D moves prompt  down one line

### ISSUE THREAD

**Issue by septatrix** [jcubic/jquery.terminal#626]
### Issue summary

<kbd>CTLR</kbd>+<kbd>D</kbd> is mostly used to signal EOF and exit the terminal (or restart it).
Using the shortcut (on the demo page) leads to the terminal being cleared but prompt still jumps down a single line.

### Expected behavior

Pressing the shortcut should either
* terminate the terminal (cease further actions and ignore input) or
* clear the whole terminal and put the cursor on the first line or
* not clear the terminal and just continue on the next line with a fresh prompt (similar to what `while true; do bash; done` would give).

The last or second to last option would probably be prefered if `exit` is set to `false` during terminal initialization.

### Actual behavior

The whole terminal is cleared but the new prompt appears on the next line irregardless or where it was before. If e.g. you press the shortcut while the prompt is currently in the third line everything gets cleared and the next prompt get displayed on line 4.

### Steps to reproduce

Go to the demo page and press the shortcut multiple times --- the prompt will seemingly move down.

### Browser and OS

* Chromium 85
* Ubuntu 20.04.

**Comment by jcubic** [comment]
I'm looking at the code and if there are no login it just call:
```
self.resume();
self.echo('');
```
I'm not sure what was the purpose of that empty echo. I'll just remove it.

**Comment by jcubic** [comment]
`CTRL+D` was created so it can resume the terminal if somehow the terminal freezes when Ajax call was done (or other action that pause the terminal).
