### ISSUE TITLE
Browsers without CSS variables are broken

### ISSUE THREAD

**Issue by RussellAbraham** [jcubic/jquery.terminal#630]
### I have question related to jQuery Terminal

Hi, first time issuing a question.

* CSS variables 
* Map function 

Is causing compatibility issue with some of the mobile platforms you have detection for. 

Do you plan to include a Map polyfill and alternative to CSS variables?

Thanks.

**Comment by jcubic** [comment]
I've planed to add to documentation how to use css variables ponyfill (I've played with it on IE11) I need to test if it's still usable without this, but I don't think it's good idea to include with the library. As for Map I should probably add polyfill. That will be included.

**Comment by jcubic** [comment]
Can you tell me what platforms are you interested that don't have Map and CSS variables?

**Comment by RussellAbraham** [comment]
> Can you tell me what platforms are you interested that don't have Map and CSS variables?

Only one actually. BlackBerry 10, Webkit 10.3.3.3216.

After adding a polyfill for Map.

![IMG_20201103_163256](https://user-images.githubusercontent.com/35252806/98055634-d0f5e880-1df2-11eb-8ad8-61202f2446a2.png)

**Comment by jcubic** [comment]
Not sure if I can easily test this, on I don't think that there is such platform at BrowserStack. But I can make it work better with CSS variables or maybe add workaround that can be used.

Did you change the colors anyway or is this the default? At least it should be all black without CSS variables you only should have problems with setting for instance white backround with css variables.

Will test on IE11 and see what can I do. If you will be able to test on your blackberry that would be really helpful.

**Comment by RussellAbraham** [comment]
No that is the default theme from your distribution. 

Sure, I tried to produce a heap yesterday but the devices debugger just output a blank file and I had some errors from Backbone that just added a layer of confusion.

**Comment by jcubic** [comment]
Also one more question do you have any global css on the page? Maybe `*` selector that is applied to the page or maybe selectors like span or div?

**Comment by RussellAbraham** [comment]
> Also one more question do you have any global css on the page? Maybe `*` selector that is applied to the page or maybe selectors like span or div?

No not at all, just what is installed from v2.19.2.  I have been using v0.10.1 until I read through the whole library.

**Comment by jcubic** [comment]
Are you sure you're using same version of CSS and JS?

**Comment by RussellAbraham** [comment]
Yea, adding styles my self would be no problem. I deployed demos of the latest and v0.10.11 here.

[Github Pages](https://russellabraham.github.io/demo/)

I'll add some screen shots of before and after.  At least up to this style sheet issue. No stress, just some stats.

I was hoping to use this browser specifically, android Fennec browser paints everything fine. 

Thanks.

**Comment by jcubic** [comment]
Thanks for the demos. Running in Browserstack in IE11 shows the error. I think that demo (that I've tested) have background from the page not from terminal. Will investigate and try to fix the issue.

**Comment by jcubic** [comment]
Quick fix before I update the library is to just use this for now:
```css
.terminal {
   background: black;
}
```

**Comment by jcubic** [comment]
CSS part is fixed, I only need to also fix #631 for version 2.19.3.

I also have questions about Map I've tested in Safari 10 on MacOSX Sierra and there are no issues. Most the features of Map are in Safari 8 it even work in IE11. Map is used in code that cache the processing of long command line in multiline command when you just move the cursor. It seems that there are no issues. Do you have any exceptions from Map being undefined?

**Comment by RussellAbraham** [comment]
> CSS part is fixed, I only need to also fix #631 for version 2.19.3.
> 
> I also have questions about Map I've tested in Safari 10 on MacOSX Sierra and there are no issues. Most of the features of Map are in Safari 8, it even work in IE11. Map is used in code that cache the processing of long command line in multiline command when you just move the cursor. It seems that there are no issues. Do you have any exceptions from Map being undefined?

No, it doesn't really need it. With Map not being built in, an error was thrown from your [https://github.com/jcubic/jquery.terminal/blob/6414ccffad890f2e632c9bf256d1378bcb3ec88d/js/jquery.terminal.js#L312](code here).

**Comment by jcubic** [comment]
Ok, did you tried this polyfill https://polyfill.io/v3/polyfill.min.js?features=Map service? There is quite a lot of code to polyfill Map object. The service is user-agent based and send JS only if needed. If it don't return anything for your blackberry browser then maybe you will need to report the bug to use the service. 

I home this help, if this is fine then I will need only to document the use of Map object and suggest polyfill.

**Comment by RussellAbraham** [comment]
> Ok, did you tried this polyfill https://polyfill.io/v3/polyfill.min.js?features=Map service? There is quite a lot of code to polyfill Map object. The service is user-agent based and send JS only if needed. If it don't return anything for your blackberry browser then maybe you will need to report the bug to use the service.
> 
> I home this help, if this is fine then I will need only to document the use of Map object and suggest polyfill.
> 
> The main page is https://polyfill.io/v3/url-builder/ where you can use the polyfills you want.

Thank you, the user agent is becoming a problem for this browser.

**Comment by jcubic** [comment]
Then probably you will need feature test kind of polyfill that's always included on the page.

**Comment by jcubic** [comment]
Found [shim for Map](https://github.com/eriwen/es6-map-shim), but it says that implementation is slow, so I've made `Map` optiona,l since it was added to improve speed of rendering (used as cache when moving cursor when command is long and have syntax highlighting).

**Comment by RussellAbraham** [comment]
Great news. Yes it seems an [iterable protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) is behind the implementation of Map done in C++.

While the syntax does not work 1:1 with modern javascript, the latest version of [Backbone](https://backbonejs.org/), provides the same constructs and is more suitable for use in a legacy javascript environment.

**Comment by jcubic** [comment]
releasing the fix in version 2.20.2
