### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by tranceitionalMynd** [jcubic/jquery.terminal#632]
### I have question related to jQuery Terminal

Could you share build instructions please, or a link?

I'm trying to build my fork to experiment with changing the behavior of terminal-error and terminal-command.  I'd like to limit the number of displayed historic commands and errors to one or two.

Thanks,
Tyler

**Comment by jcubic** [comment]
Will need to create steps to build and release the versions. Basic build instruction after fork is `npm install` and `make`. What make does is mostly adding version numbers to the output files, JavaScript source file is written in single ES5 file so no need to use webpack or babel. The only file created by `make` is emoji file.

Will add instructions to README.

**Comment by tranceitionalMynd** [comment]
Hi @jcubic Thanks, that helped.  I also noticed you have a clear() function which provides the functionality I was looking for

**Comment by jcubic** [comment]
Also there is outputLimit option that limit number of stuff in terminal that can be displayed at once.

**Comment by jcubic** [comment]
Added release cycle and build instruction to CONTRIBUTORS.md file.
