### ISSUE TITLE
jquery terminal + prism on SSR

### ISSUE THREAD

**Issue by Kingsy** [jcubic/jquery.terminal#639]
Hi, 

This is related to https://github.com/jcubic/jquery.terminal/issues/624 <- however I couldnt ropen the issue.

sorry to revisit this, however I was hoping you could expand on using jsdom in the above examples? Say I wanted to use the prism extension server side.
How possible is this?

    import terminal from "imports-loader?additionalCode=var%20define=false;!jquery.terminal";
    import PrismJS from "prismjs";
    import prism from "imports-loader?additionalCode=var%20define=false;!jquery.terminal/js/prism";

    var jsdom = require("jsdom").jsdom,
        myWindow = jsdom().createWindow(),
        $ = require("jQuery"),
    terminal(window, $);
    prism(myWindow, $, PrismJS);

Gives me

    ./node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:4:19
    Module not found: Can't resolve 'child_process'
    null

Any suggestions?

**Comment by jcubic** [comment]
I'm not sure why it try to use XHR. Can you tell me exactly what you're trying to do? Maybe there is different solution.

**Comment by Kingsy** [comment]
Of course, I am using jquery terminal and prism to render content and display it to the user from a CMS.
SO, the workflow is (after the page has loaded)

User types command
Application fetches content associated with that command from the CMS.
The content is parsed to look for code snippets which is then highlighted with prism.
The content is displayed via jquery terminal using echo.

This all works great. but I am using nextjs so when a page loads initially if its a deeplink I use getInititalProps to do all of the above server side, so the content is already fetched and parsed when the page loads.

Everything in that chain works apart from prism, obviously in SSR I don't have a window object to pass into terminal() and prism().

Any suggestions?

I can share the link to the website so you can see exactly what I mean in the way its working, but the explanation above is pretty much it.

**Comment by jcubic** [comment]
I was making it work, here is the code:
```javascript
import terminal from "jquery.terminal";
import PrismJS from "prismjs";
import 'prismjs/components/prism-javascript.min.js';
import prism from "jquery.terminal/js/prism.js";
import jsdom from 'jsdom';
import jquery from 'jquery';

const { JSDOM } = jsdom;
const { window } = new JSDOM(`<!DOCTYPE html><html>`);
global.window = window;
global.document = window.document;
const $ = jquery(window);

global.navigator = {userAgent: 'NodeJS'};

terminal(window, $);
prism(window, $, PrismJS);

console.log($.terminal.prism('javascript', 'var x = 10', {command: true}));
```
Also found a bug `{command: true}` should not be required for prism function to work, but the option is required with current version of jQuery Terminal. Note that this works from Node, I didn't tested it with WebPack but you probably just need to add the longer import that force using browser version.

**Comment by Kingsy** [comment]
Thanks for this!
I'll try it tonight and let you know how it works out.

**Comment by Kingsy** [comment]
That worked. BUT I ended up having to use a work around anyway. jsdom ended up needing canvas as a requirement which is currently broken on OpenBSD.

Thank you though. I have saved this information to use when I make a PR to fix canvas.
