### ISSUE TITLE
Stop words breaking across lines.

### ISSUE THREAD

**Issue by Kingsy** [jcubic/jquery.terminal#641]
Hello,

By default if you echo a line longer than the terminal if it happens land in the middle of the word the terminal does not carry the word over to the next line but splits it so some chars are on one line and others on the next. This makes things quite hard to read for a paragraph of text.

Is there a way of preventing this?

Thanks

**Comment by Kingsy** [comment]
Oh, I have also just realised that when using less it doesn't word wrap at all, any word on that one too?

**Comment by jcubic** [comment]
You can make echo wrap on words there is option for that in [echo](https://terminal.jcubic.pl/api_reference.php#echo) `keepWords`

less don't wrap because this how native less works you need to use left/right arrow to show more.

**Comment by Kingsy** [comment]
Ah thats good news about echo.

Ah you are absolutely right about less, but its unfortunate in my case as I want to use it to read paragraphs of text. Is there an easy way of turning off this functionality? so it word wraps like echo within the less command?

If not I will have to write a hack before it to insert \n chars in the right places, which I don't really want to do.

**Comment by jcubic** [comment]
You would need to modify less plugin. I can check how hard it would be to add options to less. You can also try it yourself.

**Comment by Kingsy** [comment]
That would be great if you could have a look.
I'll take a look at the file myself too as you say to investigate.

**Comment by jcubic** [comment]
You need to modify function `print()`
https://github.com/jcubic/jquery.terminal/blob/master/js/less.js#L164
You will need to use `$.terminal.split_equal` before the lines are splitted, so you can proper number of lines.
I can add later today the options: `wrap` and `keepWords`.

**Comment by jcubic** [comment]
or maybe even before the lines get printed so you don't split lines each time less render text that can happen a lot on scroll.

**Comment by jcubic** [comment]
I think it would be better to modify function `run()` here:
https://github.com/jcubic/jquery.terminal/blob/master/js/less.js#L238
that handle initial input and return lines. Note that input can be Array of strings or string and function. There are a bit of logic there is will be more complicated when new options will be added.

**Comment by Kingsy** [comment]
Hm, that run function isnt clear how it would take the fix.
I can see that just making var should_substring = false; does the job, but the starting vertical position of less is off if I just do that, so perhaps it needs something else.

Oh right. if I am understand what you said above correctly? should I wait and you are going to add options into less to do this today?

**Comment by Kingsy** [comment]
Ahh this is great.
Will this change automatically be available via npm?

**Comment by Kingsy** [comment]
Looks like it has the latest release on there. Sorry that was obvious.
Do you think you could create a new release so I can include the new flags via npm please?

**Comment by jcubic** [comment]
No, I need to release new version first, it make take few days I have on feature that I can add to this version, which will be 2.21.0.
Also I found one bug in parsing commands that I would like to fix as soon as possible.

**Comment by Kingsy** [comment]
Thanks!
I will keep an eye out for the new version. much appreciated.

**Comment by jcubic** [comment]
The version of the file is devel branch I've accidentally pushed to master so I've removed the commit that was adding the fix.

**Comment by Kingsy** [comment]
ok np. I'll wait for the new version instead of copying the js file and linking to that.

**Comment by Kingsy** [comment]
Hi, any word on getting this in a new release?

**Comment by jcubic** [comment]
Sorry I didn't had much time to fix the other issue to release new version. In fact I've completely forget that I need to release new version. Will fix that other issue and create that other feature maybe in this week.
If you really need this I can release kind of weird beta version for 2.21.0-beta.1 you will be able to install it from npm using:

```
npm install jquery.terminal@beta
```

**Comment by jcubic** [comment]
I've just finished fixed one bug and added the feature that I wanted in 2.21.0 it will be released soon after GitHub solve their issues, because I want my CI script to run, so I it can test the code on the server. It's works locally but I want my tests to run on the server as well.

**Comment by jcubic** [comment]
Version 2.21.0 got released.

**Comment by king-c** [comment]
Thanks for this! I'll try out the new features today. Appreciate it.
