### ISSUE TITLE
Question: Docs suggest old jquery version 1.11.1?

### ISSUE THREAD

**Issue by hoodmane** [jcubic/jquery.terminal#646]
The docs suggest using jquery from https://code.jquery.com/jquery-latest.js, but this url points to jquery version 1.11.1 (from 2014). Is jquery terminal developed against jquery version 1.11.1? If not, perhaps the docs should be updated? For instance, https://cdn.jsdelivr.net/npm/jquery or https://code.jquery.com/jquery-3.5.1.min.js both point to up-to-date minified copies of jquery.

**Comment by jcubic** [comment]
Thanks for the report will update the docs, I didn't use that url for a long time. I usually use jsdelivr because it's fast and it also allow to use files from GitHub.

**Comment by jcubic** [comment]
The link was updated. Thanks.

**Comment by hoodmane** [comment]
https://blog.jquery.com/2014/07/03/dont-use-jquery-latest-js/

**Comment by hoodmane** [comment]
Thanks for your quick response!

**Comment by jcubic** [comment]
Yes, I was not using that because it was outdated, but I've forgot to update the docs.
