### ISSUE TITLE
Not usable without "unsafe-eval" in script-src

### ISSUE THREAD

**Issue by codegain** [jcubic/jquery.terminal#647]
### Issue summary
Hi,
I'm using jquery.terminal for quite a while now, but since 2.22.0 it stopped working. I got an CSP error in chrome:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'
```

I narrowed it down to this commit 8b2d6bfb0ecffb0d900fd9861f5c9243793e9e14 and this line added:

https://github.com/jcubic/jquery.terminal/blob/9c28d597e8295a5bd282030256a9fe1b50a371c1/js/jquery.terminal.js#L1215

This won't be executed if the CSP doesn't contain `unsafe-eval` in the `script-src` CSP.

### Steps to reproduce

Set a CSP with `script-src 'self'` and run the terminal.

### Browser and OS

Chrome 88 on Windows 10

**Comment by jcubic** [comment]
I've found this code snippet on StackOverflow but it seems that the Function constructor, that is fact eval, is not needed.

This works fine:
```javascript
var is_browser = (function() { try {return this===window;}catch(e){return false;} })()
```
Thanks for the bug report.

**Comment by jcubic** [comment]
The fix is added, it will be published in next bug fix version. I will try in same version fix the prompt issue.
