### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by hoodmane** [jcubic/jquery.terminal#651]
Cursor disappears / gets stuck in first position. Further text is inserted in reverse.

### To trigger
Make a website with the source given at the bottom of this post. Go to the website, put two characters in row one and one character and row two. So for instance "12<SHIFT+ENTER>3" then press Up, Down, Up, Down. The cursor will disappear and text will be inserted backwards at the start of the input region. 

After triggering the bug with that sequence of keystrokes I typed " backwards text is here!" and made the following screen shot:

![image](https://user-images.githubusercontent.com/8739626/109111828-77d9f980-76ee-11eb-9141-2927da4b3f19.png)

Using the following html:
```html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/jquery.terminal/css/jquery.terminal.min.css" rel="stylesheet"/>
</head>
  <body>
    <script type="module">
      window.term = $("body").terminal(
        (command) => {}, 
        { prompt : "" }
      );
    </script>
  </body>
</html>
```

**Comment by jcubic** [comment]
That's really odd, will investigate.

**Comment by jcubic** [comment]
I can confirm the position got outside of the range.

**Comment by jcubic** [comment]
The problem what that the prompt was empty variable prompt_len was undefined and it give wierd results when you press up and down arrows.

**Comment by hoodmane** [comment]
Thanks!
