### ISSUE TITLE
Edit current command line

### ISSUE THREAD

**Issue by dotsquid** [jcubic/jquery.terminal#653]
Hi and thanks for jQuery Terminal!

Currently I'm trying to implement my own version of popup-autocomplete which uses fuzzy searching. E.g. when entering "tin" it would suggest ["tint", "getinfo", "rotation"].
To make it do its job I need to alter an existing command line somehow.
How can I do that? I found the "insert" function, but it's not enough since I have to erase an entire command line before replacing it with a new one.

**Comment by jcubic** [comment]
The method you're looking for is `Terminal::set_command`.

**Comment by jcubic** [comment]
Note there is already popup-autocomplete that you can modify [autocomplete_menu.js](https://github.com/jcubic/jquery.terminal/blob/master/js/autocomplete_menu.js)

**Comment by dotsquid** [comment]
I somehow thought that `Terminal::set_command` sets only the command token keeping argument tokens untouched. But it indeed replaces the whole command line.
Thanks!
