### ISSUE TITLE
please i need help

### ISSUE THREAD

**Issue by mitmelon** [jcubic/jquery.terminal#659]
Am using this code below to login to the commandline

```
 term = $('#terminal').terminal((new TPlugins).getServerPath()', {
		login: true,
        greetings: function() {
            return render('Manomite', 'Slant')+'\n' + (new TPlugins).TemplateEngine(general.patientTerminal, { version: `${$.terminal.version}` });
        },
    });
```

After login I dont know how to add command to this for processing... I have gone through the samples but could not fully understand how to do this...

I have tried using 

```
term.terminal({
		open: function(value) {
		   
		},
		sub: {
		   get: function(arg) {
		   }
		},
		close: function(arg1, arg2) {
		}
	 });
```

but not working

Thanks for your help...

**Comment by jcubic** [comment]
If this is the server path for JSON-RPC `(new TPlugins).getServerPath()` then commands are on the server.

Can you tell me exactly what you want to do? What the server Path point to what is inside?

**Comment by mitmelon** [comment]
> If this is the server path for JSON-RPC `(new TPlugins).getServerPath()` then commands are on the server.
> 
> Can you tell me exactly what you want to do? What the server Path point to, what is inside?

Actually I want user to login first before they could access commands just like you login to Linus terminal to access sudo commands.

I don't want to keep the command in the server...

**Comment by jcubic** [comment]
If you want the commands in JS then you can use array as the interpreter.
```javascript
$('body').terminal([(new TPlugins).getServerPath(), {
    open: function(value) {
    },
    sub: {
        get: function(arg) {
        }
    },
    close: function(arg1, arg2) {
    }
}]);
```

**Comment by mitmelon** [comment]
> If you want the commands in JS then you can use array as the interpreter.
> 
> ```js
> $('body').terminal([(new TPlugins).getServerPath(), {
>     open: function(value) {
>     },
>     sub: {
>         get: function(arg) {
>         }
>     },
>     close: function(arg1, arg2) {
>     }
> }], {
>     login: true
> });
> ```

Ok thank you very much...

**Comment by jcubic** [comment]
But if you want just login, it's overkill to implement the whole JSON-RPC on the server. You can just use a normal server and use ajax to get reply from login function:
```javascript
$('body').terminal({
    open: function(value) {
    },
    sub: {
        get: function(arg) {
        }
    },
    close: function(arg1, arg2) {
    }
}, {
    login: function(user, password) {
        const body = JSON.stringify({user, password});
        return fetch((new TPlugins).getServerPath(), {method: 'post', body}) .then(res => res.json());
    }
});
```

**Comment by jcubic** [comment]
and server should return JSON string with the token or null (or false).
