### ISSUE TITLE
What does the 'class' field do in the formatter

### ISSUE THREAD

**Issue by 0x2b00b1e5** [jcubic/jquery.terminal#667]
For text formatting a `class` field is mentioned in the documentation: 
> class — class adeed to format span element [optional].

I suppose you add that by doing `[[!guib;color;bg-color;class-name]some text]`? When testing this, I couldn't find any class added to the span.

Is anyone using this if so, how does it work? Thanks in advance.

**Comment by jcubic** [comment]
If you use `!` it will create a link and it have `class-name` class. Do you have a demo online where there is no class?

**Comment by 0x2b00b1e5** [comment]
Oh I wasn't aware this only worked for links. Explains a lot

**Comment by jcubic** [comment]
It works on span also but `!` means to create a link.

**Comment by jcubic** [comment]
Just use:

```javascript
term.echo('[[guib;color;bg-color;class-name]some text]');
alert($('.class-name').text())
```
to see the class is created. Maybe you're looking at wrong element.

**Comment by 0x2b00b1e5** [comment]
Found the issue. Thanks for clarifying!
