### ISSUE TITLE
Ignore Case in command

### ISSUE THREAD

**Issue by rabbithops** [jcubic/jquery.terminal#669]
### I have question related to jQuery Terminal

Hi, in this example: 

```
var App = {
    exit: function(text) {
        exit(this);
    },
}
```

exit is the command, but this means typing command as EXIT or Exit will not work. How can we modify the terminal to accept commands of any case? My immediate thought is to use str.toLowerCase(), but I do not know how to modify command before it is checked. Cheers for the great app, I am having a lot of fun using it!

**Comment by jcubic** [comment]
For an exit like this you will need two things:
* `exit: false` option so default exit doesn't work
* Use function as an interpreter where you can make the code ignore the case. You can use the same App object but you invoke the methods yourself.

```javascript
$('body').terminal(function(command) {
   var cmd = $.terminal.parse_command(command);
   var name = cmd.name.toLowerCase();
   if (App[name]) {
     App[name].apply(this, cmd.args);
   } else {
     this.error('Command not found');
   }
}, {
    exit: false
});
```

The object interpreter is for the simplest case. If you want something more customized you should always use function and handle parsing of commands yourself.
