### ISSUE TITLE
How to translate the shell color

### ISSUE THREAD

**Issue by llaiajiale** [jcubic/jquery.terminal#689]
Hi, master!

How to translate the liunx console color:

example:
the color is Black
\033[30mTheBlackWord\033[0m   

the color is Blue
\033[34mTheBlueWord\033[0m    

Thanks.

**Comment by jcubic** [comment]
You need to use unix_formatting.js file just include it and the transformation will be added as formatted. You can read about this on a Wiki [ansi-escape-codes](https://github.com/jcubic/jquery.terminal/wiki/Formatting-and-Syntax-Highlighting#ansi-escape-codes)
