### ISSUE TITLE
Disarranged CSS style in raw HTML echoing

### ISSUE THREAD

**Issue by SuibianP** [jcubic/jquery.terminal#695]
### Issue summary

`display: flex` gone and `float: right` not working when echoing raw HTML content, both seemingly due to an appended `width: 100%` style.

### Expected behaviour
<https://codepen.io/suibianp/pen/bGRKeLP>

The first should be on a single line, with the embedded `div` floating to the right.

The second should have the children distributed evenly on a line.

### Actual behaviour
The first is broken into two lines.

The second is squeezed together.

### Steps to reproduce
<https://codepen.io/suibianp/pen/YzQvWwY>

### Browser and OS
Firefox 92.0 (64-bit), Manjaro Linux

**Comment by jcubic** [comment]
And thanks for reporting the bug.

**Comment by jcubic** [comment]
The fix is in the devel branch, it will be released in the next version.

**Comment by SuibianP** [comment]
Thank you very much for the fantastic package and rapid fix!
