### ISSUE TITLE
Weird behaviour by CSS in echoed raw HTML

### ISSUE THREAD

**Issue by SuibianP** [jcubic/jquery.terminal#697]
### Issue summary
`margin-block-start` has no effect and messes up terminal appearance.

### Expected behaviour
There should be a 1em margin above the `h2` element; other terminal styles should not be affected.

<https://codepen.io/suibianp/pen/NWgzpVv>

### Actual behaviour

A white bar appears above the terminal, and the cursor grows much bigger. Moreover, `margin-block-start` has no effect on the heading.

### Steps to reproduce
<https://codepen.io/suibianp/pen/ZEyReQJ>

### Browser and OS
Firefox 92.0 (64-bit), Manjaro Linux

**Comment by jcubic** [comment]
I was fixing broken CSS a lot of time, and I'm tired. I will add to documentation that should not use `*` selector any custom CSS. For this, to work I will need to force every possible CSS property that exists in the specification and update the library when the browser decides to create new CSS property.

Please don't use `*` selector, it will probably break a lot of JavaScript libraries that are out there.

**Comment by jcubic** [comment]
Note that if you want to affect your own HTML inside terminal (from raw echo) you should use:

```css
.terminal. raw * {

}
```

**Comment by jcubic** [comment]
Also, this doesn't make any sense to echo the whole HTML page including html and body tags. There should be only one html and body tag on the page.
