### ISSUE TITLE
Get rid of templates/package.in

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#700]
### I have an idea for a new feature for jQuery Terminal

It was used to update the version in package.json file but now it the Makefile update `package.in` when package.json changes and it recursive it keeps updating.

The package.in have `{{VER}}` that is updated with current version but to update the package.in the code use regex so it can just update the file iteself.

The file is modified in Makefle file (that is created based on template/Makefile.in so that file needs to be modified and then make needs to be run to update Makefile).

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by jcubic** [comment]
@himanshu007-creator go ahead.
