### ISSUE TITLE
Keyboard on Firefox mobile (Android) not showing.

### ISSUE THREAD

**Issue by trankten** [jcubic/jquery.terminal#750]
### Issue summary
When you open a webpage with jquery terminal in Firefox under Android, it won't the keyboard. Chrome works fine. I've tried with https://www.trankten.com and https://terminal.jcubic.pl/android.php and I get the same result.

### Expected behavior
Keyboard should appear on mobile device to type.

### Actual behavior
Keyboard doesn't show.

### Steps to reproduce
Visit the website with the aforementioned browser

### Browser and OS
Firefox for Android.

Have a nice day.
![noKB](https://user-images.githubusercontent.com/86560527/154867516-ec24c640-5edc-4d56-a5e3-f57ff1d07c88.jpg)

**Comment by jcubic** [comment]
android.php is my testing code. Don't use it to test if something works. There are some issues with your site like missing viewport meta tag, and some issue with prompt. But the keyboard is working. At least when I've tested this on my phone.

**Comment by jcubic** [comment]
android.php is my testing code. Don't use it to test if something works. There are some issues with your site like missing viewport meta tag, and some issue with prompt. But the keyboard is working. At least when I've tested this on my phone. 

Note that on mobile you need to tap to open the keyboard.

**Comment by jcubic** [comment]
Note to self: check [Firefox remote debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging).

**Comment by luohua17** [comment]
I also had this problem.

**Comment by jcubic** [comment]
Adding 2.35.0 milestone, this is pretty important.

**Comment by jcubic** [comment]
I just checked and Firefox is working on Android. The [404 error page](https://terminal.jcubic.pl/404) is working fine.

I'm closing the issue. If you have the same problem please create a reproduction.
