### ISSUE TITLE
How To Extend JQuery Terminal Methods?

### ISSUE THREAD

**Issue by KiddoV** [jcubic/jquery.terminal#755]
_I have question related to jQuery Terminal:_

I want to extend some methods to your plugin without touching the source code, for example, your plugin has the ``.error()`` method to print red lines to terminal. I want to add a ``.warning()`` method to print a yellow lines. 
I want to add those custom methods globally so those can be used for any JQ Terminal instances on the same page.

Is there anyway that I can do that?

Thanks!

**Comment by jcubic** [comment]
Goog question, I will add this to Wiki. The library extend jQuery plugin object, so you can add jQuery plugin:

```javascript
$.fn.warning = function() {

};
```

one thing to remember is that this is not a jQuery Terminal instance so you need to call.

```javascript
this.terminal().echo(...);
```

so the code can look like this:

```javascript
$.fn.warning = function(text) {
   return this.terminal().echo('[[;yellow;]' + text + ']');
   // or
   return this.terminal().echo(`[[;yellow;]${text}]`);
};
```

jQuery error has more code because it handles brackets if you want to be able to print for instance '[WARN]: this is warning' you should use `$.terminal.escape_brackets()` or alias `$.terminal.escape_formatting()`.

One more thing is that builtin Terminal methods are not jQuery plugins so you can't change them for instance:

```javascript
$.fn.echo = function() {
};
```
THIS WILL NOT WORK.

**Comment by KiddoV** [comment]
@jcubic Thanks. It works flawlessly. Now I can make my custom method.
I didn't know that we have ``$.terminal.escape_brackets()`` to handle brackets, I was using...
```js
msg = JSON.stringify(msg).replace(/^"(.+(?="$))"$/, "$1").replace(/[\[]+/g,"&#91;").replace(/[\]]+/g,"&#93;")
```

**Comment by KiddoV** [comment]
Additional to this question. How do I make this work in TypeScript?

**Comment by jcubic** [comment]
I'm not sure, I would need to experiment. But I think that it would look the same as the library extend jQuery and add new methods.

**Comment by jcubic** [comment]
I'm not sure how to do this. My testing code doesn't event work:

```typescript
import jQuery from "jquery";
import terminal, { JQueryTerminal } from "jquery.terminal";

const $ = terminal(window, jQuery);

const fn: JQueryTerminal.FunctionInterpreter = function(command) {
   this.echo(command.toUpperCase());
};

$('body').terminal(fn);
```

I'm not sure if it was working. Maybe d.ts file need to be updated in order to extend with the types. I also just noticed that the types you added are wrong, because the default export should return jQuery object.

**Comment by KiddoV** [comment]
I am certain I can call `terminal` in this case:
```ts
import jqTerminal from 'jquery.terminal';

jqTerminal(window, jQuery); //This works without error
```
At leaset in my application.

**Comment by jcubic** [comment]
Yes it works, I've tried to modify the code to allow returning JQueryTerminal namespace and allow returning jQuery from terminal function.

**Comment by KiddoV** [comment]
Any update on this?

**Comment by jcubic** [comment]
If you want to add additional methods to jQuery Terminal, you can do the same what the library is doing, extend the JQuery object.

Becase what you want is how to extend JQuery, which is the same how to have jQuery plugin in TypeScript. You can try to google to find how. This is an answer on StackOverflow:

[How to extend JQuery functions in TypeScript](https://stackoverflow.com/a/47091565/387194)

**Comment by KiddoV** [comment]
I think I got it.
Example:
```ts
//Put this somewhere in your global scope file...
declare global {
    interface JQueryTerminal {
        info(msg: string): JQueryTerminal
    }
}

$.fn.extend({
    info(msg: string): JQueryTerminal {
        return this.echo(msg);
    }
});
```
This work perfectly in my app.

**Comment by jcubic** [comment]
The code works in TypeScript but it should throw an error.

You need to use:

```javascript
$.fn.extend({
    info(msg: string): JQueryTerminal {
        msg = "[[;#39C0ED;]" + msg + "]";
        return this.terminal().echo(msg);
    }
});
```

Because in jQuery plugin this is jQuery object and to get terminal object you can call `.terminal()`. But note that if the object is not jQuery Terminal it will create an instance for you.

**Comment by KiddoV** [comment]
@jcubic  weird! I don't see any error when using it, but thanks for the suggestion anyway!

**Comment by jcubic** [comment]
Hm, maybe it because how jQuery pass the context around. But anyway with this you can use:

```javascript
$('.terminal').info('message');
```

or 

```javascript
term.css('--color', 'red').info('message');
```

and it will still work.
