### ISSUE TITLE
How to set height of Terminal

### ISSUE THREAD

**Issue by GalaxyLinus** [jcubic/jquery.terminal#758]
### I have question related to jQuery Terminal

So I have my Terminal embedded in a WinBox.js Box that can be resized. I want to change the height of the terminal to the height of my box, so when you click anywhere in the box, the terminal cursor gets selected. How to achieve that?

![image](https://user-images.githubusercontent.com/57060126/157479898-ea72a934-17a5-443e-a47b-76f09036430f.png)

**Comment by jcubic** [comment]
First, you have some kind of padding so you need to remove it, unless you want that to be preset, just use dev tools to find that padding. And to make it fill the container use `height: 100%`.

**Comment by jcubic** [comment]
I've found [your site](https://galaxylinus.github.io/).

If you want 20px padding I suggest:

```css
#terminal-content {
  padding: 20px;
}
```

because right now the scrollbar is in the middle of the window, which doesn't look good.
