### ISSUE TITLE
Add space after tab completion

### ISSUE THREAD

**Issue by kama1** [jcubic/jquery.terminal#761]
How to add a space after using tab completion?

Currently when user uses tab completion a space required to use another tab completion.

**Comment by jcubic** [comment]
The only way is to use function as completion, you should be able to use whatever you want, including adding space at the end. If I will have time I can create a demo if you want.

**Comment by jcubic** [comment]
I think that one feature is missing getting default completion in function so you can enhance it. I've created an issue for that.

**Comment by kama1** [comment]
completionEscape: false works like a charm!
