### ISSUE TITLE
Scroll on Echo Problem on New Version 2.33.1

### ISSUE THREAD

**Issue by KiddoV** [jcubic/jquery.terminal#777]
### Issue summary
The ``scrollOnEcho`` was Ok on the old version (2.28) I think. I just updated to the latest (a lot of changes). Now it is not working anymore!
### Steps to reproduce
Check my JSFiddle.
Scroll up/down a few time in the terminal.
After a few scrolling, you will see the terminal stop automatically scrolling to the bottom.
### Browser and OS
Windows 10
Chrome, Webview2
### Additional notes
https://jsfiddle.net/KiddoV/5srqhzLm/14/

I tested the old version 2.32.1 was OK. It just happen on the big version 2.33.0 (this version has a big update)

**Comment by jcubic** [comment]
I will investigate probably when the content is very large the scroll to the bottom doesn't work anymore. I've seen this when printing factorial of 8000 using big int in my other project.

It may be related to pixel density that was added in the last version and maybe also related to CSS.

**Comment by jcubic** [comment]
What is the use of:

```javascript
  $('.prompt').hide(0, function() {
    setTimeout(function() {
      $('.terminal-output').text('Connected');
      $('.prompt').delay(500).show(0); 
    }, 3000);    	
  });
```

**Comment by jcubic** [comment]
The problem was that there was a new element added - a `.scroller`, I don't remember why but it was required. The code that scrolls to the bottom was not updated to use that new element.
