### ISSUE TITLE
Ask for password, hash it (sha256) and check it. Possible?

### ISSUE THREAD

**Issue by S1700** [jcubic/jquery.terminal#783]
I've already tried to do this but I can't get it to hash and check it, has anyone else done this before and got code snippets?

Thanks

**Comment by dragoncoder047** [comment]
IMO I think that's outside the scope of this library. Perhaps [`SubtleCrypto.digest()`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest#:~:text=in%20cryptographic%20applications\)-,%22SHA%2D256%22,-%22SHA%2D384%22)?

**Comment by S1700** [comment]
ill look into that lib thanks

**Comment by jcubic** [comment]
The hash is usually done on the server, I've never seen any website that has the password in the browser. You send the password to the server and then hash it. The same as on any other website you check the hash on the server.

**Comment by S1700** [comment]
I'm using GitHub to host the site will it still work with that?

Thanks

**Comment by jcubic** [comment]
If you use GitHub pages I suggest using Firebase authentication. You need to have some kind of persistence. You can't create authentication without a server.

**Comment by S1700** [comment]
ah okay ill try it, never used it but let's see

Thanks
