### ISSUE TITLE
Using the color function with text that has ]

### ISSUE THREAD

**Issue by S1700** [jcubic/jquery.terminal#784]
So I'm using `[[;green;]]` to put color in the terminal, but when I try to do it with text that already has a [] in it leaves the ] on the text uncolored (look at `Pinging server`):
![image](https://user-images.githubusercontent.com/68336568/170119727-fe5f9b47-6cae-4bc4-8b52-f37d1136e34d.png)
here is the code:
![image](https://user-images.githubusercontent.com/68336568/170119885-53d16a19-a2a4-462f-a9ed-dba9a70b2e1b.png)

Thanks

**Comment by S1700** [comment]
I did try to escape the character before and no combination worked (`\]], ]\], \]\]`). What do you mean with the `$.terminal.espace_brackets` and how would I apply it

Thanks

**Comment by jcubic** [comment]
```javascript
term.echo(`[[;green;]${$.terminal.escape_brackets('[OK]')}]`);
```

**Comment by dragoncoder047** [comment]
The other thing I have tried that seems to work relatively well is using `{raw: true}` and a `<span>`. That way you only have to escape `<` to `&lt;` when you don't want it to be interpreted as the start of a HTML tag.

```js
term.echo('<span style="color: green;">[OK]</span>', { raw: true });
```

This might cause issues if you ever apply custom formatting later on (change font, text size, etc). [I did](https://github.com/dragoncoder047/phoo/issues/5) and when I use `{raw: true}` the text is ever-so-slightly bigger that without. I'm not exactly sure why but it doesn't seem like it would be a problem.

But if you insist on using the bracket formatting, you can replace literal brackets with `&lsqb;` and `&rsqb;`. Saves you a call to `$.terminal.espace_brackets` and a mildly confusing template string interpolation.

**Comment by S1700** [comment]
Okay, thanks got it. One more question before I close this (prevents me from opening a new issue), how would I clear the terminal automatically after a short delay when the boot thing finishes?

**Comment by jcubic** [comment]
```
setTimeout(() => {
  term.clear().resume();
}, 1000);
```
You should use resume here, you don't want to clear user commands.

And one more thing, if you don't want to see a prompt when boot animation is running use `term.pause()`; without true. I just assumed that you want the prompt to be visible.

**Comment by jcubic** [comment]
and escape brackets is just:

```javascript
        escape_brackets: function escape_brackets(string) {
            return string.replace(/\[/g, '&#91;')
                .replace(/\]/g, '&#93;')
                .replace(/\\/g, '&#92;');
        },
```

so if you use replace yourself you just duplicate what's already been implemented.

**Comment by S1700** [comment]
Thanks!

**Comment by S1700** [comment]
oh dumb me, I forgot to ask where should I put this auto-clean function, tried putting it in the onInit code and it just does it on a loop or it does it straight away (while all the boot text is going).

Thanks (last question I promise)

**Comment by S1700** [comment]
ah got it thanks!

**Comment by jcubic** [comment]
You probably don't want that old `term.resume()` so you should delete it.
