### ISSUE TITLE
Removing masks?

### ISSUE THREAD

**Issue by S1700** [jcubic/jquery.terminal#786]
How do you remove/unset masks? Can't find it in issues or in the getting started guide

Thanks

**Comment by jcubic** [comment]
You can do that with:
```javascript
term.set_mask(false);
```
It seems that I need to add this to the documentation.

**Comment by S1700** [comment]
Thanks, do you know where I should put it in this code to ask for the password then once they have it remove it.
```
secret: function() {
            hashCode = function(s){
                return s.split("").reduce(function(a,b){a=((a<<5)-a)+b.charCodeAt(0);return a&a},0);              
            }
            this.set_mask('*').read('Password: ').then(pass => hashCode(pass) == '-1152556145' ? this.echo('\n[[;green;]Access granted.]') : this.echo('\n[[;red;]Access denied.]'));
        },
```
Already tried some combinations but they always end up remove the mask before they put the password

Thanks

**Comment by dragoncoder047** [comment]
> Thanks, do you know where I should put it in this code to ask for the password then once they have it remove it.
> 
> ```js
> secret: function() {
>             hashCode = function(s){
>                 return s.split("").reduce(function(a,b){a=((a<<5)-a)+b.charCodeAt(0);return a&a},0);              
>             }
>             this.set_mask('*').read('Password: ').then(pass => hashCode(pass) == '-1152556145' ? this.echo('\n[[;green;]Access granted.]') : this.echo('\n[[;red;]Access denied.]'));
>         },
> ```

It goes inside the `.then` handler which is called with the password when the user presses enter.

```js
.then(pass => {
  this.set_mask(false);
  if (hashCode(pass) == '-1152556145') this.echo('\n[[;green;]Access granted.]')
  else this.echo('\n[[;red;]Access denied.]'));
});
```

**Comment by S1700** [comment]
Thanks so much!
