### ISSUE TITLE
Scrolling is too fast

### ISSUE THREAD

**Issue by wch** [jcubic/jquery.terminal#795]
### Issue summary

Scrolling with the touchpad or a mouse wheel is too fast. This makes it difficult to scroll a specific part of the history. I'm using a Mac, and this happens with both the touchpad and with a mouse scroll wheel, in Chrome, Firefox, and Safari.

This can be tested by going to https://jcubic.github.io/jquery.terminal/, holding down Enter until there are enough lines of output that a scrollbar appears, and then scrolling. The minimum scrolling increment for me is about 2 whole lines. In "normal" web content with a similar font size, the minimum scrolling increment is about 0.1-0.2 lines.

I found that replacing this:

https://github.com/jcubic/jquery.terminal/blob/a2d769db3cc5b00469e294c73b4d36035a1d8793/js/jquery.terminal.js#L12057-L12061

with this:

```js
    self.scroll(-delta);
```

results in natural-feeling scrolling behavior, with proper acceleration.

Is there a particular reason that scrolling code sets the scrolling increment to 40?

**Comment by jcubic** [comment]
The value was picked by experimentation, or maybe I took that value from somewhere). I think it was matching windows or Linux behavior.

You can disable mousewheel controlling if you return true from the event:

```javascript
$('body').terminal(function(command) {

}, {
    mousewheel: () => true
});
```

Mousewheel was mostly done for `Less` plugin that changes the way you scroll.

**Comment by jcubic** [comment]
DO you only have a TypeScript error or the code doesn't work at all? TS errors are like warnings they still generate the output code so you can test if it works. I will add typing for the mousewheel event.

**Comment by wch** [comment]
I just tried it again: I have the TypeScript error, but the code does work as you said. I previously thought the code did not work, but I think I was editing the wrong copy of the file on my computer. Thank you!

Also, I suggest adding `mousewheel` to the API documentation so that others will see how to deal with the scrolling speed issue.

**Comment by jcubic** [comment]
Yes, not everything is properly documented. There are a lot of issues for writing the documentation.

I need to take some time just go through everything in the code and properly document it.
