### ISSUE TITLE
how to enable history on `read()`?

### ISSUE THREAD

**Issue by dragoncoder047** [jcubic/jquery.terminal#796]
In the docs it says this:

> `read([string, success_fn, cancel_fn])` — wrapper over push, it set prompt to string and wait for text from user then call user function with entered string. The function also return a promise that can be used interchangeably with callback functions. **from version 1.16.0 read disable history.**

Is there (or can there be) an argument to bring back the history of previous interpreter? or do I have to resort to manual push and pop hacks / re-implementing `read()`?

https://github.com/jcubic/jquery.terminal/blob/01001bd4e07b2e3fe20b375b13569d69431b888f/js/jquery.terminal-src.js#L10800

**Comment by jcubic** [comment]
`read()` is just a wrapper over `push()` you can use that instead and you will have history.

You can also use

```javascript
const ret = this.read('? ');
this.cmd().history().enable();
```

But the history is always per interpreter the same in real Terminal, if you run NodeJS you have a different history than in bash. So `read` will have its own history even if you enable it.

I was reading the code and found this hack:

```javascript
$('body').terminal({
    async push() {
        this.echo(await this.read_ex('? '));
    }
}, {
    name: 'this'
});

$.fn.read_ex = function(...args) {
    var term = this.terminal();
    var name = this.prefix_name(true);
    var ret = this.read(...args);
    var cmd = this.cmd();
    cmd.name(name);
    cmd.history().enable();
    return ret;
};
```

`Terminal::prefix_name(true)` returns the real name of the interpreter used in localStorage if you set this as the name of the CMD it will create history based on that name and restore the same command History as the previous interpreter.

The way the library is constructed you can't overwrite the built-in `read` method, but jQuery Terminal extends the jQuery object so whatever you add to $.fn will be accessible from the terminal object.
