### ISSUE TITLE
Add blur as alias to focus(false)

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#813]
It may be confusing that `term::blur()` does nothing (it's jQuery method `$.fn.blur`) so there should be a `blur()` that is just an alias for focus(false).

_Inspired by @AlexCrosby post in discussions https://github.com/jcubic/jquery.terminal/discussions/812_

**Comment by kumar-rocks** [comment]
I am new to open source, can you explain more about it.

**Comment by jcubic** [comment]
It's implemented. I use this flow when I don't close tasks only add label resolve and close it when code is released.

**Comment by jcubic** [comment]
Do you want to do that on initialization or when you do something like inside a command?

**Comment by jcubic** [comment]
I don't think you can't do this. Because of Logic. To be able to focus the input you need to blur the terminal you can't prevent something that already happens.

But anyway if you need this feature please create a new issue, this is not related to this one. This issue is about adding an alias method.

GitHub issues are not a forum where you have discussions about different topics.
