### ISSUE TITLE
Saving State Server Side

### ISSUE THREAD

**Issue by dstyvsky** [jcubic/jquery.terminal#823]
I have need to save state of the Terminal server side. In reading the documentation I come across this line: 

"NOTE: The object that is returned by export_view will not work with JSON.stringify unless you have a way to serialize functions. But it will work with few limitations if you strip out functions."

I have tried removing the functions without success. How would I go about stripping these functions and then reloading the state from the stripped JSON?

I also tried the jsonfn library to serialize the state with functions included but did not have success with that either.

**Comment by dstyvsky** [comment]
Got it working with just stringify. Must have been passing something incorrectly.

**Comment by jcubic** [comment]
I'm glad you figure that out.
