### ISSUE TITLE
Code of Conduct file Missing !!

### ISSUE THREAD

**Issue by sumitbishti** [jcubic/jquery.terminal#830]
According to Hacktoberfest guidelines you should have a Code of Conduct file which contains your values and rules.
I can create that for you.

**Comment by jcubic** [comment]
If I would ever add a CoC document I would like to write it myself, and don't make it random or exactly the same as other projects. What is the point of having a document that is always the same?

Where can I find Hacktoberfest guidelines? Do you have a link?

**Comment by sumitbishti** [comment]
You can take an idea from here: https://hacktoberfest.com/participation/#maintainers

**Comment by jcubic** [comment]
It says best practices so it's not a requirement, only a suggestion.

**Comment by jcubic** [comment]
Add Code Of Conduct. I don't see a reason to put CoC from the template. So I've created a short NON-BULSHIT COC.
