### ISSUE TITLE
How to use jquery.terminal in vue3

### ISSUE THREAD

**Issue by thekingofsex** [jcubic/jquery.terminal#832]
hello everyone, i'm a rookie front-end developer
i'm useing jquery.terminal in vue3 and vite.
i'm trying this to import jquery.terminal and use it.
<img width="491" alt="image" src="https://user-images.githubusercontent.com/38530231/195557506-5c82996c-06f5-42bb-8990-80315d74fecd.png">
but when i print `$('#test').terminal()` in console ,the console tell me `Uncaught TypeError: $(...).terminal is not a function`.
<img width="543" alt="image" src="https://user-images.githubusercontent.com/38530231/195558564-7e368356-845d-42cd-98b4-736e96191a86.png">
it seems like there is no `terminal()` method in `$('#test')` object.
I have already googled and checked other people's code on github , but it not works.
How can i fix this. , pleases help me :sob:

**Comment by jcubic** [comment]
You need to invoke the terminal with jQuery and a window object. This is how the old version of jQuery used to work when using import.

When I'm using import on CodeSandbox it complains about `jquery.terminal` not being a module, the UMD solution is pretty old.

This is what I'm using to import jQuery Terminal.

```javascript
import "jquery.terminal/css/jquery.terminal.min.css";
const jquery = require("jquery");
const terminal = require("jquery.terminal");
const $ = terminal(jquery, this);
```

You can also pass 3rd argument which is `wcwidth` (for wider characters like Chinese or Japanese).

**Comment by thekingofsex** [comment]
> You need to invoke the terminal with jQuery and a window object. This is how the old version of jQuery used to work when using import.
> 
> When I'm using import on CodeSandbox it complains about `jquery.terminal` not being a module, the UMD solution is pretty old.
> 
> This is what I'm using to import jQuery Terminal.
> 
> ```js
> import "jquery.terminal/css/jquery.terminal.min.css";
> const jquery = require("jquery");
> const terminal = require("jquery.terminal");
> const $ = terminal(jquery, this);
> ```
> 
> You can also pass 3rd argument which is `wcwidth` (for wider characters like Chinese or Japanese).

thank you dude, it help me a lot
