### ISSUE TITLE
CTRL + C

### ISSUE THREAD

**Issue by hasanbahadirkoca** [jcubic/jquery.terminal#843]
### I have question related to jQuery Terminal

How can I make a keyboard shortcut to stop a function like CTRL + C.

**Comment by dragoncoder047** [comment]
> How can I make a keyboard shortcut to stop a function like CTRL + C.

Unfortunately I don't think you can do this with vanilla JS... the best approach I know is to insert a "check for CTRL+C" function periodically in your code that throws an error if a flag has been set, kind of thing. You can then set that flag in a CTRL+C keymap handler. See [here](https://terminal.jcubic.pl/api_reference.php#:~:text=keymap%20%E2%80%94%20object%20where%20keys%20are%20uppercase%20shortcuts%20like%20CTRL%2BALT%2BC%20and%20the%20value%20is%20the%20function%20executed%20on%20that%20shortcut.%20The%20order%20of%20modifiers%20are%20CTRL%2C%20META%2C%20SHIFT%2C%20ALT.)

**Comment by jcubic** [comment]
Yes, you can use:

```javascript
$('body').terminal({}, {
   keymap: {
     'CTRL+C': function() {
        // your code
     }
});
```
but you can stop the invocation of a function in JavaScript. But this is beyond the question about jQuery Terminal. To really stop the invocation of the function you would need to create your own Virtual Machine or interpreter that you would control.
