### ISSUE TITLE
File '[.../node_modules/jquery.terminal/js/jquery.terminal.d.ts' is not a module.

### ISSUE THREAD

**Issue by yutongluo** [jcubic/jquery.terminal#844]
### I have question related to jQuery Terminal

I'm using a hack seen on [this issue](https://github.com/jcubic/jquery.terminal/issues/832) to get jquery working in typescript. 

```
import jquery from 'jquery'
import terminal from 'jquery.terminal'
const $ = terminal(jquery, this)
```

I'm getting `File '[.../node_modules/jquery.terminal/js/jquery.terminal.d.ts' is not a module.` Any ideas why this is happening? None of the types are working in my file. 

```
"devDependencies": {
    ...
    "jquery": "3.6.1",
    "parcel": "^2.8.0",
    "typescript": "^4.9.3"
  },
  "dependencies": {
    "jQuery": "npm:jquery@^3.6.1",
    "jquery.terminal": "^2.34.0"
  }
```

**Comment by jcubic** [comment]
I have no idea, I can reproduce it, the problem is probably that the library is not ES Module.

**Comment by KiddoV** [comment]
Add this at the bottom of the ``jquery.terminal.ts`` fixed the VSCode error for me:
```ts
declare module 'jquery.terminal' {
    const jqTerminal: (window: Window, JQuery: JQueryStatic) => void;
    export default jqTerminal;
}
```

**Comment by jcubic** [comment]
Awesome thanks, I will check it out if it works. Note that you can contribute with the fix, you will be added to the list of contributors, since they are generated with GitHub API.

**Comment by KiddoV** [comment]
Sure. I can make a PR.

**Comment by jcubic** [comment]
I just checked and it works. Please make a PR for the development branch if you can.
