### ISSUE TITLE
commandline contains &nbsp; instead of the original spaces, makes impossible to wrap the line

### ISSUE THREAD

**Issue by philippehenri** [jcubic/jquery.terminal#848]
Hello
I am trying to type automatically something as a command.

I tried:
1/ echo term.prompt + text
and
2/ set_command (text)

In both cases all spaces in my text are replaced by &nbsp; and therefore I cannot apply any wrap or break-word css params if the length of the command exceeds the terminal width...

Is there a way to avoid that?

ps: these &nbsp appear only when echoing on command line apparently?

thanks !
Philippe

**Comment by jcubic** [comment]
The terminal is automatically breaking lines you don't need to use CSS to break the lines.

Can you maybe create an example that shows:
* what you're trying to do
* What you expect to have
* WHat you have instead

**Comment by philippehenri** [comment]
Hi Jakub,
thanks for your reply.
here we go: https://codepen.io/PhilippeHenri/pen/MWBvWzo

1/ please note that I have changed the font (css part): this codepen shows wrapping the problem

2/ if i do not change the font, it breaks words but in the middle of words ?

3/ you will also note that "the echo('long text')" in the js code does not trigger the command event (it does if i paste the same text)

thanks !!
regards
philippe

**Comment by jcubic** [comment]
jQuery Terminal works only with a monospace font to properly wrap lines. It takes a long time to make wrapping lines properly. There are two modes with words or not.

Sorry to say, but making terminal wrap lines with a normal font is out of scope for this project. Please use a monospace font. I probably should document is somewhere.

**Comment by jcubic** [comment]
Also if you will use different font sizes on different parts of the terminal the library also may have problems calculating the number of characters per line.

**Comment by philippehenri** [comment]
ok well noted, thanks

**Comment by jcubic** [comment]
And just a note, you can pick different font but make sure it's monospace.
