### ISSUE TITLE
Keep Getting: ``Uncaught TypeError: Cannot set properties of undefined (setting 'omap')``

### ISSUE THREAD

**Issue by KiddoV** [jcubic/jquery.terminal#849]
### Issue summary
I am keep getting this error 
```console
Uncaught TypeError: Cannot set properties of undefined (setting 'omap')
    at jquery.terminal.js:264:7
    at jquery.terminal.js:227:9
    at jquery.terminal.js:183:1
(anonymous) @ jquery.terminal.js:264
(anonymous) @ jquery.terminal.js:227
(anonymous) @ jquery.terminal.js:183
```
...when trying to import jQuery Terminal.

### Steps to reproduce
Just getting started.
Either import using CDN links, or import as ESM.
### Browser and OS
Windows 10
Webview2 (MS Edge)
### Additional notes
Using ``Svelte`` as a frontend!

**Comment by jcubic** [comment]
Do you include jQuery? It looks like it's not defined. Can you create a reproduction of the issue? Something I can test?

**Comment by KiddoV** [comment]
I did included the jQuery lib already, because I also have other libraries that depends on the jQuery. Those libraries work tho.

I cannot reproduce the issue because Svelte REPL doesn't support TypeScript:
https://svelte.dev/repl/860f5ef210634b16803ea32af65b67ba?version=3.55.1

Maybe it only happen with TypeScript?

**Comment by jcubic** [comment]
I was looking at the REPL, sorry I know nothing about Svelte you will need to debug this yourself.

**Comment by jcubic** [comment]
But it looks like the scripts are just added to the document and the next script doesn't wait for the previous script as it happens with normal HTML. Any reason why you use the Svelte compiler with jQuery plugins? It's like a combination of Angular and React in one project (and I don't talk about micro frontends).

**Comment by KiddoV** [comment]
I was trying a new framework on my project, but still stuck with some old libraries that still depends on the ``jQuery`` (It would take awhile for those libraries to get a new ESM version).

Can you point me to the line of code where the ``$.omap`` was extended from? (Where is the ``$.omap`` was defined?)
Thanks,

**Comment by jcubic** [comment]
It's at the top of the file, it's a utility that is used like Array::map but for objects. Just after UMD Module definition. To get this error you need to execute JS file without including jQuery. Which I think happens because loading scripts run in parallel. So jQuery Terminal is executed before jQuery is fully parsed and executed.

To fix this I can only think of one hack, that I use to load jQuery in my bookmarks:
```javascript
    script('https://cdn.jsdelivr.net/npm/jquery');
    (function delay(time) {
        if (typeof jQuery === 'undefined') {
            setTimeout(delay, time);
        } else {
            next(jQuery, function() {
                if (orig_jQuery) {
                    window.jQuery = orig_jQuery;
                    if (dolar) {
                        window.$ = window.jQuery;
                    }
                }
            });
        }
    })(500);
```

See the rest of the code here: https://github.com/jcubic/lips/blob/master/lib/js/bookmark.js

The alternative is to search for how to load scripts is a sequence in Svelte.

**Comment by KiddoV** [comment]
This line I supposed?
https://github.com/jcubic/jquery.terminal/blob/29791ab401fddd8805d7efa4fdbeb038f2ed676e/js/jquery.terminal.js#L264

Thanks for the suggestions!

**Comment by KiddoV** [comment]
Solved by adding this line:
```js
$ = window.jQuery
```
``window.jQuery`` must defined in ``vite.config.ts``

to line number 231 https://github.com/jcubic/jquery.terminal/blob/29791ab401fddd8805d7efa4fdbeb038f2ed676e/js/jquery.terminal.js#L231

**Comment by KiddoV** [comment]
True! but I have tried many way. I guess this is the only way for me.

**Comment by jcubic** [comment]
If this has nothing to do with svelte (most likely) If I will have time I will test using the library with just Vite.

**Comment by KiddoV** [comment]
I am still very confused of how the ``root.jQuery`` is undefined at this line https://github.com/jcubic/jquery.terminal/blob/ef9b63834a9bc2679fae45fd7d308873304016c3/js/jquery.terminal.js#L193

After a few ``console.log``, the ``root`` variable should point to ``window`` object at that line, and when I do:
```js
console.log(window.jQuery) // <==== This clearly display jQuery is already defined
console.log(root.jQuery) // <=== This is undefined, wth? Should ``root`` be the SAME as ``window``?
```

**Comment by jcubic** [comment]
Please provide a reproduction of the issue. Share your code somehow e.g. on GitHub

**Comment by KiddoV** [comment]
I got a minimal code for you to try here...
[xdot-controller-v2.zip](https://github.com/jcubic/jquery.terminal/files/11332098/xdot-controller-v2.zip)
To run the app you need to do a little bit of setup.

 1. Download and unzip file.
 2. In the editor, CD to the main folder: ``xdot-controller-v2``.
 3. You need to install ``Wails``, follow these step: https://wails.io/docs/gettingstarted/installation
 4. Now you can run the app with command: ``wails dev``.
 5. When the app run, you can right click to open the dev tool just like in the browser.

I think this is the only way that I can address the error.

Thanks,

**Comment by jcubic** [comment]
The problem is that you're using import, jQuery Terminal is written as UMD module and you need to run something like this:

```javascript
const jQuery = require('jquery');
const terminal = require('jquery.terminal');
terminal(jQuery);
```

it will not work with import, since it's not supported. You need to figure out how to include the library in some other way.

I think that the problem is that you have two version of jQuery one that is hardcoded by your build and one that is loaded by the terminal.

**Comment by jcubic** [comment]
I also think that you can create minimal reproduction, your backend code with go doesn't really matter. The problem is with Svelte. You can probably create new Svelte project put your init code.

You need to learn how to reproduce the issues when you reporting bugs. You don't need 90% of the code you send to reproduce the issue.

**Comment by jcubic** [comment]
I was not able to debug the code because the file was missing, got null as the filename in dev tools. But it seems that the jQuery Code runs after the jQuery Terminal. That's probably why jQuery is missing.

**Comment by KiddoV** [comment]
> The problem is that you're using import, jQuery Terminal is written as UMD module

I know this lib is in UMD, but why is the ``src/libs/fomantic-ui/fomantic-ui.js`` works. It is also in UMD, and required ``jQuery``.

**Comment by KiddoV** [comment]
> I was not able to debug the code because the file was missing, got null as the filename in dev tools. But it seems that the jQuery Code runs after the jQuery Terminal. That's probably why jQuery is missing.

Were you be able to run ``wails dev``?
What file was missing? Can you share the screenshot of the error?
Thanks,

**Comment by jcubic** [comment]
If you have another library that requires jQuery then probably it loads one jQuery and jQuery Terminal loads another copy.

**Comment by jcubic** [comment]
I have no idea, there are too much happening at the same time.

**Comment by jcubic** [comment]
I will try to create a new svelte project and see what is needed. Will add that to Wiki, when I will solve the problem. Will also try to include two plugins if one will work out of the box.

**Comment by KiddoV** [comment]
That would be nice!
Thank you so much for the help!

**Comment by jcubic** [comment]
I'm not sure about your setup, but here is the Svelte code that works:

```html
<script>
  import jQuery from 'jquery';
  import { onMount } from 'svelte';
  import terminal from 'jquery.terminal';
  import 'jquery.terminal/css/jquery.terminal.min.css';
  terminal(jQuery);
  export let name;
  export const termClass = 'term';
  onMount(() => {
    jQuery(($) => {
      console.log($(`.${termClass}`));
      $(`.${termClass}`).terminal({
        echo(...args) {
          this.echo(args.join(' '));
        }
      }, {
        checkArity: false
      });
    });
  });
</script>

<main>
  <h1>Hello {name}!</h1>
  <p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
</main>
<div class="{termClass}"></div>
```

![Przechwycenie obrazu ekranu_2023-04-27_19-22-25](https://user-images.githubusercontent.com/280241/234940794-04f098a3-977d-4333-af66-d9d4a025c3fa.png)


I've just created a base project and added jQuery Terminal.

**Comment by jcubic** [comment]
this also works but it's an invalid invocation.
```javascript
terminal(jQuery)
```
I've noticed that the unit tests are using this but this is wrong.
This is probably why your code doesn't work with two jQuery plugins.

**Comment by KiddoV** [comment]
It works now! 😱
I didn't know we can import like:
```ts
import terminal from 'jquery.terminal';
```
... because my VSCode always give me this error:
![vs-error](https://user-images.githubusercontent.com/28552977/234954912-7782243a-950d-44b2-b9a1-0b3ecfdbe165.png)
How do I get rid of this error, by the way?

Also, please update the ``jquery.terminal.d.ts`` as it related to this issue: https://github.com/jcubic/jquery.terminal/issues/877

Thank you soooo much! This error giving me headache for months!!!

**Comment by jcubic** [comment]
Already added it to Wiki [Svelte](https://github.com/jcubic/jquery.terminal/wiki/Svelte).
I'm wondering about TypeScript, I used JS will check if importing will throw error also in Emacs.

As for the d.ts file it's already updated but I need to release a new version. Maybe will do that over the weekend. But I will need to move the milestone one version because I was planing fixing more issues.

**Comment by KiddoV** [comment]
The script works regardless, wondering if it something to do with VSCode IntelliSense?

**Comment by KiddoV** [comment]
Should this ``jquery.terminal.d.ts`` file has an ``export`` keyword to work in ES6 module type?

**Comment by KiddoV** [comment]
Hmmm... just found out there is a ticket for this
https://github.com/jcubic/jquery.terminal/issues/844

**Comment by jcubic** [comment]
@KiddoV if you know how to fix it you can contribute. I will be able to release with the code I have on the devel branch. I didn't publish it yet.
