### ISSUE TITLE
how can i put a image as the greeting.

### ISSUE THREAD

**Issue by wk2poor** [jcubic/jquery.terminal#851]
### I have question related to jQuery Terminal

I cant seem to set a image as the greeting in jquery, heres what my code looks like
` greetings: '<img src="sampleimage.jpg">', `

when i do the whole webpage is a white screen which is what usaly happens to me when there is a error. is this feature even possible? also didnt know if i should have marked this as a bug/error or a question so please change the catergory accordingly. thanks

**Comment by jcubic** [comment]
jQuery Terminal doesn't allow raw HTML by default for security reasons. You can use [Terminal formatting syntax for images](https://github.com/jcubic/jquery.terminal/wiki/Formatting-and-Syntax-Highlighting#images):

```javascript
term.echo('[[@;;;;https://placekitten.com/300/300]]');
```

or by adding [XML Formatter](https://github.com/jcubic/jquery.terminal/wiki/Formatting-and-Syntax-Highlighting#extension-xml-formatter) that allows using images.

You can also add this formatter:

```
$.terminal.new_formatter([
    /<img src="([^"]+)"\/>/g, '[[@;;;;$1]]'
]);
```

but with XML Formatter you can also have an alt attribute, and it allows other XML-like tags inside Terminal, that is easier than Terminal formatting syntax.
