### ISSUE TITLE
How to force user to login with a prompt before accepting commands?

### ISSUE THREAD

**Issue by v1ckie** [jcubic/jquery.terminal#852]
### I have question related to jQuery Terminal

I assume it has something to do with setting greeting to a function but I havent been able to find examples

I'm planning on doing this client side for a terminal based story telling project

**Comment by jcubic** [comment]
There is login option, you can read more on a Wiki [Authentication](https://github.com/jcubic/jquery.terminal/wiki/Authentication).

```javascript
$('body').terminal(function(command) {

}, {
   login: function(user, password) {
   }
});
```

The function should return a token or a Promise that resolves to a Promise.

**Comment by v1ckie** [comment]
In the demos for authentication _without_ using a server, the user is able to enter other commands without logging in.

I'm trying to force the user to enter a login before anything else _without_ using a server?

I'm not sure how to do this client side, like the demo for authentication using a server

**Comment by jcubic** [comment]
This is the code:

```javascript
$('body').terminal(function(command) {

}, {
   login: function(user, password) {
      if (user === 'foo' && password == 'bar') {
        return 'TOKEN';
      }
      return null;
   }
});
```

but note that this is not very secure because everyone will be able to see the password by inspecting the code.

**Comment by v1ckie** [comment]
Thank you.

This doesn't need to be secure since I'm going to use it for an interactive story telling project.
