### ISSUE TITLE
How to use ascii_table output

### ISSUE THREAD

**Issue by changfeng2021** [jcubic/jquery.terminal#863]
I don't know how to used ascii_table output , like mysql select command  format . 
please give me an example  Thank you

**Comment by jcubic** [comment]
Here is example:

```javascript
let arr = [[1,2,3,4,5], ["lorem", "ipsum", "dolor", "sit", "amet"]];
term.echo(ascii_table(arr));
arr = [['name', 'command'], ['foo', 'hello'], ['bar', 'world'], ['baz', 'lorem ipsum']];
term.echo(ascii_table(arr, true));
```

The second argument to ascii_table is a flag that indicates if it should use the first element in the array as a header.

You can test this on this [CodePen](https://codepen.io/jcubic/pen/LYygzby?editors=0010).

**Comment by changfeng2021** [comment]
Thanks for your reply
