### ISSUE TITLE
Cursor slows down if typing animation is enabled

### ISSUE THREAD

**Issue by Dev12310** [jcubic/jquery.terminal#864]
### Issue summary
When there is a long text to echo and typing animation is enabled at any delay, the echoing slows down to a very low pace.
### Expected behavior
The cursor should keep moving at same pace.
### Actual behavior
 the echoing slows down to a very low pace after a very specific time
### Browser and OS
Chrome(Version 111.0.5563.65 (Official Build) (64-bit)) and Windows 11 Home

**Comment by jcubic** [comment]
Yes, This is a known issue, I'm closing because this is a duplicate of #820.
