### ISSUE TITLE
Cyrillic not displayed correctly

### ISSUE THREAD

**Issue by ner00** [jcubic/jquery.terminal#868]
I searched for this issue but the only thing I found was the wiki for wide font (Japanese and Chinese) but nothing related to Cyrillic characters. I've also tried with accented characters and it seems to work fine, The issue really seems to be related to the decoding of the output since the terminal itself can display Cyrillic chars if pasted in the prompt.

I'll use a screenshot to demonstrated the issue (top is this shell and bottom is Windows command line):
![firefox_lW7sZ6kOSL](https://user-images.githubusercontent.com/2269603/228388844-d51f978d-4148-4060-974a-295683a280b0.png)

The screenshot shows two issues, one is the echo of the Cyrillic characters, and the other is the actual output from a dir command. I couldn't test this in another OS like Linux to understand if the issue in Windows only.

I framed this as a question because chances are there's something that I should be doing and not an actual bug.

**Comment by jcubic** [comment]
Can you share you project? Do you have `<meta charset="utf-8" />` on the page?

**Comment by ner00** [comment]
json output for the particular filename: 
`12/03/2023  04:23        27 933 178 10. NEUS, ????? ?????????, ???, Atomic Heart - Golden Hoop (NEUS Remix).flac`

**Comment by jcubic** [comment]
I think that the problem is not jQuery Terminal but jsh.php. Can you upload somewhere that file? And what OS you're using Windows or Linux?

**Comment by ner00** [comment]
I'm using Windows.
Can't you use the one in my repo, that I linked above?

**Comment by jcubic** [comment]
I don't use Windows and the repo doesn't have files with Cyrillic letters.

But this looks like the problem with:

```php
$result = sapi_windows_cp_conv(sapi_windows_cp_get('oem'), 65001, $result);
```

Try to test if it works outside of jQuery Terminal. if not then you need to ask somewhere else. But note that when I was asking about this I answered my own question.

**Comment by ner00** [comment]
Indeed, this is seems to be the bit which is problematic in this situation.
```php
$result = sapi_windows_cp_conv(sapi_windows_cp_get('oem'), 65001, $result);
```
In any case, I might lose a bit more time on it but I'm pretty sure that I'll break something else in the process.

Thanks for the suggestions.
