### ISSUE TITLE
Pretty display of error unpauses terminal

### ISSUE THREAD

**Issue by dragoncoder047** [jcubic/jquery.terminal#875]
### Issue summary

when `term::exception()` is used to pretty print the JS error, it allows the user to see the source code of the error by clicking on the file names in the stack trace. But when they do this it enables the terminal regardless of whether the app called `term::pause()`

### Expected behavior

If `term::pause()` has been called, the prompt will not re-appear when the user clicks the traceback links

### Actual behavior

When the user clicks the traceback links, the prompt re-appears

### Steps to reproduce

1. https://jsfiddle.net/cpfe3ray/
2. Click the link for one of the jQuery frames
3. Prompt reappears below traceback frame
4. You can type at the prompt and the command function is called

### Browser and OS

Chrome 108 64-bit on a chromebook.

### Additional notes

I am using this library for a programming language interpreter, when the interpreter suffers a fatal error it is supposed to show the traceback using `term::exception()` and then block the user from entering anything else. But when they click the traceback they get a prompt back and then when they try to enter anything it causes the page to hang.

**Comment by jcubic** [comment]
Added a fix. So a call to resume after Ajax call only when there was no pause before the call.

**Comment by dragoncoder047** [comment]
Great, just checked with bleeding edge version (https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/js/jquery.terminal.min.js) and it works good.
