### ISSUE TITLE
`term::disable()` doesn't do anything

### ISSUE THREAD

**Issue by dragoncoder047** [jcubic/jquery.terminal#876]
### Expected behavior

term::disable() should block further user input

### Actual behavior

The prompt does not go away

### Steps to reproduce

1. https://jsfiddle.net/cpfe3ray/
2. Change `t.pause()` to `t.disable()`
3. Re-run
4. The prompt is there below the error
5. You can type at the prompt and the command function is called

### Browser and OS

Chrome 108 64-bit on a chromebook

**Comment by jcubic** [comment]
Disable disables the terminal it acts like `focus()` when you click the terminal it's enabled.

There is a freeze(), it was reported that it doesn't work properly I didn't have time to make it properly freeze the terminal, so it can't be enabled by clicking on the terminal.

Freeze should make the terminal read-only.

On one branch I was working on a state machine to properly handle all states and properly document the transition from one state to the other. But the code is outdated and too much diverged from the devel branch that it can't be merged.

**Comment by jcubic** [comment]
I'm closing this issue since it's working as expected.

Just use this code:

```javascript
$(() => {
  var t = $("#term").terminal(cmd => {
    try {
      throw new Error("fancy");
    } catch (e) {
      t.exception(e);
      t.disable();
    }
  });
});
```

You will see that disable blurs the terminal. Maybe disable/enable are not the best names, but this is how it works.
