### ISSUE TITLE
How to center greetings or banner? 

### ISSUE THREAD

**Issue by tonmoy998** [jcubic/jquery.terminal#895]

**Comment by jcubic** [comment]
Good question, I need to think about this. I will create a demo tomorrow.

**Comment by tonmoy998** [comment]
Ok :)

**Comment by jcubic** [comment]
It requires a bit of work:

```javascript
const term = $('body').terminal({}, {
    onInit() {
        this.echo('Welcome', {
            finalize(div) {
                div.addClass('center');
            }
        });
    },
    greetings: false
});
```

CSS
```css
.center {
    text-align: center;
}
```

[CodePen demo](https://codepen.io/jcubic/pen/QWJPdZx).

But note that you can't use this code if you have ASCII art, it will probably be messed up if you have ASCII art, like the one rendered with Figlet. You will need to process the string and add spaces to be in the center.
