### ISSUE TITLE
How can I change the CSS background of the terminal from "BLACK COLOR" to "BLUE COLOR"?

### ISSUE THREAD

**Issue by c0de91101** [jcubic/jquery.terminal#899]
Hello. Can you tell me if it is possible to change the CSS background of the terminal from "BLACK COLOR" to "BLUE COLOR"?

```
%%html
<div id=term_demo></div>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery.terminal/js/jquery.terminal.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/jquery.terminal/css/jquery.terminal.min.css" rel="stylesheet"/>
<script>
  $('#term_demo').terminal(async function(command) {
      if (command !== '') {
          try {
              let res = await google.colab.kernel.invokeFunction('shell', [command])
              let out = res.data['application/json'][0]
              this.echo(new String(out))
          } catch(e) {
              this.error(new String(e));
          }
      } else {
          this.echo('');
      }
  }, {
      greetings: 'Terminal',
      name: 'colab_demo',
      height: 320,
      prompt: 'Tech: '
  });
```

**Comment by jcubic** [comment]
You can do this with CSS, check [CSS Style](https://github.com/jcubic/jquery.terminal/wiki/CSS-Style) on a Wiki.

**Comment by jcubic** [comment]
I also suggest not using `https://code.jquery.com/jquery-latest.js` which is outdated, it returns version 1.11.1, and the latest is 3.7. I suggest using jsDelvr:

```html
<script src="https://cdn.jsdelivr.net/npm/jquery"></script>
```

**Comment by c0de91101** [comment]
@jcubic I saw the code in google colab help me change terminal css background from "BLACK COLOR" to "BLUE COLOR"? How to do this please help.
https://colab.research.google.com/drive/1yz-XElYJrW9qoc0Oj1Vy7iDhzCoKWWOs?authuser=3#scrollTo=Kn9S2H8HODQD&line=2&uniqifier=1

**Comment by jcubic** [comment]
```html
<style>
:root {
   --background: blue;
}
</style>
```

**Comment by jcubic** [comment]
When Open the link you get an error in the modal window. Note that other people can't open your private files.
