### ISSUE TITLE
Support jQuery 4.0

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#915]
### I have an idea for a new feature for jQuery Terminal

The base code work after adding:

```javascript
$.isFunction = function(obj) {
    return typeof obj === 'function';
};
$.trim = function(str) {
    return str.trim();
};
```

- [x] Remove those functions
- [x] Update GitHub workflow
- [x] Include jQuery 4.0 on branch
- [x] Run Unit Tests on new branch

**Comment by badulesia** [comment]
Hi.
Can we assume that this will be included in the next release? I'm trying to convert my project to Jquery4. I have some minor incompatibilities with plugins such a Terminal.

**Comment by jcubic** [comment]
Yes, it will be included in the next version. jQuery 4.0 final has not yet been released that's why I haven't published a new version yet.

Temporarily you use grab the file from CDN:

https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/js/jquery.terminal.min.js

**Comment by badulesia** [comment]
Yes I'm aware that Jquery 4 is only at beta stage, and it's fresh. I can assume now this is solved, or soon to be.
Thank you.

**Comment by jcubic** [comment]
I don't have any features or bug fixes to release right now, so I think that I will just release the fix for jQuery 4.0. I'm not sure if should be a bug-fix release or a feature.

**Comment by badulesia** [comment]
Consider the importance of jQuery, make it a feature.
Beyond this, the two functions involved are deprecated since jQuery 3.3. Wouldn't it be better to review the code and remove them? Replace with pure JS.

**Comment by jcubic** [comment]
@badulesia all deprecated functions got removed. Just look at the diff.

**Comment by badulesia** [comment]
I'm not sure in which branch I should check. The Jquery 4 one hasn't been update recently. I do trust you.

**Comment by jcubic** [comment]
Sorry, it's on the devel branch like on the CDN link I've shared.

**Comment by badulesia** [comment]
Perfect, thank you.
