### ISSUE TITLE
Bugs with a large prompt

### ISSUE THREAD

**Issue by ordo-n** [jcubic/jquery.terminal#919]
### Preface
I'm using jqueryterminal 2.39.3 and whenever I have a large prompt 2 things happen on resize of the window or terminal
Here is a screen shot of a large prompt
![image](https://github.com/jcubic/jquery.terminal/assets/166300150/658866ca-4f49-4563-a1f3-6e70dd4b3782)

### Issue summary
1) When i resize the terminal it appears to insert the prompt into the command input that i can press any key and it disappears again, further resizing makes it appear and disappear
![image](https://github.com/jcubic/jquery.terminal/assets/166300150/a546dd13-4cfb-47a1-930e-483186ab6c44)

2) the prompt splits across newlines with breaks inbetween when it should have no blank lines inbetween 
![image](https://github.com/jcubic/jquery.terminal/assets/166300150/932ef62b-af09-45c1-9e8f-d0a364e76f43)

### Expected behavior
1) no blank lines inbetween prompt
2) the prompt should not appear more than once

### Actual behavior
1) blank lines
2) prompt appears more than once

### Steps to reproduce
1) create a large prompt with coloring
2) reduce the width of the browser by a few pixels for prompt to be inserted
3) reduce the width of the browser by a lot to see blank lines appear

### Browser and OS
Tested in chrome latest and edge latest same problem
Windows 10

### Additional notes
I'm using 2.39.3 from a  cdn
As an incentive to fix theses bugs, once a programmer has fixed the bugs and i have tested I am willing to donate to them for their efforts as I am now reliant on this library working

**Comment by jcubic** [comment]
Thanks for reporting. It looks like it happen on initialization, if you resize the window the issue is gone. Also, there is some kind of flicker when you resize, it looks like it renders the wrong prompt and then the prompt is corrected.

Do you have a reproduction of those blank lines?

**Comment by jcubic** [comment]
The first issue of initialization got fixed. The problem was that cmd plugin first rendered the prompt, and they check the size of the character and number of characters per line.

**Comment by jcubic** [comment]
The flicker is probably same behavior you observed with empty lines. When terminal is resized, cmd don't render immediately with new number of characters. And when cmd overflows it shows blank lines because of the `::before` pseudo selector in CSS.

**Comment by jcubic** [comment]
Please check devel version if the issue is fixed. You can use jsDeliver link:

https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/js/jquery.terminal.js

https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@ddf91077011/css/jquery.terminal.css

The CSS have problems to refresh, so there is a hash to commit.

**Comment by ordo-n** [comment]
> Please check devel version if the issue is fixed. You can use jsDeliver link:
> 
> https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@devel/js/jquery.terminal.js
> 
> https://cdn.jsdelivr.net/gh/jcubic/jquery.terminal@ddf91077011/css/jquery.terminal.css
> 
> The CSS have problems to refresh, so there is a hash to commit.

I tested the provided scripts and they contain the bug so i had same problem when tested. Thanks for looking into this

**Comment by jcubic** [comment]
Can you explain what you mean by "contain the bug"?

**Comment by ordo-n** [comment]
![image](https://github.com/jcubic/jquery.terminal/assets/166300150/be3d1286-fdba-466b-8e04-94715eefd872)
by contain the bug i meant i am experiencing the same bug with jquery terminal 2.39.3 and the jsDeliver links

**Comment by jcubic** [comment]
Can you record a video of an error?

https://jsfiddle.net/ebpj5m9w/

**Comment by ordo-n** [comment]
> Can you show the error on this link, that use latest files? Your screenshot use same links as your original bug.
> 
> https://jsfiddle.net/ebpj5m9w/

![image](https://github.com/jcubic/jquery.terminal/assets/166300150/2705e67f-c442-4d05-96f9-e9487675b2f8)

https://jsfiddle.net/v3Lqh7fc/

**Comment by ordo-n** [comment]
you have to play with the width moving it from left to right to change which line the cursor is on

**Comment by jcubic** [comment]
Yes, I can reproduce, it's random when you resize the window. I need to investigate what is going on.

**Comment by jcubic** [comment]
I can reproduce it every time if you open dev tools that is on the side and you have full screen terminal.

**Comment by jcubic** [comment]
It should be fixed now, the problem was that the draw command line function get prompt from previous render. That's why when you have big change of the size (like with dev tools open) the bug was visible.

Try again same link, I've purged the cache so you should be able to just refresh the demo.

**Comment by jcubic** [comment]
I also fixed jumping of text when resizing a long prompt. Below the line in prompt there was an empty line for as split second. Now it should look smooth.

**Comment by ordo-n** [comment]
can confirm its fixed can close issue now
