### ISSUE TITLE
Conflict with other library!!

### ISSUE THREAD

**Issue by KiddoV** [jcubic/jquery.terminal#931]
### Issue summary

I am using ``jquery.terminal`` with other library ([Inputmask ](https://github.com/RobinHerbots/Inputmask) and [VisActor/VTable](https://github.com/VisActor/VTable)) in my application.

I created a custom editor for the VTable with Inputmask, when using it I realized when hitting the ``Escape`` key within the editor, ``jquery.terminal`` just called a method and throw an error for no reason, even though I was not calling anything within the ``jquery.terminal`` scope.

I think there might be a conflict jQuery between ``jquery.terminal`` and ``Inputmask`` library.

The error came from this library so I think I might raise an issue here first.

### Expected behavior

No error from ``jquery.terminal`` should be logged into the console when hitting ``Escape`` key on the editor.

### Actual behavior

Got the error:

```console
Uncaught TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.
    at HTMLDocument.disable (jquery__terminal.js:10694:35)
    at HTMLDocument.dispatch (chunk-OPGWJREC.js:2821:102)
    at elemData.handle (chunk-OPGWJREC.js:2709:113)
    at t2.trigger (inputmask.js:215:60)
    at HTMLInputElement.keyEvent (inputmask.js:440:280)
    at HTMLInputElement.l2 (inputmask.js:653:34)
```

### Steps to reproduce

Here is the minimal example you can use:
https://codesandbox.io/p/sandbox/vtable-simple-demo-forked-wm9ph4?file=%2Fsrc%2Findex.ts%3A61%2C38

1. Open the example.
2. Double click on the first cell to enable the custom editor I made with Inputmask.
3. Hit the ``Escape`` key to exit editor mode.
4. ===> ERROR will occurs 

### Browser and OS

Any

### Additional notes

![bug](https://github.com/jcubic/jquery.terminal/assets/28552977/4395dbfe-0b35-4025-8763-c4470575391d)

**Comment by jcubic** [comment]
This is the code that is using that function:


```
function disable(e) {
    if (is_mobile) {
        return;
    }
    e = e.originalEvent;
    if (e) {
        // e.terget is body when click outside of context menu to close it
        // even if you click on terminal
        var node = document.elementFromPoint(e.clientX, e.clientY);
        if (!$(node).closest('.terminal').length && self.enabled()) {
            // we only need to disable when click outside of terminal
            // click on other terminal is handled by focus event
            self.disable();
        }
    }
}
self.oneTime(100, function() {
    $(document).bind('click.terminal_' + self.id(), disable).
        bind('contextmenu.terminal_' + self.id(), disable);
});
```

For some reason, this library trigger click event without `clientX` and `clientY`.

This is easy to fix, since real click event have `isTrusted === true`.

**Comment by jcubic** [comment]
It should be fixed now, but you need to test locally with devel branch.

You can do this by cloing the repo, checkout devel branch and using [npm link](https://docs.npmjs.com/cli/v6/commands/npm-link).

**Comment by KiddoV** [comment]
I managed to test it using ``npm install github:jcubic/jquery.terminal#devel`` without cloning the entire repo.
It works! No more ERROR. Thank you!

**Comment by jcubic** [comment]
Oh, didn't know you can install from GitHub. Good to know. I'm releasing `2.40.2` with the fix.
