### ISSUE TITLE
Infinite Loop when animating of empty line

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#946]
### Issue summary

When you echo `\n\n` with typing animation it prints `undefined` in a loop

### Expected behavior
It should skip the line

### Actual behavior
It create infinite loop

### Steps to reproduce
1. Open demo https://codepen.io/jcubic/pen/bGyNQvB?editors=0010

### Browser and OS
N/A

**Comment by Tman1314** [comment]
Unfortunately this isn't resolved yet. Both the Codepen (in the issue text) and if you get a certain joke from the programmer joke API used in the intermediate tutorial in the documentation the issue still presents. Maybe including a way to interrupt the output of the typing animation similar to using `ctrl+ c` in linux when a command is running.

**Comment by jcubic** [comment]
It is resolved on the devel branch. When this is released the issue will be closed.

**Comment by jcubic** [comment]
Just released a new version. Thanks for the reminder.

**Comment by jcubic** [comment]
Actually, the error was not fixed the repro still shows an issue, but the `undefined` disappear when you run `term.skip()` that was used in demo.

**Comment by jcubic** [comment]
The actual fix was released in version 2.42.2
