### ISSUE TITLE
Autofill Interaction Causes Error in `jquery.terminal` - (Conflict libs ?)

### ISSUE THREAD

**Issue by KiddoV** [jcubic/jquery.terminal#977]
### Issue summary
When using the autofill feature in forms, I encounter an error in the ` jquery.terminal` library. 
Specifically, the error message is:

```error
Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
```

### Expected behavior
No ERROR when using autofill in a form.

### Steps to reproduce
* Fill the form with `AutoFill`
* Watch the error in console

https://jsfiddle.net/KiddoV/pdt2m5k0/17/

### Browser and OS
Webview 2
Windows 10

### Additional notes

![jq-term-error](https://github.com/user-attachments/assets/45ecbffd-5622-4353-9b55-339d9279a41b)

**Comment by jcubic** [comment]
It looks like the keydown event is triggered without the [key property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) that is supported by all major browsers.

**Comment by jcubic** [comment]
Should be fixed, the problem was that keydown even always intercepts all events even when terminal is disabled. So you can use `CTRL+D` to resume. And the autofill triggered fake keydown event.

**Comment by KiddoV** [comment]
I tested the `devel` branch and it is **fixed**!
Thanks for the quick patch!
