### ISSUE TITLE
{ raw:true } for prompts

### ISSUE THREAD

**Issue by phook** [jcubic/jquery.terminal#991]
### Prompts should support raw in the same manner as echo

I am trying to create clickable functionality in the prompt, in order to enable opening/closing functionalty of the output from the prompt. Seems to me a raw option in set_prompt could solve my problem.

**Comment by jcubic** [comment]
I don't think this is a good idea, the prompt and CMD plugin (the input) needs to have specific DOM structure otherwise it can randomly break. I don't want to allow putting there any HTML.

But you still can create links inside the prompt, and add events to them.

```javascript
const term = $('body').terminal({}, {
    prompt: '[[!;;;toggle;#toggle]toggle]$ '
});

term.on('click', '.toggle', () => {
    const output = term.find('.terminal-output');
    if (output.is(':visible')) {
        output.slideUp();
    } else {
        output.slideDown();
    }
    return false;
});
```

Or if you use XML_formatting file, you can use:

```javascript
const term = $('body').terminal({}, {
    prompt: '<a href="#link" class="toggle">toggle</a>$ '
});
```

**Comment by jcubic** [comment]
Here is a demo https://codepen.io/jcubic/pen/YPKpWjQ

**Comment by phook** [comment]
Well, it seems I just needed to add the xml_formatting.js,
Before that the prompt didn't respond to markup - so I guess I just failed to find the correct solution in the docs :-)

**Comment by jcubic** [comment]
`xml_formatting` is not exactly Full HTML, internally the XML structure is converted to flat list of `[[;;]]..]` formatting. It's only easier to use than internal formatting syntax.
